### ISSUE TITLE
Zero-downtime Upgrade Research

### ISSUE THREAD

**Issue by caniszczyk** [cncf/cluster#1]
### First Name

Stuart
### Last Name

Williams
### Email

stuart@weave.works
### Company/Organization

Weaveworks
### Job Title

Director of Product Management
### Project Title

Zero-downtime Upgrade Research
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Infrastructure components are now often containerized, upgrading them without causing, or minimising downtime presents challenges that are not adequately explored in cloud native environments.
### Briefly describe the project

We will try various scenarios, at scale, that upgrade container-based infrastructure and validate that applications using those services are impacted or impeded in their operation.
### Do you intend to measure specific metrics during the work? Please describe briefly

Liveness of applications and error detection
### Which members of community and/or end-users would benefit from your work?

Users of containerized infrastructure components will benefit from our learnings.
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Yes. Results will be published & changes to OSS described in a blog
### Are there identified risks which would prevent you from achieving significant results in the project ?

No
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip questions 2 through 4.

No
### Please list project titles associated with prior CNCF cluster usage.

n/a
### Please list contributions to open source initiatives for projects listed in question 2. If you did not upstream the results of the open source initiative in any of the projects, please explain why.

n/a
### Have you ever been denied usage of the cluster in the past? If so, please explain why.

n/a
### Please state your contributions to the open source community and any other relevant initiatives

All Weave products are OSS; our employees have created and contributed to many OSS projects - from Linux kernel patches, to ASF & Eclipse projects, to founding RabbitMQ.
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

1000 nodes
### Duration of request (minimum 24 hours)

120 hours
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

With OS.
### Any other relevant details we should know about while preparing the infrastructure?

Not yet.

**Comment by cncfclusterteam** [comment]
@caniszczyk is this request still valid?

Furthermore, there won't be 1000 nodes available until early Q2'17 and even then it will probably be closer to 900 as stated in our [README](https://github.com/cncf/cluster/blob/master/README.md).

**Comment by caniszczyk** [comment]
Thanks for following up @cncfclusterteam, lets ping @pidster and ask

**Comment by pidster** [comment]
You can close this, thanks.
