### ISSUE TITLE
Scalability for Kubernetes, Swarm, Mesos on OpenStack

### ISSUE THREAD

**Issue by duglin** [cncf/cluster#10]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Doug

### Last Name
Davis
 
### Email
 dug@us.ibm.com

### Company/Organization
IBM
 
### Job Title
STSM
 
### Project Title
Scalability for Kubernetes, Swarm, Mesos on OpenStack
 
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
We want to see how prevalent platforms for containers would scale on
an OpenStack infrastructure.  The platforms include Kubernetes, Swarm
and Mesos.  As part of the study, we expect to identify bottlenecks to
fix and best practices for operating a large scale platform for
containers.  We have been working on building these platforms for the
past 1.5 years.  We have made some initial benchmark runs on a smaller
scale environment.
 
### Briefly describe the project
OpenStack provides cloud IaaS and Magnum is a service to deploy and
manage platforms for hosting containers on OpenStack.  Currently it
supports Kubernetes, Swarm and Mesos.  Each cluster is fully
integrated into OpenStack by leveraging services such as Keystone,
Nova, Neutron, Cinder, etc.

To support large scale container hosting, we need to understand the
scalability of these clusters from several perspective: many users
running multiple clusters, large cluster, launching many containers,
managing large number of containers, etc.
 
### Do you intend to measure specific metrics during the work? Please describe briefly
To study these scenarios, we have developed a set of Rally benchmarks
to run the scenarios and collect performance data.  Rally automatically
measures many metrics such as success rate, launch time, etc.
 
### Which members of community and/or end-users would benefit from your work?
Several OpenStack projects will benefit from the study:  Magnum, Heat, Neutron
This should also help validate upstream container platforms:  Kubernetes, Swarm, Mesos
We plan to coorelate performance data published by Kubernetes to establish
the baseline.
 
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?
Yes, we currently have a presentation proposal on this data for the
next OpenStack summit in October 2016
 
### Are there identified risks which would prevent you from achieving significant results in the project ?
No
 
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip questions 2 through 4.
No
 
### Please list project titles associated with prior CNCF cluster usage.
N/A
 
### Please list contributions to open source initiatives for projects listed in question 2. If you did not upstream the results of the open source initiative in any of the projects, please explain why.
We have contributed code in OpenStack to deploy Kubernetes, Swarm, Mesos.
We have done performance study on Kubernetes networking.
We currently have 6 patches in Rally to test various container scenarios.
We have made 2 presentations at the OpenStack Summit related to containers.
 
### Have you ever been denied usage of the cluster in the past? If so, please explain why.
No
 
### Please state your contributions to the open source community and any other relevant initiatives
Two of the three members of the team are core contributors in OpenStack
One member has been contributing for the past 3 years. 

### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.
50 nodes, followed by 500 nodes
 
### Duration of request (minimum 24 hours)
50 nodes for 1 week to build OpenStack and run initial benchmarks
followed by 500 nodes for 1 week to run full scalalibity benchmarks.
 
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?
With Ubuntu 14.04

### Any other relevant details we should know about while preparing the infrastructure?
It would be preferrable to have 2 network interface on the nodes, with separate networks.

**Comment by caniszczyk** [comment]
Hey @cncf/intel-cluster-team, can you review this?

**Comment by duglin** [comment]
tap tap tap - this thing on?  :-)

**Comment by duglin** [comment]
Should I just assume that the cluster isn't actually ready for use?  3 weeks is a long time to not hear any kind of response at all.

**Comment by caniszczyk** [comment]
@duglin I'll email the @cncf/intel-cluster-team and cc you, a lot of them are away on vacation during August since many are based in Europe :)

**Comment by dankohn** [comment]
We're escalating this and will get back to ASAP.
 





On Wed, Aug 31, 2016 8:02 AM, Doug Davis notifications@github.com
wrote:
Should I just assume that the cluster isn't actually ready for use? 3 weeks is a
long time to not hear any kind of response at all.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--Dan Kohn <mailto:dan@linuxfoundation.org>Executive Director, Cloud Native
Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by cncfclusterteam** [comment]
@duglin We have the ability to grant the initial 100 nodes, but we can only provide an additional 260 nodes by week 2 (360 total by week 2).  We have 2 other tenants that will consume the remaining capacity.  Will this work for you?  If not, we will have to wait until the other tenants complete their 2 week cycle.  /cc @cncf/intel-cluster-team

**Comment by duglin** [comment]
@cncfclusterteam we're ok with a smaller amount initially as long as we can hold on to them until we get the full amount (500), which we'll then need for 1 week.

**Comment by cncfclusterteam** [comment]
@duglin Until we expand the capacity to a full 1000 nodes, which we are hoping to complete in Q4, the best we can do is give you a total of 380-390 nodes in the second week.  This is the maximum allocation until we add the expanded capacity.  Let me know if this works.

**Comment by duglin** [comment]
@cncfclusterteam ok, we'll take whatever we can get  :-)

**Comment by cncfclusterteam** [comment]
Doug,

We are in the process of preparing the environment for you.

**Comment by duglin** [comment]
@cncfclusterteam excellent - thanks!
