### ISSUE TITLE
Machine in support of Jaeger project security audit

### ISSUE THREAD

**Issue by objectiser** [cncf/cluster#103]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Gary Brown

### Email
gbrown@redhat.com

### Company/Organization
Red Hat

### Job Title
Principal Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Jaeger installation for security audit.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
A third party company will be performing a security audit on the Jaeger project. They requested a running environment with "standard" configuration where they can SSH to, run test applications, and do penetration testing.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes
https://github.com/jaegertracing
Project maintainer.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
1 x c1.small.x86

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
CentOS 7

**Comment by dankohn** [comment]
+1

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by taylorwaggoner** [comment]
@objectiser, I have invited you to the Jaeger Security Audit project that I set up in Packet.  Please provide the email addresses of the people from the third party company that will need access to this project and I will invite them as well.  Thanks!

**Comment by objectiser** [comment]
@taylorwaggoner Thanks! Their email addresses are:

 dario@cure53.de
 jesper@cure53.de
 julian@cure53.de
 mario@cure53.de
 mike@cure53.de
 niko@cure53.de

If you could also please add other maintainers from the Jaeger project:

ys@uber.com
ploffay@redhat.com
jpkroehling@redhat.com

**Comment by objectiser** [comment]
and one other maintainer:

 p.r@uber.com

Thanks.

**Comment by taylorwaggoner** [comment]
@objectiser I've invited everyone to the Jaeger Security Audit in Packet.  Please let us know if you need anything else.  Thank you!

**Comment by objectiser** [comment]
@taylorwaggoner Thanks.

**Comment by objectiser** [comment]
@taylorwaggoner would it also be possible to add another user? kearls@redhat.com

Let me know if there is a different approach for adding extra users. Thanks.

**Comment by taylorwaggoner** [comment]
@objectiser I've added kearls@redhat.com to the project in Packet.  Totally fine to request adding more users here or you can email me at twaggoner@linuxfoundation.org.  Thanks!

**Comment by objectiser** [comment]
@taylorwaggoner Could you also add gbaufake@redhat.com thanks!

**Comment by taylorwaggoner** [comment]
@objectiser I've added gbaufake@redhat.com, thanks!

**Comment by vielmetti** [comment]
This project is complete, with the last machines from it deleted in May 2021.  I've removed the project, and if additional resources are needed please open a new issue. thanks!
