### ISSUE TITLE
Request Gromacs parallel MD

### ISSUE THREAD

**Issue by timofeevboris** [cncf/cluster#104]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### Any other relevant details we should know about?
[Boris.txt](https://github.com/cncf/cluster/files/2837922/Boris.txt)

**Comment by dankohn** [comment]
Sorry, this isn't enough info to go on. Could you please fill out a new form (rather than attaching a text file) and provide detailed info on what you're looking to do to gromacs?
