### ISSUE TITLE
CNCF cluster access to test weave-net scaling

### ISSUE THREAD

**Issue by murali-reddy** [cncf/cluster#105]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Murali Reddy

### Email

murali@weave.works

### Company/Organization

https://www.weave.works/

### Job Title

Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

Scaling weave-net as CNI for Kubernetes cluster of 100 or 1000's of nodes size

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Weave-net is a CNI implementation that is widely used in production Kubernetes clusters. It is prescribed and found to work pretty good to the cluster sizes of 100 nodes. When the cluster size exceeds couple of hundreds weave-net becomes resource intensive and becomes essentially unusable. 

Here are the couple of tracking issues.

https://github.com/weaveworks/weave/issues/3595
https://github.com/weaveworks/weave/issues/3593
https://github.com/weaveworks/mesh/issues/100
https://github.com/weaveworks/mesh/issues/102

We are optimising the functionality so that Weave-net works with Kubernetes clusters of couple of hundreds of nodes if not thousands. We are hoping to use the CNCF cluster servers to perform scaling tests and verify the fixes that we have been working and quickly fix any issues found. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes its 100% open source code that we will testing.  https://github.com/weaveworks/weave is fully open source project.

I am one of the maintainers of the weave-net project.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

Configuration similar to c1.small.x86 is enough

We will need at-least 150 nodes minimum and maximum of 300 for duration of 3-5 days would be great. 

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Either Ubuntu/CentsOS with recent kernels. 

### Any other relevant details we should know about?

We will need root access to the nodes.

**Comment by dankohn** [comment]
We're happy to approve this from CNCF, but it's on the high end of what we've ever requested from Packet. @vielmetti can say whether this is feasible, and if so, if there are specific issues around server types or timing.

**Comment by vielmetti** [comment]
Thanks @dankohn - @murali-reddy in principle this would be an excellent thing to do, in practice to do this on bare metal we would need this to coincide with timing of acquisition of new hardware.

Do the nodes all need to be in the same data center? (I suspect the answer is yes, but I don't know for sure.)

Can you do some of this with virtual machines? Our biggest systems can run VMs in some quantity given the appropriate software that you would be responsible for, if the nature of the scaling can be addressed by VMs this would be much easier to pull off.

**Comment by murali-reddy** [comment]
@vielmetti VM's are fine. So if we can spin up 150-200 VM's on 20-30 nodes that would be great. No need for same datacenter. As long as if i can use it for provisioning a Kubernetes cluster across the VM's that's enough.

**Comment by jacobsmith928** [comment]
great @murali-reddy - we can provide 30 nodes (or more, if needed) in a single datacenter (ewr1) of this config: https://www.packet.com/cloud/servers/m1-xlarge/

Look forward to supporting you during your tests!

**Comment by taylorwaggoner** [comment]
@murali-reddy I have sent you an invitation from Packet.  Please let me know if there's anyone else I should invite to your project.  Thanks!

**Comment by murali-reddy** [comment]
Please include @bboreham (bryan@weave.works) as well.

> great @murali-reddy - we can provide 30 nodes (or more, if needed) in a single datacenter (ewr1) of this config: https://www.packet.com/cloud/servers/m1-xlarge/

Sounds good @jacobsmith928 thanks.

**Comment by taylorwaggoner** [comment]
@murali-reddy, I've sent Bryan the invitation from Packet.  Thanks!

**Comment by jacobsmith928** [comment]
Look forward to hearing the results on this one!
