### ISSUE TITLE
freedesktop.org CI runners

### ISSUE THREAD

**Issue by fooishbar** [cncf/cluster#106]
### First and Last Name

Daniel Stone (daniels)

### Email

daniel@fooishbar.org

### Company/Organization

freedesktop.org / X.Org Foundation

### Job Title

Administrator / Chief Cat Herder

(my day job is at Collabora Ltd. where I work on a number of OSS projects, this among them; I'm applying purely on behalf of fd.o as an OSS project)

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

x86-64 and ARM CI for Mesa, Wayland, X.Org, Linux kernel, GStreamer, VirGL, libinput, libfprint, ...

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

freedesktop.org is a 'forge'-like host for a number of low-level open-source projects.

Probably our most active focus is on open-source graphics enablement, where we develop graphics support for the Linux kernel (hosting all the DRM trees and test suites) and userspace (hosting [Mesa](https://www.mesa3d.org) for OpenGL/Vulkan drivers, the Wayland and X.Org window systems).

However, we also host a lot of low-level Linux infrastructure as described on [our software page](https://www.freedesktop.org/wiki/Software). D-Bus development is still hosted on fd.o, systemd development began there and still has its website and mailing lists there, and Flatpak also began its life hosted on fd.o.

We would like to have better and faster CI runners for the projects that we host. We currently have two GitLab CI runners - one on GCE and another on Hartzner - but they are quite overloaded and we cannot afford too much more at the moment. We would also love to allow our projects to run native CI on Arm platforms.

These servers would be runners for GitLab CI, which works entirely in Docker containers, though some of our projects use tools like kaniko and buildah to construct their container environments.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

The code we host is 100% open source.

fd.o has a [GitLab instance](https://gitlab.freedesktop.org) where all our code is kept. This request is for a shared GitLab runner to run jobs from all these projects and their corresponding user forks.

I am one of the three people who run fd.o overall, and its primary admin.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

Err ... fast ones? It's difficult to say as people have been deliberately limiting their CI usage due to it being overloaded - sometimes we have end-to-end latencies of around 5 hours for pipelines which should only take around 15 minutes.

I would suspect probably c1.xlarge.x86 (we don't seem to use too much RAM, and having NVMe is always good) and c1.large.arm.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Most likely COS / Container Linux, as all we need to do is run containers. No special network configuration e.g. VPC.

### Any other relevant details we should know about?

More than happy to discuss anything about fd.o if you would like.

Thanks for your consideration!

**Comment by jacobsmith928** [comment]
Thanks Daniel!  @dankohn can also chime in but it would seem like since this is an ongoing CI request, it would be better handled / supported directly through Packet's open source program vs through the CNCF CIL.

I would suggest c1.small or c2.medium for x86 builds, and our upcoming Ampere (c2.medium.arm) for Arm.  @vielmetti can be a resource there.

Please comment on this issue and if you would like to proceed with OSS support drop me an email via jacob@packet.com to arrange.  It would be helpful if you can signup for a Packet account as well for easy setup.

**Comment by fooishbar** [comment]
@jacobsmith928 Thanks a lot! I'll chase this up privately.
