### ISSUE TITLE
Request for access for Vitess Project (CNCF member project)

### ISSUE THREAD

**Issue by dkhenry** [cncf/cluster#107]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Daniel Kozlowski

### Email
koz@planetscale.com

### Company/Organization
Planetscale

### Job Title
Minister of Engineering

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Native Large Scale Vitess Testing

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Vitess has been run at massive scale by various companies, but there is currently no public large scale tests that have been run. Running on packet would be an excellent performance comparison to other workloads that have been used. Also vitess has first class support for multiple datacenters, but the open source implementation of failover is not as broadly tested as the proprietary versions

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, github.com/vitessio/vitess, I am a maintainer

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
m2.xlarge
c2.medium
(maybe) c1.large.arm

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Linux

**Comment by dankohn** [comment]
If it's just these 3 machines, this looks good. If you're looking for many
instances of these 3 machines, we'll need to ask Packet to OK it.

+1
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dkhenry** [comment]
It would be many instances of those machines, normally I just count cores and I would like to run 1000 cores if I could, and I don't even know where to being with ARM. Also I don't know how many data centers I have access to, but we would like to run across multiple data centers.

**Comment by dkhenry** [comment]
Also fewer cores would be fine ( just let me know how many I can use ), and the test normally takes about 12 hours ( loading data, and then running TPC like workloads )

**Comment by jacobsmith928** [comment]
Thanks @dkhenry for the details.  How long would the scale test run?

**Comment by dkhenry** [comment]
About 12 hours or so, depending on how fast I can load a few TB of data

**Comment by jacobsmith928** [comment]
Awesome @dkhenry could you try with m1.xlarge?  This will allow me to give you the same config across four facilities.  If that works, @taylorwaggoner can get you setup and you can grab:

EWR1 - 40 x m1.xlarge.x86 (960 cores)  <- you can grab up to 60 of these if you want.
SJC1  - 3 x m1.xlarge.x86 (72 cores)
NRT1 - 10 x m1.xlarge.x86 (240 cores)
AMS1 - 4 x m1.xlarge.x866 (96 cores)

Sort of imbalanced but hopefully it accomplishes what you need.  Let me know any feedback.

**Comment by dkhenry** [comment]
That will be awesome. The unbalanced deployment is actually closer to a real world setup that completely balanced setups

**Comment by taylorwaggoner** [comment]
@dkhenry, I've created your project and invited you to it in Packet.  Please let me know if there's anyone else you'd like added.  Thanks!
