### ISSUE TITLE
Cluster access for Apache ZooKeeper

### ISSUE THREAD

**Issue by skamille** [cncf/cluster#11]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.
### First Name

Camille
### Last Name

 Fournier
### Email

 camille@apache.org
### Company/Organization

 ZooKeeper
### Project Title

 ZooKeeper
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Distributed coordination service
### Briefly describe the project

Distributed Coordination Service
### Do you intend to measure specific metrics during the work? Please describe briefly

This will be used to help create a reproducible process for vetting release candidates
### Which members of the CNCF community and/or end-users would benefit from your work?

Anyone using Apache ZooKeeper, which is a very long list
### Is the code that you’re going be running 100% open source? If so, what is the URL or URLs where it is located?

Yes, zooeeper.apache.org
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Anything that becomes a reusable artifact will be published as source code, and I certainly hope we can get something done in the next 2 months
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?

Maybe? Maybe? Maybe?
### Are there identified risks which would prevent you from achieving significant results in the project ?

Fully volunteer group is busy
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.

 no
### Please state your contributions to the open source community and any other relevant initiatives

 TOC member for CNCF
PMC member for Apache ZooKeeper
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

 50 nodes
### Duration of request (minimum 24 hours)

 open-ended
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

with
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

reproducible end-to-end and stress testing of distributed systems is a good thing for all of us
### Any other relevant details we should know about while preparing the infrastructure?

JVM

**Comment by cncfclusterteam** [comment]
Hi @skamille, unfortunately open-ended access is not possible. Would you like to rephrase this request to fit our requirements (i.e. max request time being 2 weeks) or can we close it?

Thank you
