### ISSUE TITLE
Hyperledger Ursa Gitlab CI runners.

### ISSUE THREAD

**Issue by dhuseby** [cncf/cluster#111]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
David Huseby

### Email
dhuseby@linuxfoundation.org

### Company/Organization
Hyperledger/Linux Foundation

### Job Title
Security Maven

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Hyperledger Ursa CI/CD runners and reproducible builds.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
The Hyperledger Ursa project uses the Gitlab CI system for coordinating the builds for our CI/CD system. The runners are crowdsourced and run by volunteers. We'd like access to the CNCF resources so that we can always have some number of machines available to do a build even when our volunteers have their machines offline. The end goal is to mature the CI/CD process to do reproducible builds since Ursa is a crypto library.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/hyperledger/ursa

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)? 
To start we only need 5-10 of the c1.small.x86. We may need to scale up as the demand on our CI/CD system grows, but again, we're trying to crowdsource as much as possible and these machines are just to provide a backstop. Our build passes are CPU bound so it's more important for us to have many smaller machines than a few large ones.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)? 
We'll be running custom Ubuntu 18.04 docker images set up to be Gitlab runners.

### Any other relevant details we should know about?
We're your neighbors; hi neighbors!

**Comment by dankohn** [comment]
+1

**Comment by jacobsmith928** [comment]
Howdy neighbors!  Happy building.

**Comment by taylorwaggoner** [comment]
@dhuseby I've created the Hyperledger Ursa project and have invited you to it.  Please send emails of anyone else that should be invited.  Thanks!

**Comment by dhuseby** [comment]
@taylorwaggoner working on that now. Thanks!

**Comment by vipinsun** [comment]
Volunteering to manage the machines

**Comment by vielmetti** [comment]
The "Hyperledger Ursa" project in the CIL has been closed out, due to non-use since 2019. Please feel free to open up a new issue if there's any future need for use.
