### ISSUE TITLE
Request for access for FredProject

### ISSUE THREAD

**Issue by SilverShades02** [cncf/cluster#112]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Jyotiraditya Panda

### Email

jyotiraditya182@gmail.com

### Company/Organization

FredProject

### Job Title

Lead Developer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

FredOS/FredProject

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

FredOS is an Android Pie custom ROM project based straight off CAF's Android for MSM sources, which is basically AOSP enhanced for Qualcomm Snadragon devices. With the server we can build our ROM for several devices supported by us and can maintain our source also we can host our website too ( we are working on https://myfrom.github.io/fredos.github.io/ )

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes,
MainORG: github.com/FredProject
as we're doing a rebase then : github.com/FredRebase

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

m2.xlarge.x86 will be preferable. Many custom ROM teams are using that .

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu 18.04

**Comment by dankohn** [comment]
This is open source but not particularly cloud native. @vielmetti should make the call. Thanks.

**Comment by jacobsmith928** [comment]
Please submit this request through Packet's open source request form, as I
believe the request is for long term support.

**Comment by dankohn** [comment]
Here's the URL: https://www.packet.com/developers/open-source/
