### ISSUE TITLE
Infrastructure request for linkerd

### ISSUE THREAD

**Issue by cpretzer** [cncf/cluster#113]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Charles Pretzer

### Email
charles@buoyant.io

### Company/Organization
Linkerd

### Job Title
Field engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Testing and development for the CNCF Project, linkerd

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Run tests to ensure compatibility and stability

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, the code is 100% open source: https://github.com/linkerd/linkerd https://github.com/linkerd/linkerd2

I am member of and contributor to the community

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
5 c1.small.x86

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Debian 9

### Any other relevant details we should know about?
I am employee of Buoyant, the primary sponsor of the linkerd project.

**Comment by dankohn** [comment]
This isn't specific enough of what you want to do. But, are you sure you don't want to just get added to the existing linkerd account? If so, please email info@cncf.io and you can close this issue.

**Comment by cpretzer** [comment]
@dankohn thanks for the quick reply.

One of my colleagues suggested opening this request directly, rather than contacting the CNCF.

This request is the same as #66 and #68 

Charles

**Comment by dankohn** [comment]
We are the CNCF. Could you please email info@cncf.io and @taylorwaggoner will get you added.

**Comment by cpretzer** [comment]
Will do, thanks.
