### ISSUE TITLE
request access

### ISSUE THREAD

**Issue by anitosh-cloudstack** [cncf/cluster#119]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Anitosh Saha
### Email
onpremcloudlink@gmail.com
### Company/Organization
Freelancer
### Job Title
DevOps engineer
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Bind container project
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
not created yet
### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
bare-metal
### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu (14.04, 16.04, 17.10, 18.04)
Debian (8, 9)

**Comment by dankohn** [comment]
Thanks for your interest. Please open a new issue when you have more details and, most important, have open sourced the code you'll be working with.
