### ISSUE TITLE
Performance and scalability testing of Hyperledger Iroha peers in the networks of different configurations

### ISSUE THREAD

**Issue by LiraLemur** [cncf/cluster#121]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Sara Garifullina

### Email

garifullina@soramitsu.co.jp

### Company/Organization

Myself working in Soramitsu Co. Ltd; Requesting help for a project hosted by Hyperledger based on their advice

### Job Title

Community manager

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

We want to do performance testing of an open-source DLT framework Iroha

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We work on creating HL Iroha – an easy-to-use, client friendly private blockchain platform for universal use. We would like to ask for resources to do the performance and scalability testing of Hyperledger Iroha peers in the networks of different configurations because there are many questions regarding the performance results from the community and to help more people use this technology, we would like to run performance tests and analyze how well does the network behave in geographically distributed setting, and how is performance affected by increasing the network size.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

All the code is 100% open-source.
https://github.com/hyperledger/iroha/ — main repo with the whole code. 
I personally work for a company that helps maintaining it both by code contributions and by helping the community to use the platform.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

We would like to use https://www.packet.com/cloud/servers/x1-small/ 100 servers because the idea is to set up 100 nodes for a thorough testing. If that is not possible, we can try and set up several nodes on each machine. 

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu 18.04

### Any other relevant details we should know about?

We used your help before this year (https://github.com/cncf/cluster/issues/109) as we were getting to the beta-testing. Now Iroha is production ready (v1.1.1) and we would like to check its performance to share the results with everyone, so @dhuseby from Hyperledger suggested we could ask for your help again. We (and our community) would really appreciate that. Thank you!

**Comment by dankohn** [comment]
+1, modulo @vielmetti and @jacobsmith928 confirming that 100 smalls is feasible and advising on type and how long they can be used.

**Comment by vielmetti** [comment]
@dankohn - @taylorwaggoner and I are working through some kind of review of overall cluster usage - once we walk through some of the older and some of the heavier usage projects it should be more clear how and when this can be fulfilled.

Given the size of this request and the nature of the testing I'd recommend consideration of the Packet "spot market" for this effort - in particular this would give you some sense of resiliency testing as well should nodes drop out of the network due to resource contention or other chaos monkey-style failures.
