### ISSUE TITLE
CNCF cluster around NixOps/Security Audits

### ISSUE THREAD

**Issue by RaitoBezarius** [cncf/cluster#122]
### First and Last Name
Ryan Lahfa

### Email
ryan at lahfa ⋅ xyz

### Company/Organization
Freelancer

### Job Title
Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

- Various NixOps improvements (performance, consistency, shared statefile issue) to make it usable for serious deployments.
- Security audits on K8s, cAdvisor, mostly around Docker ecosystem (using notably Kube-Hunter and some tools like this, I'd like to experiment deploying "real-world clusters" and study multiple configurations and see how to detect misconfiguration properly, write auto-detection for Kube Hunter from Aqua Security for example).

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

- Testing the above-mentioned tools ;
- Performing penetration tests against the servers ;
- Running large scale deployments and documenting how to do X in NixOps/NixOS ;

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

- <https://github.com/NixOS/nixops/tree/master/nixops>
- <https://github.com/aquasecurity/kube-hunter/>
- Plus, all the NixOS/Nixpkgs stuff which is open source too.

Just an open-source enthusiast :). I am in non-profit orgs which also uses OSS but those are not really related to cloud.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

Most likely 3 ~ 4 c1.small for K8s, very short-term/temporary "large" instances sometimes (to test large scale Nixops deployments) up to X machines where X is whether you deem to be the max.
I guess it'd be amazing to have X >= 10 to do multi-tier deployments, but it's really up to you.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

That's not really a surprise, but NixOS all the way.

### Any other relevant details we should know about?

None, AFAIK.

**Comment by dankohn** [comment]
I'm approving this for the small deployments. Please come back here and let us know prior to doing large instances or higher numbers. Good luck.

**Comment by RaitoBezarius** [comment]
@dankohn Alright, thank you. How to proceed from then? Should I expect an email?

**Comment by taylorwaggoner** [comment]
Hi @RaitoBezarius, I have sent you an invitation to your project in Packet.  Please let us know if you have any questions!

**Comment by RaitoBezarius** [comment]
@taylorwaggoner Thank you!

**Comment by vielmetti** [comment]
This project never deployed any systems, and so it is closing now. If there is a requirement to start up a new project, please open a new issue to reflect current thinking. Thanks!
