### ISSUE TITLE
Request access for Falco

### ISSUE THREAD

**Issue by leodido** [cncf/cluster#123]
# First and Last Name

[Leonardo Di Donato](https://github.com/leodido)
[Lorenzo Fontana](https://github.com/fntlnz)

### Email

leodidonato@gmail.com
lo@linux.com

### Company/Organization

Company: Sysdig
Organization: [Falco](https://github.com/falcosecurity)

### Job Title

Open Source Software Engineers @ Sysdig
Falco Maintainers

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

Falco build and test infrastructure.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Right now, Falco has a build and test infrastructure that is based on TravisCI and some Sysdig internal infrastructure.
This is because we can't build the Falco userspace (eg., command line tools, clients etc.) in TravisCI but we need servers for building the custom kernel modules and eBPF probes on which Falco is based.
Moreover our automation infrastructure for the contributing workflows in based upon PROW, which again is in internal Sysdig infrastructure.
Given this, what we want to do is to have an 100% open build & test infrastructure for Falco on which all the maintainers and contributors can operate.
This can only be achieved by using the CNCF cluster. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

https://github.com/falcosecurity/falco
https://github.com/falcosecurity/falcoctl
https://github.com/falcosecurity/client-go
https://github.com/falcosecurity/falco-exporter
https://github.com/falcosecurity/falcosidekick
etc. etc.

We are the maintainers.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

(1) c2.medium.x86
(4) t1.small.x86

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu 18.04

**Comment by dankohn** [comment]
Sounds great. @taylorwaggoner will set you up early next week.

**Comment by fntlnz** [comment]
Thanks @dankohn !!

**Comment by rajibmitra** [comment]
++1 for this, thanks @dankohn

**Comment by rajibmitra** [comment]
This will help us a lot, thanks for this issue guys @fntlnz  and @leodido  :)

**Comment by leodido** [comment]
Thanks @dankohn !

**Comment by taylorwaggoner** [comment]
Hi all - I've invited lo@linux.com and leodidonato@gmail.com to the Falco project in Packet. Please let me know if there are other emails that need to be added. Thanks!

**Comment by fntlnz** [comment]
Got access, thanks @taylorwaggoner !

**Comment by fntlnz** [comment]
@taylorwaggoner @dankohn We also need to give access to the Falco Project on Packet to Kris Nova (@kris-nova)

Email: kris@nivenly.com
Role: Open Source Advocate
Company: Sysdig
Role at Falco: Maintainer
https://github.com/kris-nova

I will probably ask access for two other maintainers once anyone volunteers in the public  Infrastructure/Release call we have every two weeks. Please be patient :) If you need me to open a new issue for this I will do, just let me know.

**Comment by taylorwaggoner** [comment]
I've added Kris to the project.  Feel free to request in this issue. Thanks!

**Comment by vielmetti** [comment]
All of the infrastructure associated with the Falco project at the CNCF CIL has been turned down as of 04/08/2022.

@leodido is this project complete, or do you anticipate future use of it here?

**Comment by fntlnz** [comment]
@vielmetti  - @leodido and I are not anymore involved in this.
@vielmetti we originally shut that down because Falco had accesso to aws credits and we had our Prow infrastructure there.

@jasondellaluce @leogr @fededp do you know about the CNCF cluster? I'm sure you would fancy to use this for some driver builds, I feel like they would be very efficient there.

**Comment by leogr** [comment]
I wasn't aware of this, so thank you for mentioning me!

@vielmetti we will evaluate this for future use, but I guess we should fill in another issue, correct?

cc @lucaguerra

**Comment by vielmetti** [comment]
@leogr Yes, a new issue would be best - I'll delete the existing project, and you can fill in a new issue to reanimate it with a new request and scope. Thanks!
