### ISSUE TITLE
Request access for CRI-O

### ISSUE THREAD

**Issue by saschagrunert** [cncf/cluster#126]
### First and Last Name

[Mrunal Patel](https://github.com/mrunalp)
[Peter Hunt](https://github.com/haircommander)
[Sascha Grunert](https://github.com/saschagrunert)

### Email

mpatel@redhat.com
pehunt@redhat.com
sgrunert@suse.com

### Company/Organization

Companies: Red Hat, SUSE
Organization: [cri-o](https://github.com/cri-o)

### Job Title

CRI-O Maintainers

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

CRI-O Test Infrastructure

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We're planning to run our bats based integration as well as the Kubernetes end-to-end tests inside the cluster. We have a CircleCI based pipeline which may be converted as well to provide a uniform test approach. We're also looking for a machine for running continuous performance tests.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes: https://github.com/cri-o/cri-o

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

(3) c2.medium.x86
(1) c1.small.x86

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Linux (maybe RHEL, Ubuntu, SLE, Custom Image)

### Any other relevant details we should know about?
None

/cc @haircommander @mrunalp

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
@saschagrunert I've created your project and invited you, Mrunal, and Peter. Thanks!

**Comment by saschagrunert** [comment]
Thank you @taylorwaggoner, I’ve got the invitation. :)
