### ISSUE TITLE
Order Management Solution on Mule (CE) hosted on K8

### ISSUE THREAD

**Issue by hakella2018** [cncf/cluster#127]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Hari Kiran Akella

### Email
hakella2018@gmail.com

### Company/Organization
Keste Software Pvt Limited

### Job Title
Senior Solution Architect

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Develop Integration Solution using Mule Runtime (Community Edition) hosted on Kubernetes 

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
OrderManagement Solution using Mule Runtime (Community Edition) hosted on Kubernetes 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes. 

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
Custom - 3

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
CentOS 7

**Comment by dankohn** [comment]
Sorry, this isn't enough detail to approve. The code you're implementing (i.e, your order management solution) also needs to be open source.
