### ISSUE TITLE
Cluster access for Mesos Elasticsearch

### ISSUE THREAD

**Issue by frankscholten** [cncf/cluster#13]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.
### First Name

Frank
### Last Name

Scholten
### Email

frank.scholten@container-solutions.com
### Company/Organization

Container Solutions
### Job Title

Senior Software Engineer
### Project Title

Mesos Elasticsearch 
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Deploying and running Elasticsearch on a Mesos cluster
### Briefly describe the project

Deploying and running Elasticsearch on a Mesos cluster
### Which members of the CNCF community and/or end-users would benefit from your work?

Anyone using Mesos and/or Elasticsearch
### Is the code that you’re going be running 100% open source? If so, what is the URL or URLs where it is located?

Yes. https://github.com/mesos/elasticsearch
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Yes
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?

Yes. Mesos Elasticsearch can run in Jar mode or in Docker mode by specifying a flag when running the scheduler.
### Are there identified risks which would prevent you from achieving significant results in the project ?

Contributors are busy
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.

No
### Please state your contributions to the open source community and any other relevant initiatives

Committer on Apache Whirr (now in attic). Committer on Apache Mahout (currently inactive). Creator of minimesos: https://github.com/ContainerSolutions/minimesos
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

100
### Duration of request (minimum 24 hours)

One week
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

With a Linux operating system that supports Docker
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

End-to-end testing of deployment, scaling and failover scenarios will help us improve the quality of Mesos Elasticsearch framework and provide information that is useful for other projects.
### Any other relevant details we should know about while preparing the infrastructure?

We will be running on Mesos

**Comment by bprestonlf** [comment]
Approved

**Comment by bprestonlf** [comment]
+1

**Comment by mnarusze** [comment]
On behalf of @cncf/intelclusterteam - is this request valid?

If so, we have two questions:
1. What OS would you prefer - CoreOS (any), Ubuntu 16.04 LTS, CentOS 7, RHEL 7.2, none (bare-metal with PXE boot on native VLAN)?
2. We are planning to prepare the nodes and give you access starting from WW46, is this fine with you?

**Comment by frankscholten** [comment]
@mnarusze:

1. I prefer Ubuntu.
2. Sounds good

**Comment by cncfclusterteam** [comment]
@frankscholten: Do you have any preferences on profiles of nodes and the numbers of them?
Current hardware specification of profiles (compute/storage node) can be found at [README](https://github.com/cncf/cluster/blob/master/README.md)

**Comment by frankscholten** [comment]
@cncfclusterteam I don't have a preference for a particular profile. To test scheduling of the framework with agent attributes it is good to have mix of profiles in the cluster, if possible.

**Comment by cncfclusterteam** [comment]
This issue has been reopened to better show the current status of an associated request - "In progress" should show that the nodes are still used by the requester.

**Comment by frankscholten** [comment]
If possible I would like to extend my usage of the cluster up to the start of the [maintenance window](https://github.com/cncf/cluster/issues/28)

**Comment by cncfclusterteam** [comment]
Hi @frankscholten ,

We hope the time spent with the cluster has been productive. I am writing to inform you that we would like to clean up the nodes for next tenants. Please let us know when we can take them back to the free pool.

Please also notify us here when there are any follow-up articles available.

Thank you,
CNCF Cluster Team

**Comment by frankscholten** [comment]
Yes, you can take them back. Thanks!
