### ISSUE TITLE
apply for trial of CIL

### ISSUE THREAD

**Issue by ttshmily** [cncf/cluster#130]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Chao Fang
### Email
dayi.fc@alibaba-inc.com
### Company/Organization
Alibaba
### Job Title
QA
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Learn Cloud Native
### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Any Linux distribution os is OK

**Comment by taylorwaggoner** [comment]
If you're looking to learn Kubernetes and related technologies, please try out Katacoda. https://www.katacoda.com/courses/kubernetes/playground

thanks!
