### ISSUE TITLE
grpc.io website tooling test

### ISSUE THREAD

**Issue by chalin** [cncf/cluster#132]
### First and Last Name

Patrice Chalin

### Email

pchalin at gmail dot com

### Company/Organization

Linux Foundation (under contract) - reporting manager is @caniszczyk

/cc @taylorwaggoner 

### Job Title

Developer Advocate / Technical Writer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

grpc.io website tooling tests

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

The tools mentioned in the next section are being considered for use as part of the grpc.io (https://github.com/grpc/grpc.io) website build toolchain. But the tools are behaving differently under Travis CI as compared to local macOS. This is a request for a remote login to an Ubuntu box so that we can investigate the differences in behavior under Linux vs. macOS.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes, the tools are 100% open source. URLs:

- https://github.com/chalin/code_excerpt_updater
- https://github.com/chalin/code_excerpter

Tests will likely be conducted by setting up and building the following site, for which the tooling problems were first reported: https://github.com/flutter/website. The site build requires nvm, rvm, and [Dart](https://dart.dev).

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

A single machine. No constraints other than the installed OS (mentioned next).

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu 16.04.6 LTS

### Any other relevant details we should know about?

None that I can think of.

**Comment by taylorwaggoner** [comment]
@chalin I have invited you to Packet. Let me know if you have any questions!

**Comment by chalin** [comment]
Thanks!
