### ISSUE TITLE
Victor Morales Community Infra Lab Request

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/cluster#133]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Victor Morales

### Email
v.morales@samsung.com

### Company/Organization
Samsung

### Job Title
Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Contribute to the CNCF Conformance and Test bed projects

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
My short term goal is contribute on this project improving its deployment instructions and validating the existing ones.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
3 s3.xlarge
1 c3.small

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Ubuntu 18.04 LTS

**Comment by dankohn** [comment]
Approved, thanks. @vielmetti We'd appreciate if you could help.

**Comment by taylorwaggoner** [comment]
@electrocucaracha I have sent you an invitation to join the CNF Sandbox project in Packet, based on Taylor Carpenter's recommendation.  Please let me know if you need anything else!  Thanks!

**Comment by electrocucaracha** [comment]
Thanks @taylorwaggoner , I received the invitation and I have successfully created an account.
