### ISSUE TITLE
Apply  for access to the CNCF Community Infrastructure Lab and machine

### ISSUE THREAD

**Issue by wangaoran** [cncf/cluster#134]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name :
Aoran WANG

### Email
 aoranw@126.com

### Company/Organization 
Beijing University of Post and Telecommunication

### Job Title 
Graduate student 

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Test the CNF environment automatically

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Set up the test environment
Test cases (DHCP\LDAP\ load balancing\ IMS\DNS\VoIP)
Show the test results
Test summary

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, it is 100% open source. https://github.com/cncf/cnf-testbed

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
two, x1.small.x86

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Ubuntu 16.04 and Ubuntu 18.04.

### Any other relevant details we should know about?
No

**Comment by taylorwaggoner** [comment]
@wangaoran are you still interested in pursuing this? Have you been in touch with the folks from the CNF testbed? thanks!
