### ISSUE TITLE
Cluster for GSoC Project [CNCF - Virtual Kubelet]

### ISSUE THREAD

**Issue by virendrasuryavanshi** [cncf/cluster#136]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Virendrasingh Suryavanshi

### Email
vs9812@gmail.com

### Company/Organization
Indian Institute of Technology, Mandi

### Job Title
Student

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Enhance Volcano Scheduler to support Virtual Kubelet

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
When there're not enough resources in one cluster, virtual kubelet is one of the solutions to the scale-out cluster. So in order to enhance the scheduler to balance resources in the cluster, it will be integrated with the virtual kubelet.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, it will be completely open source. It is a part of GSoC program.
https://github.com/cncf/mentoring/tree/master/summerofcode#virtual-kubelet

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
I'm not aware of what kind of machines would I be needed for this project (https://github.com/cncf/mentoring/tree/master/summerofcode#virtual-kubelet
) but I will be needing Kubernetes Cluster with following prerequisites[https://github.com/virtual-kubelet/azure-aci#prerequisites] to test Virtual Kubelet Azure ACI.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
OS - Ubuntu 16.04
Networking - As per the project requirements as mentioned above.

### Any other relevant details we should know about?
https://github.com/virtual-kubelet/virtual-kubelet/issues/812, https://github.com/volcano-sh/volcano/issues/624

**Comment by dankohn** [comment]
Approved, thanks.

**Comment by virendrasuryavanshi** [comment]
Thanks @dankohn for approving. Can you please also let me know how will I get the Credentials of cluster allocated or how should I access the cluster.

**Comment by dankohn** [comment]
@taylorwaggoner will follow up shortly with your credentials.

**Comment by taylorwaggoner** [comment]
@virendrasuryavanshi I have created your project in Packet and have sent you the invitation to join.  Thanks!

**Comment by vielmetti** [comment]
@virendrasuryavanshi The infrastructure for this project from last year is still active - please let us know if you have completed your work.
