### ISSUE TITLE
Application for KubeVirt CNCF mentorship students

### ISSUE THREAD

**Issue by danielBelenky** [cncf/cluster#137]
### First and Last Name
Daniel Belenky

### Email
dbelenky@redhat.com

### Company/Organization
Red Hat

### Job Title
Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
KubeVirt adds a virtualization capabilities to K8s and allows users to manage their containerized and virtualized workloads using a unified and known API.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
KubeVirt is participating in the CommunityBridge summer internship program.
We are mentoring 2 students from the CNCF mentoring program and we need 2 bare-metal machines for our students to be able to develop KubeVirt and use all the existing automation around the development process.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/kubevirt/kubevirt/
I am a maintainer in the KubeVirt project, and a mentor on the CNCF CommunityBridge summer internship program.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
We will need x2 c3-small machines. Our students will turn them off whenever they are not in use.
https://www.packet.com/cloud/servers/c3-small/

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
We will use CentOS 8 or Ubuntu 20.04 LTS. Whatever our students will prefer.

### Any other relevant details we should know about?
In order to run KubeVirt on a machine, a quite powerful bare-metal machine is required because of the nature of KubeVirt: KubeVirt adds virtualization capabilities to K8s. It means that in order to do something interesting with KubeVirt, we will create VMs. KubeVirt has automation in place to create a virtual K8s cluster locally using Docker and QEMU. Because our students are currently using a virtual machine to run a Linux distribution, they end up having 3 layers of virtual machines and it doesn't allow them to have a proper development process.

**Comment by fabiand** [comment]
@caniszczyk can you help?

**Comment by dankohn** [comment]
Approved, thank you. @taylorwaggoner will get you accounts.

**Comment by taylorwaggoner** [comment]
@danielBelenky I've created a Kubevirt project and invited you to it.  Please let us know if there are any other people you'd like to invite to the project.  I'll just need their email addresses.  Thanks!

**Comment by fabiand** [comment]
Taylor, would you mind addin gme as well? Thanks

**Comment by taylorwaggoner** [comment]
Hi @fabiand, I've invited you too!  Thanks!

**Comment by danielBelenky** [comment]
@taylorwaggoner thank you :)
