### ISSUE TITLE
Apply for access to the CNCF CIL computing resources

### ISSUE THREAD

**Issue by ijelliti** [cncf/cluster#138]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Ibrahim Jelliti

### Email
ibrahim.jelliti@gmail.com
sw1115595@swccd.edu

### Company/Organization
Vistaprint

### Job Title
Software engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Kubernetes Dashboard

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
the Kubernetes Dashboard is a General-purpose web UI for Kubernetes clusters. I am working on kind/feature to implement/fix assigned to me. the servers will help to setup the good k8s cluster to develop on it.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, it is 100% open source. https://github.com/kubernetes/dashboard/

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
several machines to setup a kubernetes cluster, kind c3.medium.x86 or c3.small.x86 or is fine.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Ubuntu or CoreOS would be favoured.
### Any other relevant details we should know about?
No, for the moment

**Comment by dankohn** [comment]
Approved, thanks.

**Comment by taylorwaggoner** [comment]
I've created the project and invited sw1115595@swccd.edu and ibrahim.jelliti@gmail.com.  Please let us know if you have any questions!
