### ISSUE TITLE
Apply for access cncf cluster infrastructure lab

### ISSUE THREAD

**Issue by SomboChea** [cncf/cluster#140]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Sambo Chea

### Email
sombochea100@gmail.com

### Company/Organization
CUBETIQ / SETEC Institute

### Job Title
Software Developer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Mini Cloud Infrastructure

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
- Setup and test environment
- Application Deployment and Automation
- Mini Cloud Labs
- Networking
- Share between machines

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, exactly. And I need to improve my knowledge and share them to others.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
- Type: x1.small.x86
- Amount: 4

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Ubuntu 18.04 LTS and Ubuntu 20.04 LTS

### Any other relevant details we should know about?
I want to improve more about cloud infrastructure and share them to others

**Comment by dankohn** [comment]
Sorry, this doesn't provide enough info to approve. You need to include the URL of the open source project you'll be working on and an explanation of what you're trying to do. Please research more and then open a new issue.

**Comment by SomboChea** [comment]
Okay, thank you!
