### ISSUE TITLE
CNCF cluster for running end to end tests

### ISSUE THREAD

**Issue by anishakj** [cncf/cluster#142]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Anisha K J
### Email
anisha.kj@dell.com
### Company/Organization
DELL EMC
### Job Title
Senior Software Engineer
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
pravega-operator
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
The purpose of  the cluster is to run end to end tests of pravega-operator as part of CI. We are using pravega-operator to deploy the pravega cluster. More details can be found on 
https://github.com/pravega/pravega-operator
https://github.com/pravega/pravega
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, https://github.com/pravega/pravega-operator
### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
Kubernetes cluster with 3 nodes.
vCpus: 8
Memory: 32GB
### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
Any linux distribution
### Any other relevant details we should know about?
Will it possible to recreate cluster in our CI job, which will be run on every commit.

**Comment by dankohn** [comment]
This is good for CNCF but it's a big ask so @vielmetti should comment.

**Comment by Ranganaths8** [comment]
@vielmetti  any further updates for us ?

**Comment by vielmetti** [comment]
@Ranganaths8 Thanks for your understanding.

The system that looks like it's a best match for the machine requested is our c1.small

https://www.packet.com/cloud/servers/c1-small/

32G of memory and 4 fast cores. It does not however have as fast a network configuration as some of our systems, limited to 1G instead of 10G. If that is a match for the request, then I'll look for suitable inventory.

**Comment by Ranganaths8** [comment]
@vielmetti  thanks a  lot for response. Yes c1.small should be good for us.

**Comment by taylorwaggoner** [comment]
I've invited anisha.kj@dell.com to the project in Packet.  @Ranganaths8, what is your email address?  Thanks!

**Comment by Ranganaths8** [comment]
my id is ranganath_s@dell.com. thank you

**Comment by taylorwaggoner** [comment]
Great thanks! I've sent you the invitation as well @Ranganaths8.

**Comment by anishakj** [comment]
How can  I create a storage class in CNCF cluster after attaching a storage volume?

**Comment by dankohn** [comment]
You want to ask Packet support.

**Comment by vielmetti** [comment]
@anishakj please review https://github.com/packethost/csi-packet - a Kubernetes CSI driver for Packet block storage.

**Comment by vielmetti** [comment]
@anishakj @Ranganaths8 -

I've sent you both email regarding the end of life of the Equinix Metal block storage service. This will impact your pravega-operator testing efforts. I'm happy to provide any assistance here or via email.

**Comment by anishakj** [comment]
@vielmetti I have deleted all the storage volumes. Will the server creation will be impacted after  Equinix Metal block storage service is deprecated
