### ISSUE TITLE
Cluster access for Freshealth

### ISSUE THREAD

**Issue by lk153** [cncf/cluster#144]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Viet Nguyen
### Email
vietnguyen148@gmail.com
### Company/Organization
Tiki
### Job Title
Technical Architect
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Fresh Health. This site is built for mom community sharing and pedagogy for their childrens
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
I will built ML machine to categorize children character for suitable pedagogy. Beside on that I build streaming microsite for cartoon and sharing video
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
This project is built on Wordpress and use fwplayer for streaming education and cartoon videos. I host this site on Google Cloud VM, it nearly expired for free-use. http://freshealth.cf/ https://github.com/lk153/healthcare
### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
c1.small.x86
### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
With OS, if Ubuntu (18.04 LTS)
### Any other relevant details we should know about?
My daughter is more 2 years old. She is really naughty and learning everything so fast. Many things my wife and I understand vital point that we need to learn with her, not easy. So that 's my main purpose I try all my best to build up this site

**Comment by dankohn** [comment]
Thanks for reaching out, but unfortunately your application is not what these servers are intended for. I would instead recommend looking for free hosting at wordpress.com or similar.
