### ISSUE TITLE
Apply to Use the On-Demand Infrastructure

### ISSUE THREAD

**Issue by chengtong321** [cncf/cluster#145]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Cheng Tong
### Email
chengtong@chinamobile.com
### Company/Organization
China Mobile
### Job Title
Implement CNF-conformance and CNF-testbed
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
through implementing CNF-conformance and CNF-testbed in order to verify if it works well, and verify the difference between cnf and vnf
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
in order to verify the difference between cnf and vnf , and verify if CNF-conformance and CNF-testbed can be used test tools in our company.
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
yes,  the code that i am going to run is 100% open source. 
https://github.com/cncf/cnf-testbed/tree/master/docs
https://github.com/cncf/k8s-conformance
https://github.com/cncf/cnf-conformance
i will implement these project in the evironment
### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?
Intel NIC 5 hosts ( i will deploy 1 master and 3 worker node,1 packet generator )
export MASTER_NODE_TYPE=t1.small
#export WORKER_NODE_TYPE=n2.xlarge.x86 # Intel NIC
export NODE_OS=ubuntu_18_04
export PACKET_FACILITY=ewr1
ETCD_VERSION=v3.2.8
CNI_VERSION=v0.6.0
K8S_RELEASE=v1.12.2
### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?
ubuntu_18_04    Intel NIC (VLANs)
### Any other relevant details we should know about?
no

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
@chengtong321 I have sent you an invitation to join our CNF Sandbox project in Packet.  Thanks!
