### ISSUE TITLE
Add ARM machines to Longhorn CNCF infra

### ISSUE THREAD

**Issue by yasker** [cncf/cluster#146]
### First and Last Name

Sheng Yang

### Email

sheng@yasker.org

### Company/Organization

Rancher Labs

### Job Title

Software Architect and Engineering Manager

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

Add ARM machines to Longhorn CNCF infra

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We're planning for the ARM support for the Longhorn, so we need some ARM machines to run the building and testing.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes. The codes are located at https://github.com/longhorn/ . Longhorn is a CNCF sandbox project. I am a maintainer of Longhorn.

### What kind of machines and how many do you expect to use (see: https://www.packet.com/bare-metal/)?

c1.large.arm or c2.large.arm. We only need one additional ARM node first. We might need to expand to 3 or 4 nodes later.

### What OS and networking are you planning to use (see: https://support.packet.com/kb/articles/supported-operating-systems)?

Ubuntu 18.04 

### Any other relevant details we should know about?

No.

**Comment by taylorwaggoner** [comment]
@vielmetti this is for an existing Longhorn project in our account

**Comment by yasker** [comment]
Ping?

**Comment by vielmetti** [comment]
Looks good to me. We have more c1.large.arm inventory at the moment so that's a better one for initial testing @taylorwaggoner @yasker

**Comment by dankohn** [comment]
+1

**Comment by yasker** [comment]
Thanks @dankohn . @vielmetti Can you help to add permission to provision c1.large.arm to our Longhorn account?

**Comment by yasker** [comment]
Ping?

**Comment by vielmetti** [comment]
The access issue has been resolved
