### ISSUE TITLE
Cluster Access for Packet Bare Metal Automation

### ISSUE THREAD

**Issue by zsmith928** [cncf/cluster#15]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Developer automation for fundamental, "can be anywhere" infrastructure is a critical component of cloud native computing.  To date, most cloud native computing relies heavily on primitives of multi-tenant public clouds or virtualization based private clouds.  Packet is eager to refine its software stack for use in on premise environments to power cloud native applications regardless of location.   At Packet, we operate a public cloud that is used by many CNCF members to test, build or operate cloud native stacks without virtualization or overlay networking as a requirement.   We envision that much of this could happen on the CNCF cluster.
 
### Briefly describe the project
We would like to install and operate a Packet private rack in the CNCF cluster.  This would include both server and switch automation.
 
### Do you intend to measure specific metrics during the work? Please describe briefly
We are interested in achieving baseline capabilities, including provisioning, deprovisioning, healthchecking and metering of physical compute instances.  We would use our own Docker-based canary testing for simulating thousands of provisions and measure the success rates.
 
### Which members of the CNCF community and/or end-users would benefit from your work?
Nearly all members could leverage this.  However, members known to be comfortable with the Packet API and meta data service include CoreOS/Quay, Mesosphere DC/OS, Rancher, Apprenda, ContainerSolutions, Deis, Diamanti, Nginx, Portworx, StackPoint, Mirantis, Tigera, and Virtuozzo.

### Is the code that you’re going be running 100% open source? If so, what is the URL or URLs where it is located?

No, it is not currently open source.  Our goal would be to evaluate the usefulness of open sourcing any of our core automation.  

### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

We agree in publishing in our results.

### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?

Yes, our stack currently runs 100% in Docker (on Rancher).
 
### Are there identified risks which would prevent you from achieving significant results in the project ?

Yes, the network architecture and access to control plane, IP space, routing level details, etc are unclear and could affect if this would be successful or not.
 
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.

No.
 
### Please state your contributions to the open source community and any other relevant initiatives

We are large supporters of the Cloud Native and Open Source communities in general, regularly providing 100-1000 bare metal compute nodes to cloud native projects for load and scale testing, build operations and compatibility work.
 
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

100 nodes, or whatever is in a logical switch group.
 
### Duration of request (minimum 24 hours, maximum 2 weeks)

2 weeks would probably be insufficient for our use given past experiences with other infrastructure environments.  Our goal would be to a) complete Packet private rack ingestions and b) offer use of the underlying compute resources to CNCF projects via the Packet API and metadata service (using a special CNCF facility code).
 
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

No operating system.  We would need full BMC access, bios level control (particularly if we were to test trusted computing), and privileged switch control using netconf style access.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Our goal is to showcase that cloud native computing can leverage fundamental bare metal compute (literally nothing else),  be performed in any location and offer the same convenient DevOps interfaces that users leverage today (e.g. terraform, ansible, native cloud-init, elastic addressing, etc).

### Any other relevant details we should know about while preparing the infrastructure?

**Comment by cncfclusterteam** [comment]
@zsmith928 Good morning.  Unfortunately, we don't provide or allow access to the physical network infrastructure.  That is out of scope.

**Comment by zsmith928** [comment]
hi @cncfclusterteam, I can see your point around open source although it would be good to discuss.  Also, just for my own edification, is the @cncfclusterteam part of the board of CNCF and what is the process to have the committee fully evaluate our request?

To be clear, everything we would install in the CNCF environment would be Open Source, as we are just doing bare metal CoreOS, Ubuntu, etc installs in the CNCF environment.  Our control plane could (and may have to) live outside of the environment.  The control plane is not Open Source.  Would this allow us to meet the Open Source requirement for the cluster?

As for the access to network, I suspect that given members like Tigera/Calico, Cilium, etc, and the relatively immature state of physical network automation in the cloud native ecosystem, it would benefit the community to reconsider restrictions on the physical switch plane access.  I'd be open to discussing how we could make this work, but would need to understand more details of the cluster environment.

**Comment by cncfclusterteam** [comment]
@zsmith928 Given that this a multi-tenant cluster, we rely on the physical "underlay" to deliver a decoupled and multi-tenant experience.  The underlay forms the IP ECMP fabric for all tenants, along with carving up the cluster boundaries via switch based VXLAN head end replication.  Tenants will typically run (or not) their own overlay, but we make no assumptions that they will.  Also, part of delivering this service requires that our automation touches and manages the physical network infrastructure.  You have the option to run virtual machine instances of switch network OS's (Arista vEOS, Cumulus), if the goal is to run automation functionality tests, which are very vendor specific.  Our ISP links also terminate into the spine fabric, which are all the reasons the physical network is out of scope.  In order to provide bare-metal network switch access, we would need to make significant changes to the current design and hardware.  We can work with you to add some functionality to the underlay (DCB/ECN/QoS as an example), but we cannot provide access.

Additionally, per the CNCF cluster usage guidelines:

- The cluster is used for the purposes of open source projects only. CNCF related projects and projects demonstrating intent of upstreaming code will be given priority

- At this point, we do not expect any physical changes to be requested to the cluster. Hence, there is no expectation that there needs to be any on-site presence

 Thank you

**Comment by zsmith928** [comment]
This is very useful. Thanks for the context here!

**Comment by cncfclusterteam** [comment]
Per our discussion with Zachary, we can't accommodate this type of use-case in the CNCF cluster.  Thank you.
