### ISSUE TITLE
Cluster for experiments and tests difhub-codegen

### ISSUE THREAD

**Issue by v-bilous** [cncf/cluster#151]
### First and Last Name
Vova Bilous

### Email
vova.bilous@hotmail.com

### Company/Organization
bilous.pro

### Job Title
Principal Software Engineer

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Metadata Driven cloud-native microservice system built using the code generator

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
The idea of the project is to Generate a RESTful microservice system and infrastructure as a code for it using a code generator driven by metadata, right after the code generation – deploy the entire microservice system to the cluster. No code at all at the initial step, the entire project can be generated using the tool and metadata for it, this gonna be a great open-source instrument for the startups and digital transformation. I want to organize continuous integration and deployment of generated (test-only) microservice systems on the CNCF. The code generator has a lot of options that required different clusters with a different configuration to be deployed. I wanna move from Azure Pipelines to CNCF as well. Also, I wanna try Spinnaker to experiment with CD for the generated project.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes. It is open-source, the code is located at https://github.com/v-bilous/difhub-codegen . I'm the owner of this project. 

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
Well, the good option for me is:
- three c3.small.x86 for a 3-node Kubernetes cluster

### What operating system and networking are you planning to use?
Ubuntu 20.04

### Any other relevant details we should know about?
No, but I would like to say thank you for all the support :)

**Comment by caniszczyk** [comment]
a cool idea but too small of a project for us to support

**Comment by v-bilous** [comment]
Hi @caniszczyk , thanks for the reply. Any chance to get minimal bare metal to setup simple k8s cluster for the startup?
