### ISSUE TITLE
Kubeflow Testing Infrastructure

### ISSUE THREAD

**Issue by mameshini** [cncf/cluster#152]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Igor Mameshin

### Email
igor@agilestacks.com

### Company/Organization
Kubeflow On-prem SIG
Agile Stacks

### Job Title
Tech lead of Kubeflow On-prem SIG

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Kubeflow test infra

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Kubeflow is an open source Kubernetes-native Machine Learning platform.  It is designed to enable end-to-end machine learning workflows - for example, data processing with Python, model training with TensorFlow, and model serving with KFServing.  The goal of this project is to implement daily E2E tests of Kubeflow release on Equinix Metal to test on-prem deployment scripts for Kubeflow.  

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes the code is 100% open source
I am one of the project maintainers/tech leads, and applying on behalf of Kubeflow on-prem SIG.
https://github.com/kubeflow/
https://github.com/kubeflow/testing

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
2 worker nodes of kind c3.small.x86 if using a shared CI/CD environment
1 master and 3 workers of of kind c3.small.x86 if using dedicated Kubernetes cluster

### What operating system and networking are you planning to use?
Ubuntu 18.04

### Any other relevant details we should know about?
As discussed with @vielmetti, in phase 2 we can add support for testing on GPUs.

**Comment by vielmetti** [comment]
cc @caniszczyk @idvoretskyi @pritianka @taylorwaggoner 

I talked to @mameshini last week and have plans to join in the weekly sig-onprem call for Kubeflow on Friday. I don't see any problems with providing the equipment, and it may make sense to engage the CNCF CI team since that project feels like ti's a direct match for these requirements.

👍

**Comment by taylorwaggoner** [comment]
@caniszczyk can we please get your +1? thanks!

**Comment by caniszczyk** [comment]
+1

**Comment by idvoretskyi** [comment]
Awesome, I'll follow up on this.

**Comment by vielmetti** [comment]
Attn @castrojo

**Comment by fkautz** [comment]
Non binding +1

Kubeflow is critical infrastructure for many AI/ML pipelines. Given the nature of what kubeflow does, a proper community owned CI/CD will be extremely helpful in ensuring the long term health of the project.

**Comment by idvoretskyi** [comment]
@mameshini invite sent!

**Comment by mameshini** [comment]
Thank you, I received the invite and created an account.  We are now going to discuss how to create K8S cluster with Istio.

**Comment by catblade** [comment]
@caniszczyk  Request for myself and @jtfogarty to be added.  We are part of kubeflow on-prem and would like to work with @mameshini  to get this running.

**Comment by idvoretskyi** [comment]
@catblade I think @mameshini should be able to add you directly.

If not, let me know.

**Comment by catblade** [comment]
@idvoretskyi  He was not, and did try.

**Comment by idvoretskyi** [comment]
@mameshini can you please approve this?

**Comment by mameshini** [comment]
I approve adding @jtfogarty and @catblade as additional users.  I could not do via self-service console.

**Comment by idvoretskyi** [comment]
@jtfogarty and @catblade, please let me know your email addresses, and I'll invite you.

**Comment by jtfogarty** [comment]
@idvoretskyi did you get my slack message?

**Comment by idvoretskyi** [comment]
@jtfogarty I don't think so - on which Slack? Feel free to DM me on CNCF Slack or email me directly :)

**Comment by jtfogarty** [comment]
ah, I DMed you on kubeflow Slack

**Comment by tbaums** [comment]
hey @idvoretskyi - just pinged you on slack. I'm co-chair of KF sig-onprem. Can I get access to our testing resources pls? I'll dm you on slack with my email.

**Comment by DavidSpek** [comment]
Hi @idvoretskyi just like @tbaums I just pinged you on Slack with my email with regards to access to Equinix Metal.

**Comment by idvoretskyi** [comment]
Invite sent!

**Comment by idvoretskyi** [comment]
Closing this one, feel free to email me directly if anyone else should be added.
