### ISSUE TITLE
Add Arch Linux team members to packet.net CNCF project 

### ISSUE THREAD

**Issue by svenstaro** [cncf/cluster#158]
I'd like to request the addition of @jelly (`jelle@vdvaa.nl`) and @freswa (`frederik.schwan@linux.com`) to the CNCF Arch Linux packet.net project. I was [earlier added to this project myself here](https://github.com/cncf/cluster/issues/102).

**Comment by jelly** [comment]
Confirming that the above is correct.

**Comment by freswa** [comment]
Confirming that the above is correct.

**Comment by taylorwaggoner** [comment]
@svenstaro @jelly I've added both, thanks!

**Comment by jelly** [comment]
I am very sorry, I have made a typo in my email address it should be jelle@vdwaa.nl
