### ISSUE TITLE
Formalize CNCF CIL approval process between CNCF and Equinix Metal; improve project reporting

### ISSUE THREAD

**Issue by vielmetti** [cncf/cluster#159]
@idvoretskyi - I've gone through a bunch of process improvement work for the @WorksOnArm project and have some suggestions for how we can learn from this for the CNCF CIL effort which is roughly the same procedures. We have some workflows and boilerplate text and an Excel worksheet to analyze the usage, all of which I think would be worthwhile learning from and/or copying wholesale.

I'll have something specific to share on this in about a week (by 2020-12-09).

**Comment by idvoretskyi** [comment]
Awesome, thanks!

FYI @caniszczyk @pritianka @taylorwaggoner

**Comment by vielmetti** [comment]
@taylorwaggoner and I have a meeting scheduled for 2020-12-10 (Thursday) to review planning for 2021 and to look at reporting and accounting for usage analysis.

**Comment by idvoretskyi** [comment]
@taylorwaggoner @vielmetti any further work is required on this?

**Comment by vielmetti** [comment]
I think we're good for now, closing.
