### ISSUE TITLE
Locus Finder Project

### ISSUE THREAD

**Issue by scdatascience** [cncf/cluster#162]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

First and Last Name Fernando Cerutti

Email fernando.cerutti@scdatascience.com.br

Company/Organization SC Data

Job Title CIO

Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
We are starting  an IoT project with agrobusiness focus. This project may be end-to-end cloud native architecture.

Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
To program front-end middleware and back-end as well storage data from IoT sensors and to use adequate open source tools to architecture governance 

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

https://github.com/scdatascience/Locus_fider. I´m the overall project manager

What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)? 2 c3small×86

What operating system and networking are you planning to use? Debian 10 network 2 x 10Gbps Bonded

Any other relevant details we should know about? We are in very initial fase and we thinks that´s  ideal to found all CNCF tools which will fit in our project. We thanks a lot and appreciate from far time ago the Open community

**Comment by idvoretskyi** [comment]
cc @vielmetti FYI

**Comment by vielmetti** [comment]
I can't find any code on https://github.com/scdatascience?tab=repositories - and it would seem to make sense for this project to be further along and establish something of a track record before getting these resources.

**Comment by caniszczyk** [comment]
ya -1 to this
