### ISSUE TITLE
KEDA infra request: ARM processor for CI/CD build of ARM release

### ISSUE THREAD

**Issue by jeffhollan** [cncf/cluster#163]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Jeff Hollan

### Email
jeff.hollan@microsoft.com

### Company/Organization
Microsoft

### Job Title
Principal Product Manager

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
KEDA - we have requests to provide an ARM build for our operator, but in order to do so we need to have an automated CI/CD process that can deal with ARM bits.  Need some hardware to execute that process.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
We have requests to provide an ARM build for our operator, but in order to do so we need to have an automated CI/CD process that can deal with ARM bits.  Need some hardware to execute that process.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes - https://github.com/kedacore/keda 

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
1 instance of c1.large.arm should be fine

### What operating system and networking are you planning to use?
Linux, most distros should be fine

### Any other relevant details we should know about?
Planning to install the GitHub Remote Runner on it to use within our GH Actions CI/CD process

**Comment by caniszczyk** [comment]
+1

**Comment by taylorwaggoner** [comment]
@jeffhollan I've created the KETA project and invited you to it.  Please let us know if there are other people we should invite, just need their email addresses. thanks!

**Comment by tomkerkhove** [comment]
Can you invite @zroubalik, @ahmelsayed & @tomkerkhove as well please?
