### ISSUE TITLE
admin privilege for medyagh for equinix's project "minikube integration testing"

### ISSUE THREAD

**Issue by medyagh** [cncf/cluster#164]
Hello, I am the TL for minikube and one of the maintainers, per conversation with Charlie Lane, I would like to ask for admin privililge to add/remove users to "minikube integration testing"

**Comment by caniszczyk** [comment]
@idvoretskyi can you verify if this is true and take care of it

**Comment by idvoretskyi** [comment]
@medyagh has there been a public issue/record for this that you can reference to?
