### ISSUE TITLE
Requesting a  C3 Small x86 server for curiefense CI

### ISSUE THREAD

**Issue by flaper87** [cncf/cluster#166]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Flavio Percoco

### Email

flavio@reblaze.com

### Company/Organization

Reblaze

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

E2E CI for Curiefense

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

The goal is to have e2e tests running on every PR to guarantee the stability of the project, and provide a better testing platform to the curiefense contributors. Curiefense currently uses Github Actions as the CI infrastructure but, unfortunately, the resources available in the default Github Action workers are not enough to run the e2e test suite which requires running several services, as well as smoke tests.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Project: https://github.com/curiefense/curiefense/

I actively contribute to the project

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

C3 Small x86 should be enough to get us going

### What operating system and networking are you planning to use?

The current idea is to run a Github Action agent and use this node as a worker node dedicated *only* to the e2e test suite. Ubuntu / Fedora with default network configurations should be enough.

### Any other relevant details we should know about?

Curiefense is a new project in the CNCF, this is the first request of this kind. There may be better ways to achieve our goal so, we are more than open to suggestions. Requesting a cluster was recommended to us.

**Comment by caniszczyk** [comment]
+1

**Comment by idvoretskyi** [comment]
@flaper87 Intive sent a few days ago, sorry for the late notice :)

**Comment by flaper87** [comment]
> @flaper87 Intive sent a few days ago, sorry for the late notice :)

I've accepted the invite. Should I go ahead and create the node? or will you do that?

**Comment by idvoretskyi** [comment]
@flaper87 go ahead!

**Comment by idvoretskyi** [comment]
@flaper87 closing this for now, let me know if anything else is needed.
