### ISSUE TITLE
ARM based build and test environment for Dex

### ISSUE THREAD

**Issue by sagikazarmark** [cncf/cluster#170]
### First and Last Name

Márk Sági-Kazár

### Email

- mark.sagikazar@gmail.com (preferred)
- marksk@cisco.com

### Company/Organization

Cisco (ET&I)

### Job Title

Engineering Technical Lead

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

[Dex](https://dexidp.io/) ARM CI environment

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We would like to extend the CI (GitHub Actions) environment of [Dex](https://dexidp.io/) to include ARM-based hardware to ensure it works properly on ARM.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

[Dex](https://dexidp.io/) is 100% open source:

- https://dexidp.io/
- https://github.com/dexidp/dex

I'm a maintainer of the project.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

Either one of the ARM-based servers listed here:
https://metal.equinix.com/developers/docs/servers/#arm-servers

### What operating system and networking are you planning to use?

Ubuntu 20.x (whichever is supported by GitHub Actions)

### Any other relevant details we should know about?

Dex added experimental ARM support a while ago (container images are built using qemu), but it keeps breaking from time to time and qemu is slow which is why we would like to run tests directly on ARM.

**Comment by caniszczyk** [comment]
+1

**Comment by caniszczyk** [comment]
cc: @idvoretskyi

**Comment by idvoretskyi** [comment]
@sagikazarmark on it!

**Comment by sagikazarmark** [comment]
@idvoretskyi Awesome, thanks!

**Comment by idvoretskyi** [comment]
@sagikazarmark invite sent

**Comment by sagikazarmark** [comment]
Thanks, received!
