### ISSUE TITLE
Request for Whole Android Community

### ISSUE THREAD

**Issue by ElytrA8** [cncf/cluster#171]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Shéikh Adnan

### Email
manofuranium@gmail.com

### Company/Organization
Android Community

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
android development ci ( i.e roms , kernels etc )

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

I actually planned this servers for android ( open source only ) rom developers . Nowadays a more part of a community don't have servers so this waste thier skills of being active and doing work on time. It's opensource so we actually don't earn from that. This servers will be used as Jenkins for all over android community developers. I will manually verify everyone who will request are they really good at kernel / rom stuff.

We will have
1:- A Jenkins Ci Server
2:- A website to request for applying and downloading

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes. We gotta allow only 100 % opensource work 

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
Well it's hard to say coz it gonna be really hard coz its very big project. 
(Edit) Maximum Specs

### What operating system and networking are you planning to use?

Ubuntu GNU/LINUX Servers 20.04
Jenkins CI

### Any other relevant details we should know about?

Why I am doing this ?
My main motive is to give developers servers need to develop roms .

Why should you approve this project ?
We will try to advertise equinix server in every possible .
This will be the biggest android projects you ever approved .
(Artifacts) Downloads will be only on the website nowhere else.
It's hard to say but it's for a whole community where thousands of people wait for thiers phones custom firmwares. 

I humbly request give us servers we will co-ordinate with everything.

Sorry For Bad English.

One Last thing
We will make a administration team.
Which will verify every single developer

**Comment by sushmit1** [comment]
Sir no words

**Comment by TheCloverly** [comment]
@ElytrA8 Thanks for your contribution,We will stand with you :)

**Comment by brucetech627** [comment]
😃😃

**Comment by flaahokiller** [comment]
😀

**Comment by JamieHoSzeYui** [comment]
Good Job sir. Waiting for your good news!

**Comment by sasukeuchiha-clan** [comment]
@ElytrA8 doing great work sir for Android Community.😉

**Comment by Maitreya29** [comment]
Doing epic work as usual, gg.
Looking forward to your development endeavours

**Comment by sarthakroy2002** [comment]
Great job

**Comment by asjanib** [comment]
Awesome 😊☺️

**Comment by durasame** [comment]
nice

**Comment by Apon77** [comment]
Hope for the best 🙂

**Comment by manjotsidhu** [comment]
👍

**Comment by SuperCosmicBeing** [comment]
If we get it, it'll help us a lot :)
Hope that we do get it...

**Comment by caniszczyk** [comment]
Hey all, we are prioritizing cloud native open source projects, there's not enough detail here on what "android community" means - I'd recommend you look at applying for open source credits at AWS:

https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

**Comment by ElytrA8** [comment]
I meant android firmware developers from "android community"

**Comment by ElytrA8** [comment]
i.e android open source project "aosp"
Lineage os "los"

**Comment by ItsVixano** [comment]
> Hey all, we are prioritizing cloud native open source projects, there's not enough detail here on what "android community" means - I'd recommend you look at applying for open source credits at AWS:
> 
> https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

AOSP = Andoid Open Source Project "https://source.android.com/"
Is legit an OSS project 

What @ElytrA8 means with 'Android Community', is a group of folks that enjoys contributing in some AOSP forks, or even contributing porting a device tree that will be used for 

- Compiling AOSP for some specific devices
- Testing the trees and fixing problen over it 

Sadly compiling AOSP, or his forks, needs at least a powerful machine, and isn't a thing that everyone can permit

That why he "@ElytraA8" opened this issue
