### ISSUE TITLE
Request Access for a Cluster

### ISSUE THREAD

**Issue by manjotsidhu** [cncf/cluster#172]
### First and Last Name
[Manjot Sidhu](http://manjotsidhu.com/)

### Email
manjot.gni@gmail.com
pitchblackrecovery@gmail.com

### Company/Organization
[PitchBlack Recovery Project](http://pitchblackrecovery.com/)

### Job Title
Undergraduate Engineering Student
Co-founder of PitchBlack Recovery Project

### Project Title
We at PitchBlack Recovery Project aka PBRP provides Android Recovery for [40+ Android Devices](https://github.com/PitchBlackRecoveryProject/vendor_utils/blob/pb/pb_devices.json) and has a community of 100K+ Users currently dependent on it. We have to keep our Open Source Project up-to-date with the newer Android version changes and vendor specific utilities for a complete end-to-end recovery of the device. We used to come as Open Source Project of the week commonly at [SourceForge](https://sourceforge.net/projects/pbrp) since we use SourceForge for deploying releases.

### Briefly describe the project
At PBRP, we the Core Developers have to do continuous integration, testing and deployment of the builds since the recovery has to be tested on physical devices. We also have Device Maintainers and Testers (from the community) that also collaborate and help us in maintaining of our builds. Our source being dependent on Android sources consumes a lot of time in just build and deployment. Android Sources needs to be again compiled and deployed for each individual Android Device because of the [Android Build System](https://elinux.org/Android_Build_System). Our build systems being a normal low-end laptops take around 40 minutes for just 1 build. We have tested using Circle CI, [GitHub Actions](https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp/actions/runs/718154799) and that takes approximately 1 hour to complete our CI & CD process.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, our source code is 100% Open Source including build, deploy scripts hosted at [GitHub](https://github.com/PitchBlackRecoveryProject), [SourceForge](https://sourceforge.net/projects/pbrp), [Website](http://pitchblackrecovery.com/)

Our whole build process starts with fetching the dependent packages at https://github.com/PitchBlackRecoveryProject/manifest_pb
Our build and deployment scripts for local/CI/CDs are located at https://github.com/PitchBlackRecoveryProject/vendor_utils

### What kind of machines and how many do you expect to use ?
One, c3.small would be enough according to our needs.

### What operating system and networking are you planning to use?
Ubuntu 20.04 LTS

### Any other relevant details we should know about?
We are happy to support Cloud Native Computing Foundation (CNCF) in any possible way.

**Comment by caniszczyk** [comment]
-1, not cloud native related
