### ISSUE TITLE
{registry,artefact}.k8s.io Project (CNCF/K8s Infra WG)

### ISSUE THREAD

**Issue by hh** [cncf/cluster#173]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Hippie Hacker

### Email

hh@ii.coop

### Company/Organization

CNCF on behalf of the K8s-Infra-WG

### Job Title

Contractor to CNCF

### Project

Redistribution of cost for hosting {registry,artifacts}.k8s.io

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Currently most of the cost of distributing Kubernetes artefacts and images rests with Google. We'd like to develop Cloud Native solutions that are vendor dependent and set some open source best practices for the rest of the CNCF community.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

It will likely live in a few places:
- https://github.com/kubernetes/k8s.io (k8s-infra-wg infra)
- https://github.com/cncf-infra (infra beyond kubernetes may end up here)
- https://github.com/goharbor/harbor-operator (beta release will be developed within this project)
- Possible others as we identify other solutions to support a k8s artefact+image distribution solution

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

3-6 c3.smalls initially

### What operating system and networking are you planning to use?

Ubuntu and the default as a start

### Any other relevant details we should know about?

We may end up running these in multiple zones, or explore using BPG to do split-horizon any cast DNS.

**Comment by caniszczyk** [comment]
+1

**Comment by idvoretskyi** [comment]
This is done.
