### ISSUE TITLE
Cluster access for Firmament/Poseidon

### ISSUE THREAD

**Issue by ms705** [cncf/cluster#18]
### First Name

Malte
### Last Name

Schwarzkopf
### Email

malte@camsas.org
### Company/Organization

Cambridge Systems at Scale (CamSaS) / Firmament.io / MIT CSAIL
### Job Title

Researcher
### Project Title

Firmament and Poseidon scale-up evaluation
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
- Better placement decisions in cluster schedulers; e.g., to avoid “noisy neighbors” and cross-workload interference.
- Scalability of cluster scheduling using min-cost flow optimization (as in [Quincy](http://dl.acm.org/citation.cfm?id=1629601) and [Firmament](http://www.firmament.io)) on a real-world cluster.
### Briefly describe the project

In our research, we developed the Firmament cluster scheduler, on which we have an upcoming paper appearing in [OSDI 2016](https://www.usenix.org/conference/osdi16). In this paper, we evaluate the scalability of Firmament’s min-cost flow optimization-based scheduling by replaying workload traces, and in a small-scale test-bed deployment. We would like to perform a real-world scale-up evaluation to further validate our results, and to explore the benefit of Firmament’s scheduling policies for real workloads running on a larger-scale clusters than we currently have access to.

Poseidon (https://github.com/camsas/poseidon) is an integration of Firmament’s scheduling logic with Kubernetes: we have developed Poseidon as a drop-in replacement for the default Kubernetes scheduler (kube-scheduler). We would like to deploy Poseidon at scale and measure its performance in order to compare it against our own stand-alone research cluster manager and ensure that there are no undue performance penalties in either implementation.
### Do you intend to measure specific metrics during the work? Please describe briefly

Yes, we hope to measure the following:
1. Scheduling latency / placement delay, which quantifies the time between workload (pod/container) submission and the execution on a node.
2. Placement quality / performance degradation over ideal, which measures the runtime on shared infrastructure compared to the ideal runtime on an otherwise idle machine or cluster.
3. Packing efficiency, which measures the quality of a scheduling policy by shrinking the cluster until the workload no longer fits (see [source](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43103.pdf)).
### Which members of the CNCF community and/or end-users would benefit from your work?

The Kubernetes project, via the Poseidon scheduler, which we are making available for anyone to use. Poseidon is API-compatible with `kube-scheduler` and can be deployed on existing Kubernetes clusters.
### Is the code that you’re going be running 100% open source? If so, what is the URL or URLs where it is located?

Yes, see https://github.com/camsas/firmament and https://github.com/camsas/poseidon. 
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Yes, we open-source all of our work on Firmament and Poseidon under the Apache 2.0 license. Our experimental results will be published as part of a peer-reviewed paper, a blog post, or a technical report.
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?

Yes, Poseidon schedules containers (via Kubernetes). Firmament’s standalone cluster manager has alpha support for container execution; we hope to improve this in the near future.
### Are there identified risks which would prevent you from achieving significant results in the project ?

The only main risk is that the timing of cluster access may not work out well, e.g., coinciding with a major deadline, teaching, or a conference. We are a small team of two researchers, so our cycles are limited. We may also discover previously unknown scalability bottlenecks as a result of the testing, although we would consider this a success rather than a risk.
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.

No.
### Please state your contributions to the open source community and any other relevant initiatives

Our research software, data sets, experimental infrastructure, and scripts are open-source (https://github.com/camsas), and we contribute to the Kubernetes SIG-scheduling interest group.
If we use the CNCF cluster for a scale-up experiment mentioned in a research publication or blog post, we will acknowledge the support by the CNCF as we would acknowledge any other industrial support of our research.
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

100, with possibility to increase to 500.
### Duration of request (minimum 24 hours, maximum 2 weeks)

1 week.
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

With OS, if Ubuntu (14.04 LTS or 16.04 LTS) is available.
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

It will provide better container scheduling, potentially tighter packing of workloads with reduced interference, and validate the scalability of the min-cost flow optimization scheduling approach in a real-world environment.
### Any other relevant details we should know about while preparing the infrastructure?

Some of our experiments involve running applications that generate a high network load (i.e., saturating a 10 Gbit/s link).

**Comment by bprestonlf** [comment]
Approved

**Comment by bprestonlf** [comment]
+1

**Comment by mnarusze** [comment]
On behalf of @cncf/intelclusterteam - is this request valid?

If so, we have two questions:
1. Unfortunately, the maximum amount of nodes available at the moment is ~400, we cannot provide the amount you requested for part 2. I'll make sure the maximum values are updated soon.
2. Assuming 400 is OK for you,

**Comment by mnarusze** [comment]
On behalf of @cncf/intelclusterteam - is this request valid?

If so, we have two questions:
1. Unfortunately, the maximum amount of nodes available at the moment is ~400 and it probably won't change a lot (i.e. it won't reach 500) until expansion which should take place in Q1'17. Are 400 nodes enough for the second part of your tests?
2. I understand this request as follows - you would need 1 week with 100 nodes and then another week with 400 nodes. In total - two weeks of cluster usage, week after week. Is that correct?

**Comment by ms705** [comment]
[ adding @ICGog, who is doing Firmament experimentation and drives Poseidon development ]

Apologies for the late response -- other projects intervened! The request is still valid (albeit not urgent), so would it be okay to reopen it?

As for the questions:

 1. 400 nodes are sufficient for our scale-up tests.
 2. Yes, that would be ideal, but we can be flexible.

**Comment by cncfclusterteam** [comment]
Hi @ms705 , no problem at all - we just thought that it's no longer valid.

We will put this request in the queue after the maintenance window, once we know how many nodes are available afterwards then we will update you on the exact dates.

**Comment by cncfclusterteam** [comment]
Hi @ms705, we are wondering if you would like to start working after Red Hat leaves the cluster at the end of March or would you rather have the nodes allocated later?

**Comment by ms705** [comment]
/cc @ICGog

Thanks! Ionel and I both have major deadlines coming up in late April, so having a window a bit later in the year would actually suit us better (if possible).

**Comment by cncfclusterteam** [comment]
Hi @ms705, how does your schedule look like in May and June? What would be the best time for you to start your research on CNCF cluster?

Currently we have ~230-280 available nodes (this may change a bit), so from our perspective next few weeks are definitely a good time for arranging the nodes for you.

Let us know! :-)

**Comment by ICGog** [comment]
Thanks a lot for the offer! The next few weeks are a bit too early for us. We've ported our Kubernetes integration to golang and we need another two months to stabilise it and to develop the workloads we want to run. It would be ideal if we could run the experiments at the end of July or in August. Would that work for you?

**Comment by dankohn** [comment]
@ICGog Please plan to complete all work on the cluster by mid-July, as we may lose availability beyond that.

**Comment by caniszczyk** [comment]
we have a new cluster up, announced here: https://www.cncf.io/community/infrastructure-lab/

we encourage folks to reapply if they are interested in access
