### ISSUE TITLE
Request for one c3.small server for LF Mentorship Project

### ISSUE THREAD

**Issue by Roshan13046** [cncf/cluster#180]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name 
Roshan Raut

### Email : 
roshanpk.raut@gmail.com

### Company/Organization
Student

### Job Title
Student
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Blockchain Automation Framework
https://wiki.hyperledger.org/display/INTERN/Project+Plan+-+Support+Clique+Consensus+for+Besu+on+HL+Labs+Blockchain+Automation+Framework

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Hyperledger Labs Blockchain Automation Framework(BAF) is a tool to deploy different DLT platforms automatically on a given Kubernetes cluster. BAF supports multi-cloud and multi-DLT deployments, and already supports HL Fabric, HL Besu, Quorum, R3 Corda. For HL Besu, currently only IBFT2 Consensus is supported by BAF. The task is to support the Clique consensus for Hyperledger Besu, so that BAF can be used to deploy and operate a HL Besu network with Clique consensus. This will also include upgrading BAF to support the latest stable Besu version.

I am going to run minikube cluster to test out an automated deployment of Hyperledger Bseu with clique consensus.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes, https://github.com/hyperledger-labs/blockchain-automation-framework
I am a mentee for above project.
https://mentorship.lfx.linuxfoundation.org/project/b282b36d-dbf4-43df-bb67-7626898176b7

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
one c3.small

### What operating system and networking are you planning to use?
Ubuntu 18.04 , Internal networking for minikube, ability to download software from the internet.

### Any other relevant details we should know about?
I am planning to use it for 6 hrs/day for the next three months from now.

**Comment by idvoretskyi** [comment]
cc @caniszczyk to take a look.

**Comment by Roshan13046** [comment]
It has been so long since I requested.
Can anyone please help me out?

**Comment by idvoretskyi** [comment]
I'll let @caniszczyk make a decision, but I'm not sure if this project is in the scope of the Cloud Native lab.

**Comment by caniszczyk** [comment]
This is fine +1

**Comment by idvoretskyi** [comment]
Done!

**Comment by vielmetti** [comment]
This project was approved and the account set up 8/2021 but there has been no usage since that date. I've closed out the project as a consequence. Please feel free to re-apply if there is an ongoing need.
