### ISSUE TITLE
Request - machine to use with the performance tests for OpenTelemetry

### ISSUE THREAD

**Issue by jpkrohling** [cncf/cluster#182]
### First and Last Name
Juraci Paixão Kröhling (@jpkrohling)
Harshita Srinivas (@harshita19244) 

### Email
jpkroehling at redhat dot com
harshita19244 at iiitd dot ac dot in

### Company/Organization
Red Hat
--

### Job Title
Principal Software Engineer
Intern for Outreachy's CNCF Tracing project (Jaeger and OpenTelemetry)

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
Performance tests for OpenTelemetry

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
We are currently in need of one server, not necessarily too powerful. We are then running the tests in there, collecting the results for the final report. The tests are open source and located here:
https://github.com/harshita19244/opentelemetry-java-benchmarks

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes
https://github.com/harshita19244/opentelemetry-java-benchmarks
Juraci is a maintainer on the Jaeger project and collaborator on OpenTelemetry
Harshita is an intern currently working on a project involving OpenTelemetry and OpenTracing

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
c3.small 

### What operating system and networking are you planning to use?
Some Linux, likely CentOS.

### Any other relevant details we should know about?
Juraci already has an account there, just needs to be assigned to this new project.

**Comment by jpkrohling** [comment]
cc @idvoretskyi, @caniszczyk

**Comment by idvoretskyi** [comment]
@jpkrohling thanks for submitting!

@caniszczyk PTAL

**Comment by idvoretskyi** [comment]
@jpkrohling done!
