### ISSUE TITLE
Add gsoria to "OpenTelemetry Performance Tests" project

### ISSUE THREAD

**Issue by jpkrohling** [cncf/cluster#185]
As a follow-up of #182, would it be possible to please add @gsoria to the list of people with access to the project "OpenTelemetry Performance Tests" at Equinix? Her email address is soria.gaby@gmail.com . Thanks!

**Comment by jpkrohling** [comment]
cc @idvoretskyi

**Comment by idvoretskyi** [comment]
@jpkrohling sure, will take care of this!

**Comment by idvoretskyi** [comment]
Invited!
