### ISSUE TITLE
Scalability for CNCF Demo

### ISSUE THREAD

**Issue by zilman** [cncf/cluster#19]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.
### First Name

Eugene
### Last Name

Zilman
### Email

ezilman@gmail.com
### Company/Organization

CNCF 
### Project Title

Demo
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Testing scale on bare metal
### Briefly describe the project

The goal of this project is to demonstrate each of the technologies that have been adopted by the Cloud Native Computing Foundation (CNCF) in a publicly available repository in order to facilitate their understanding through simple deployment tooling and by providing sample applications as common-ground for conversation. This project will enable replicable deployments and facilitate quantification of performance, latency, throughput, and cost between various deployment models. 
### Do you intend to measure specific metrics during the work? Please describe briefly

With this one we'd like to check how overlay networking performs with a high node count. Specifically we'll be benchmarking Weave and observing the behaviour with the collaboration of the Weave developers.
### Which members of the CNCF community and/or end-users would benefit from your work?

People interested in running Weave and Countly on larger clusters.
### Is the code that you’re going be running 100% open source? If so, what is the URL or URLs where it is located?

Yes, everything is or will be available here: https://github.com/cncf/demo
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Yes.
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?

Containers used extensively.
### Are there identified risks which would prevent you from achieving significant results in the project ?

No
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.

Yes
### Please list project titles associated with prior CNCF cluster usage.

Demo
### Please list contributions to open source initiatives for projects listed in the last question. If you did not upstream the results of the open source initiative in any of the projects, please explain why.

https://github.com/cncf/demo
### Have you ever been denied usage of the cluster in the past? If so, please explain why.

N/A
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

100
### Duration of request (minimum 24 hours, maximum 2 weeks)

2 weeks
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

With CentOS7
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

It will make sure the technology demonstration ("Demo") scales from your laptop all the way to a big bare metal cluster and works as expected. Any bugs discovered will be reported upstream.
### Any other relevant details we should know about while preparing the infrastructure?

No

**Comment by gmarek** [comment]
I'm confused. In yesterday's meeting you mentioned that the goal was to serve as a tech-demo, not testing bare metal cluster, as it's written in this proposal. While I agree with the former, I don't with the latter - there are multiple teams across a number of companies that are working on testing clusters at scale. Cc'ing Google, RedHat, CoreOS and Samsung, but there are more people and companies involved - basically sig-scale is the forum that oversees our scale testing efforts.

Also there shouldn't be a difference on testing bare metal clusters and public-cloud-based ones once the cluster is running. The results would be different, but the tooling for running tests should be the same (and I do feel very very very strongly about this).

cc @jeremyeder @wojtek-t @timothysc @xiang90 @countspongebob

**Comment by dankohn** [comment]
@gmarek More info on the CNCF Demo is at https://github.com/cncf/demo#cncf-technologies-demonstration. In short, we've been doing all of the work to date with a 20 node cluster, (and with a similarly small cluster on AWS), and are now interested in trying the same applications on a larger 100 node cluster. But we're particularly focused on the scalability of Weave and Countly, as we’re presuming that K8s easily scales to 100 nodes.

Separately, @zilman and I will be in Berlin on 10/5 and 10/6 for [ContainerCon](http://events.linuxfoundation.org/events/containercon-europe) in case you might be able to chat with us in person.

Cc @monadic @bboreham

**Comment by gmarek** [comment]
@dankohn - I see that there's some unfortunate choice of words (e.g. "Anybody who is interested in reliably running Kubernetes on big clusters."), which made me think that it's about testing K8s scalability (yes, we do scale to 100 nodes easily). What you're saying (i.e. scale-testing Weave and Countly) makes perfect sense - thanks. It's still not clear to me if this effort is supposed to be a demo or scale tests, but I'm much less concerned now.

I now see that there might be substantial differences between the ways in which we load the cluster to test K8s performance and to test other technologies. It would be perfect if we were able to create a single framework for both those applications, but I don't think it's a hard requirement any longer.

**Comment by gmarek** [comment]
I'd love to speak with you, but I wasn't planning on attending ContainerCon (@fgrzadkowski is going though).

**Comment by dankohn** [comment]
@gmarek I also changed the problematic answer from "Anybody who is interested in reliably running Kubernetes on big clusters" to "People interested in running Weave and Countly on larger clusters."

@fgrzadkowski could you please look me up? I'll be around the CNCF booth and my email is on my Github profile.

**Comment by cncfclusterteam** [comment]
@bprestonlf is this request approved as well? We could probably prepare the nodes for WW46 assuming it meets the requirements.

Is this request's intent to add 80 nodes to 20 that you have been using so far or do you want another 100 nodes beside the 20 you already have? Will the 20 nodes mentioned be freed after 2 weeks of testing on 100?

**Comment by dankohn** [comment]
Thanks for the questions. I'll update later today with more info.

**Comment by dankohn** [comment]
Please hold for now. We'd like to do some additional work before getting extra nodes.

**Comment by cncfclusterteam** [comment]
Hi @zilman @dankohn any update on this one?

**Comment by dankohn** [comment]
@zilman has all he needs for now and will reopen when he wants more resources. Thanks!
