### ISSUE TITLE
Request additional users for KEDA ARM instances

### ISSUE THREAD

**Issue by jeffhollan** [cncf/cluster#191]
Per this related issue https://github.com/cncf/cluster/issues/163 wanted to give the other maintainers access to the subscription - currently my account is the only one that can manage these instances

**Comment by jeffhollan** [comment]
@tomkerkhove

**Comment by idvoretskyi** [comment]
@jeffhollan great, please email me with the list of emails you'd like me to invite.

**Comment by tomkerkhove** [comment]
Thank you @idvoretskyi!

**Comment by tomkerkhove** [comment]
@idvoretskyi Can you please invite kerkhove.tom@gmail.com if Jeff did not request this yet?

**Comment by idvoretskyi** [comment]
@tomkerkhove done!

**Comment by tomkerkhove** [comment]
@zroubalik I think you'd like to have access as well right?

**Comment by zroubalik** [comment]
yeah :)

**Comment by jeffhollan** [comment]
😬 I must have pinged Tom only since he was asking me. @idvoretskyi if we can add @zroubalik as well

**Comment by idvoretskyi** [comment]
@jeffhollan please DM me with the desired email address to add, happy to help!
