### ISSUE TITLE
Request Infrastructure for Argo project

### ISSUE THREAD

**Issue by alexmt** [cncf/cluster#192]
### First and Last Name

Alexander Matyushentsev

### Email

alexander_matyushentsev@intuit.com

### Company/Organization

Intuit

### Job Title

Principal Software Engineer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Self-hosted GitHub Action runners

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We've received multiple requests to publish ARM images for Argo projects: [argo-cd/#4211](https://github.com/argoproj/argo-cd/issues/4211), [argo-cd/#6366](https://github.com/argoproj/argo-cd/issues/6366), [argo-workflows/#5755](https://github.com/argoproj/argo-workflows/issues/5755), [argo-rollouts/#582](https://github.com/argoproj/argo-rollouts/issues/582). We would like to setup self hosted Github Actions runners to run e2e tests on ARM servers as well as to build ARM images.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes - the project is 100% open source. Github org URL: https://github.com/argoproj/ . Website: https://argoproj.github.io/

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

C3.SMALL. We have no issues with machines provided by Github Actions free tier. So C3.SMALL should be enough. 

### What operating system and networking are you planning to use?

Ubuntu 20.04 (same as default Github Actions OS)

### Any other relevant details we should know about?

Thanks a lot for supporting open-source!

**Comment by vielmetti** [comment]
Reopening to address a data center migration and system change issue to the attention of @alexmt @jeefy .

The Arm server currently running in the Argo GHA project is a c1.large.arm system in SJC1, sv-c1-large-arm-01.

Our data center in SJC1 is closing, and our c1.large.arm system type is being retired. We have a replacement system type, c3.large.arm64, which is a much more capable replacement.

We'd like you to migrate over to the new system as soon as it's feasible - you should find everything more or less the same on the c3 as the c1, except that it's way faster, and that it doesn't have 32-bit Arm support.

**Comment by vielmetti** [comment]
All of the migration work is long since completed; closing.
