### ISSUE TITLE
Request Infrastructure for Woodpecker-CI project

### ISSUE THREAD

**Issue by anbraten** [cncf/cluster#194]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Anton Bracke

### Email

anbraten @ woodpecker-ci.org

### Company/Organization

Woodpecker-CI Team

### Job Title

Maintainer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Self-hosted instance of Woodpecker-CI

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Woodpecker-CI is tested and build with Woodpecker-CI. We plan to host a Woodpecker-CI server instance with runners to execute those pipelines.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Woodpecker-CI is 100% OSS (Apache 2.0)

https://github.com/woodpecker-ci/woodpecker
https://landscape.cncf.io/?selected=woodpecker-ci
https://woodpecker-ci.org/

I am a core maintainer of the project. 

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

1x c3.small
an additional arm server (c1.large.arm) would be nice for testing & building arm images

### What operating system and networking are you planning to use?

newest ubuntu / debian

### Any other relevant details we should know about?

Additional access for `owner @ woodpecker-ci.org` would be great

**Comment by caniszczyk** [comment]
-1, we are prioritizing CNCF projects atm
