### ISSUE TITLE
Current cluster status

### ISSUE THREAD

**Issue by dankohn** [cncf/cluster#20]
This issue will (hopefully) be updated weekly to show the current CNCF community cluster allocations.

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 10/11/2016:

| Company/Organization | Project Title | Start Date | Nodes |
|----------------------|---------------|------------|-------|
| CNCF Marketing       | CNCF Demo     | ~1.08.2016 | 20    |
| Joyent               |               | ~1.03.2016 | 55    |
|                      |               |            |       |

Please note that failed nodes and management nodes are _not_ included.

Would you like to see any other data here @dankohn?

**Comment by dankohn** [comment]
This is a great start, thank you. Ideally, you could add a column that would
link to the Github issue describing the allocation request. Also, it's probably
worth adding end date.
 





On Thu, Nov 10, 2016 10:03 AM, cncfclusterteam notifications@github.com
wrote:
CLUSTER ALLOCATIONS AS OF 10/11/2016:
Company/OrganizationProject TitleStart DateNodesCNCF MarketingCNCF Demo
~1.08.201620Joyent~1.03.201655Please note that failed nodes and management nodes
are not  included.

Would you like to see any other data here @dankohn?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



--Dan Kohn <mailto:dan@linuxfoundation.org>Executive Director, Cloud Native
Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 24/11/2016:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| Joyent |  | ~1/03/2016 | | 55 | |
| Container Solutions | Deploying and running Elasticsearch on a Mesos cluster | 24/11/2016 | 5/12/2016 | 100 | #13 |
|  |  |  |  |

**Comment by dankohn** [comment]
Great update, @cncfclusterteam, thank you. @bcantrill could you please create an issue to describe the Joyent allocation and give some indication of how much longer you need it.

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 24/11/2016:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| Joyent |  | ~1/03/2016 | | 55 | |
| Container Solutions | Deploying and running Elasticsearch on a Mesos cluster | 24/11/2016 | 02/01/2017 | 100 | #13 |
| PingCAP, Inc. | Easier, scalable deployment of TiDB | 12/12/2016 | 02/01/2017 | 100 | #17 |
|  |  |  |  |

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 03/01/2017:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| Joyent |  | ~1/03/2016 | | 55 | |
| Container Solutions | Deploying and running Elasticsearch on a Mesos cluster | 24/11/2016 | 02/01/2017 | 100 | #13 |
| PingCAP, Inc. | Easier, scalable deployment of TiDB | 12/12/2016 | 16/01/2017 | 100 | #17 |
| Red Hat | OVN data plane performance testing | 22/12/2016 | 16/01/2017 | 20 | #26 |

**Comment by cncfclusterteam** [comment]
@bcantrill could you please give us an update about the cluster allocation for Joyent?

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 25/01/2017:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| Joyent |  | ~1/03/2016 | | 55 | |
| Container Solutions | Deploying and running Elasticsearch on a Mesos cluster | 24/11/2016 | TBA | 100 | #13 |
| PingCAP, Inc. | Easier, scalable deployment of TiDB | 12/12/2016 | TBA | 100 | #17 |
| Red Hat | OVN data plane performance testing | 22/12/2016 | TBA | 20 | #26 |

TBA - To Be Announced, due to the upcoming maintenance window current tenants have been granted access until it takes place.

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 24/02/2017:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| RedHat |  Deploying 1000 nodes of OpenShift on the CNCF Cluster (Part 2) | 24/02/2017 | 13/03/2017 | 110 | #21 |
| Huawei | OpenSDS Kubernetes Integration Testing | 24/02/2017 | 13/03/2017 | 20 | #30 |

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 21/03/2017:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |
| RedHat |  Deploying 1000 nodes of OpenShift on the CNCF Cluster | 24/02/2017 | 31/03/2017 | ~419 | #21 #22 |

**Comment by cncfclusterteam** [comment]
## Cluster Allocations as of 21/03/2017:

| Company/Organization | Project Title | Start Date | End Date | Nodes | Request Link |
| --- | --- | --- | --- | --- | --- |
| CNCF Marketing | CNCF Demo | ~1/08/2016 | | 20 | #6 |

**Comment by caniszczyk** [comment]
no longer relevant: https://www.cncf.io/community/infrastructure-lab/
