### ISSUE TITLE
Onlydole access request for the community cluster 

### ISSUE THREAD

**Issue by onlydole** [cncf/cluster#201]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Taylor Dolezal

### Email
tdolezal@linuxfoundation.org

### Company/Organization
Cloud Native Computing Foundation

### Job Title
Head of Ecosystem

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
End user community research

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
I plan to use this access to run temporary CNCF projects and cross project integrations to better help support end user groups. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Correct! I plan to use only OSS projects and mostly projects under the CNCF umbrella.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
I expect to use a typical 3 node cluster, but may do some experiments with auto scaling as needed.

### What operating system and networking are you planning to use?
Typically Ubuntu, Debian, and other *nix variants.

### Any other relevant details we should know about?
Thank you for providing this!

**Comment by idvoretskyi** [comment]
@onlydole invited!

**Comment by onlydole** [comment]
Thank you so much, @idvoretskyi 😄
