### ISSUE TITLE
hh@cncf.io => CNCF Community Infrastructure Administrator

### ISSUE THREAD

**Issue by hh** [cncf/cluster#204]
### First and Last Name

Hippie Hacker

### Email

hh@cncf.io

### Company/Organization

CNCF

### Job Title

Strategic Initiatives Contractor from ii.nz

### Project Title

CNCF Community Infrastructure

### Briefly describe the project

Assist in administration of CNCF Project sub accounts.

**Comment by caniszczyk** [comment]
@jeefy or @vielmetti can you get hh admin access thx

**Comment by jeefy** [comment]
hh Should have an invite now. :)

**Comment by vielmetti** [comment]
Super!

When you all are all squared away, we should pick a time for a sync and I can walk you all through some administrative and accounting and upgrades we are working on here at @equinix that will be relevant to the CNCF project.

**Comment by caniszczyk** [comment]
wohooo thanks @vielmetti, maybe find time after kubecon EU or in Valencia if you're there :)?

**Comment by hh** [comment]
I've got access now. Thanks @caniszczyk & @jeefy!

@vielmetti keen to see what admin and accounting options you've been working on. I'll ping you on slack.
