### ISSUE TITLE
Kube-OVN project review

### ISSUE THREAD

**Issue by vielmetti** [cncf/cluster#210]
In #118 a proposal was made for Kube-OVN to get short term
access to resources to support a specific task. Since then, the
project has been busy, with a last login and last deploy of several
systems this month.

Mengxin Liu from @alauda has been deploying systems. I would like
to review this project for several aspects:

- does it merit a new proposal?
- are the resources actually being used for Kube-OVN, or for some other project?
- Can we get a project update on the proposed work from #118 ?

thanks

**Comment by vielmetti** [comment]
attn @oilbeater @edwarnicke

**Comment by oilbeater** [comment]
Hi @vielmetti , the origin task in the proposal has finished. But our members in the team are still using this account to do some development and investigation work related to Kube-OVN. I think we should close the project and make new proposal when needed. Sorry for the inconvenience.

**Comment by vielmetti** [comment]
Thanks @oilbeater - can we close the project now, and can you put in a new request for the new work if needed?

**Comment by oilbeater** [comment]
@vielmetti Yes, the project can be closed now.
