### ISSUE TITLE
Karmada CI Infrastructure

### ISSUE THREAD

**Issue by riverzhang** [cncf/cluster#211]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Rong Zhang

### Email
riverzhang90@gmail.com

### Company/Organization
@vivo / Karmada

### Job Title
Software Engineer / Karmada committer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
Karmada CI Infrastructure

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
We are going to build CI infrastructure for testing our karmada installer(create、scale、delete、reset、upgrade、etc...) and codes(unit test and e2e test).
I would like to the CI pipeline like follows:
On-PR CI Jobs:
- unit-tests - syntax testing
- stage 1  kubectl-karmada tests for all supported configurations(like kubectl-karmada init、join、unjoin)
- stage 2  helm charts tests for all supported configurations
- stage 3  install karmada from binaries tests
- stage 4  Upgrade tests(non-HA and HA upgrade tests)
- stage 5  add/delete member cluster and reset karmada tests
- stage 6  external etcd cluster supported tests
- stage 7  Addons tests(test special configurations like istio,argocd,etc...)
- stage 8  e2e test(check karmada api and run e2e test)

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
YES! Karmada is 100% open source!

GitHub Repo: https://github.com/karmada-io/karmada

I am working in @vivo for maintaining and developing Karmada, and I am the committer of karmada Community. and I want to create a karmada installation project. In the meeting, we had a detailed discussion with @RainbowMango and @kevin-wangzefeng .

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
We want to build out CI infrastructure also based on Kubernetes([self-hosted runners on kubernetes,](https://medium.com/geekculture/github-actions-self-hosted-runner-on-kubernetes-55d077520a31) [kubevirt on kubernetes](https://kubevirt.io/labs/kubernetes/lab1.html), etc...). E.g: unit-test -> create vms by kubevirt -> deploy 1 host k8s cluster + 2 member k8s cluster-> deploy karmada -> check karmada api and run e2e test -> delete vms, so we expect to use:
1 x c3.medium.x86 as k8s controlplane node
3 x s3.xlarge.x86 as k8s worker node

### What operating system and networking are you planning to use?
Centos7
Ubuntu 21.04

### Any other relevant details we should know about?
No

**Comment by jeefy** [comment]
@riverzhang has been invited! :) 

/assign
/close
