### ISSUE TITLE
On-demand infrastructure application

### ISSUE THREAD

**Issue by matttrach** [cncf/cluster#218]
Hello! I would like access to the CNCF on-demand infrastructure for validating Kubernetes configurations and IAC implementations.
My goals are to develop some Terraform modules to deploy infrastructure for validating Kubernetes distros with the end goal of achieving some continuous deployment of artifacts relating to specific Kubernetes hardware/software configurations.
The target audience is Kubernetes distro developers working in home labs.

The idea is to create some Terraform modules which enable end users to implement a CI/CD system (Tekton) which can validate Kubernetes distro conformance (using the Sonobuoy conformance tests). The infrastructure will be used in the development and testing of the IAC modules with the goal of providing a turnkey solution for Kubernetes distros to build highly secure software factories on CNCF infrastructure.

**Comment by caniszczyk** [comment]
Is this for a CNCF project in particular or just a side project? Is the code open sourced?

**Comment by matttrach** [comment]
If I get access to the infrastructure (necessary for development) the source code will be open (on GitHub) and the modules published on Hashicorp's Terraform registry. This would be a separate effort from any currently recognized CNCF project, but my goal is to provide a solution which Kubernetes distros could easily adopt. Terraform modules of this kind are not meant to be directly used as live infrastructure, but rather more like templates which organizations can implement with their requirements in mind. The implementation of those modules is usually closed by necessity (the infrastructure organization is usually proprietary), but does not have to be. That part is up to those who implement the modules.

**Comment by caniszczyk** [comment]
for now we are prioritizing CNCF projects/maintainers, so sorry
