### ISSUE TITLE
Compute resource for kubernetes-sigs/node-feature-discovery

### ISSUE THREAD

**Issue by fmuyassarov** [cncf/cluster#219]
### First and Last Name
Feruzjon Muyassarov

### Email
feruzjon.muyassarov@intel.com

### Company/Organization
Intel

### Job Title
Cloud orchestration software engineer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
Run end to end test as pre-submit test for kubernetes-sigs/node-feature-discovery

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
We would like to run our [end to end tests ](https://github.com/kubernetes-sigs/node-feature-discovery/tree/master/test/e2e). In short, NFD project inspects k8s nodes and reports their characteristics (server characteristics, type of the CPU, memory etc) as node labels. When running the tests, we as developers need to know the server characteristics in advance so that we can configure our tests to run against those features. As such, having dedicated servers for our k8s cluster is important. We currently have a cluster on AWS, but it is limited in a sense that we can't run multiple tests in parallel because we don't have an access to the server but to a AWS cluster and running multiple tests in parallel on the same k8s cluster will interfere and break things.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/kubernetes-sigs/node-feature-discovery
I'm a contributor to the project and I've discussed this request with project maintainer @marquiz

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
2 x [m3.small.x86](https://metal.equinix.com/product/servers/m3-small/)

### What operating system and networking are you planning to use?
Probably Ubuntu

### Any other relevant details we should know about?
No

**Comment by fmuyassarov** [comment]
Hi @caniszczyk . Thanks for the quick response. Is there any further step I need to take to proceed with this request ?

**Comment by fmuyassarov** [comment]
@jeefy @caniszczyk can @marquiz be given access as well?

**Comment by fmuyassarov** [comment]
Hi @jeefy @caniszczyk  sorry to bother you again. Any chance that we can get this ticket resolved any time soon?

**Comment by marquiz** [comment]
ping @jeefy @caniszczyk @idvoretskyi any update on this?

**Comment by fmuyassarov** [comment]
/cc @idvoretskyi @caniszczyk @vielmetti 
Should I close this ticket if no resources can be provided?

**Comment by idvoretskyi** [comment]
@fmuyassarov what extra resources are requested, sorry?

**Comment by fmuyassarov** [comment]
@idvoretskyi only the resources requested in the description of this issue is enough for us. Basically, 2 x [m3.small.x86](https://metal.equinix.com/product/servers/m3-small/).

**Comment by idvoretskyi** [comment]
@fmuyassarov I see, yes, I'll take care of this.

**Comment by fmuyassarov** [comment]
Appreciate it :+1:

**Comment by fmuyassarov** [comment]
@idvoretskyi any updates ?

**Comment by fmuyassarov** [comment]
ping @caniszczyk

**Comment by fmuyassarov** [comment]
Thanks a lot @idvoretskyi . I've received the invitation now.

**Comment by fmuyassarov** [comment]
@idvoretskyi would you mind to send an invite to @marquiz too (markus.lehtonen@intel.com) ?
Thanks in advance. Then I think we are good to close this issue.

**Comment by jeefy** [comment]
@fmuyassarov Added! And closing. :)

**Comment by vielmetti** [comment]
@fmuyassarov -

There is a system "nfd01" in your project which was powered down

Device powered off	10/06/2023, 08:39 AM (GMT-04:00 DST)

but is still an active node. If you mean to no longer use this system, it's necessary to "destroy" the machine, which will return it to the pool; otherwise the bare-metal server stays attached to you and still costs credits.

Found this in a recent audit.

cc @jeefy

**Comment by fmuyassarov** [comment]
> @fmuyassarov -
> 
> There is a system "nfd01" in your project which was powered down
> 
> Device powered off 10/06/2023, 08:39 AM (GMT-04:00 DST)
> 
> but is still an active node. If you mean to no longer use this system, it's necessary to "destroy" the machine, which will return it to the pool; otherwise the bare-metal server stays attached to you and still costs credits.
> 
> Found this in a recent audit.
> 
> cc @jeefy

@vielmetti 
Yes, sorry for that. Actually at some point I wasn't able to delete the server and I was trying to contact the Equinix folks but seems I forgot that. I have now delete the server though. Thanks for the heads up.

**Comment by vielmetti** [comment]
Thanks @fmuyassarov ! Appreciate it. Closing this issue out for now.
