### ISSUE TITLE
Request adding members to access Longhorn projects on CIL cluster

### ISSUE THREAD

**Issue by innobead** [cncf/cluster#222]
### First and Last Name

David Ko

### Email

dko@suse.com

### Company/Organization

SUSE

### Job Title

Senior Engineering Manager

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Longhorn development

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We would like to work on future benchmark & performance testing for Longhorn's next-gen data engine

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

YES. Longhorn is a CNCF project. Check [longhorn.io](https://longhorn.io/) and [longhorn/longhorn](https://github.com/longhorn/longhorn) for more information.

I am a maintainer of the Longhorn project.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

We already have a few members able to access `Longhorn Development` and `Longhorn` projects on the CNCF CL cloud, but would like to request to add one more member to help with future tasks requiring CIL resources. 

We use c3.medium.x86 instances normally, but will also check what type is supported by CIL. 

### What operating system and networking are you planning to use?

It depends, but usually OpenSUSE OS

### Any other relevant details we should know about?

- Please add Damiano Cipriani (damiano.cipriani@suse.com), Shuo Wu (shuo.wu@suse.com), and Phan Le (phan.le@suse.com) to access the existing Longhorn projects. 
- Remove Joshua Moddy (joshua.moody@suse.com) and Keith Lucas (keith.lucas@suse.com) from accessing Longhorn projects.

cc @DamiaSan @shuo-wu

**Comment by innobead** [comment]
@caniszczyk Could you help with this? Thanks!

**Comment by innobead** [comment]
Hi, @caniszczyk any update? or anyone can help with this. Thanks first!

**Comment by innobead** [comment]
@jeefy could you help with that? Thanks.

**Comment by innobead** [comment]
@vielmetti any update on this? thanks.

**Comment by vielmetti** [comment]
attn @jeefy

**Comment by idvoretskyi** [comment]
@innobead @vielmetti I'll take care of this, no worries.

**Comment by idvoretskyi** [comment]
@innobead invites sent, please check.

**Comment by innobead** [comment]
Thanks, @idvoretskyi for the prompt action! Members will check first, then update here later. 

BTW, have you removed the below accounts from the access?

- Remove Joshua Moddy ([joshua.moody@suse.com](mailto:joshua.moody@suse.com)) and Keith Lucas ([keith.lucas@suse.com](mailto:keith.lucas@suse.com)) from accessing Longhorn projects.

**Comment by idvoretskyi** [comment]
@innobead no, I haven't, but happy to re-invite if needed.

**Comment by innobead** [comment]
Thanks, @idvoretskyi , Shuo and Damiano can access equinix metal successfully :+1: 

Two remaining things need your help.

- Need to remove two existing accounts, Joshua Moddy ([joshua.moody@suse.com](mailto:joshua.moody@suse.com)) and Keith Lucas ([keith.lucas@suse.com](mailto:keith.lucas@suse.com)), because they don't use this environment anymore. 
- Have one more invitation for Phan Le (phan.le@suse.com) to access Equinix metal because he will help with the Longhorn project.

Thanks.

**Comment by jeefy** [comment]
@innobead Done re: two remaining things. :)

**Comment by innobead** [comment]
Thanks, @jeefy !

We have one issue, members are able to use `Longhorn` project instead of `Longhorn Development`. 

Could you help correct the permission to access `Longhorn Development` only for Damiano Cipriani ([damiano.cipriani@suse.com](mailto:damiano.cipriani@suse.com)), Shuo Wu ([shuo.wu@suse.com](mailto:shuo.wu@suse.com)), and Phan Le ([phan.le@suse.com](mailto:phan.le@suse.com)). Thank you!

**Comment by jeefy** [comment]
Damiano and Shuo have been added. Phan already had access to both projects.
:)

**Comment by innobead** [comment]
Thanks, @jeefy . All good now :+1:
