### ISSUE TITLE
Getting started with Hyperledger Foundation

### ISSUE THREAD

**Issue by arsulegai** [cncf/cluster#223]
**Background:** I am from Hyperledger Foundation community. The scope of Hyperledger Foundation is to host blockchain and multiparty systems projects under the Linux Foundation. The current year I am mentoring a Linux Foundation Mentorship project about getting started on blockchain technology. Refer to the code base at https://github.com/hyperledger-tooling/start-here-hyperledger.

**Request:** The project is currently looking into building a back end service to dynamically fetch contents from across multiple platforms and aggregate them with search and index capability. We’re looking at having a API service built for experimenting some of these. The long term plan is to do it without additional server requirements.

I heard about the labs compute space in CNCF from David Boswell, Sr Director, Hyperledger Foundation. Request the community here to help us with the development.

**Comment by ryjones** [comment]
@arsulegai you need to fill out the form - [the content is here](https://github.com/cncf/cluster/issues/new?assignees=caniszczyk%2C+idvoretskyi&labels=cluster+request&projects=&template=cncf-community-lab-cluster-request.md&title=)

**Comment by arsulegai** [comment]
> @arsulegai you need to fill out the form - [the content is here](https://github.com/cncf/cluster/issues/new?assignees=caniszczyk%2C+idvoretskyi&labels=cluster+request&projects=&template=cncf-community-lab-cluster-request.md&title=)

Thanks @ryjones , this mentorship program has ended now. I will check if other developers are interested, and if there is enough support for development then I will raise a request for the resource.

**Comment by ryjones** [comment]
@arsulegai I would close this issue.
