### ISSUE TITLE
Request for arm64 machines to run GH action runners for etcd-io 

### ISSUE THREAD

**Issue by dims** [cncf/cluster#227]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Davanum Srinivas

### Email
davanum@gmail.com

### Company/Organization
CNCF / AWS

### Job Title
Principal Engineer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
arm64 based testing for etcd

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

The etcd team had marked `arm64` in their `Tier 1` here before, but then downgraded it to `Tier 3` as they lost access to the `arm64` infrastructure
https://etcd.io/docs/v3.5/op-guide/supported-platform/

Please see for context:
- https://github.com/etcd-io/etcd/issues/14748
- https://groups.google.com/g/etcd-dev/c/3s-GT1t8kBc/m/s3k7UoLoBQAJ

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

https://github.com/etcd-io/etcd/

Yes, I am a contributor to Kubernetes, containerd and etcd.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

2x `c3.large.arm`

### What operating system and networking are you planning to use?

Linux (probably ubuntu)

### Any other relevant details we should know about?

cc @serathius @spzala

**Comment by caniszczyk** [comment]
+1

**Comment by idvoretskyi** [comment]
@dims invite sent!

**Comment by vielmetti** [comment]
the issue of arm64 support for etcd goes back a long, long ways to https://github.com/etcd-io/etcd/issues/5054 - looking forward to getting this solidified once and for all.

**Comment by dims** [comment]
thanks @caniszczyk @idvoretskyi @vielmetti !

**Comment by idvoretskyi** [comment]
@dims JFYI, I believe @vielmetti may provide more details, but ARM instances are not available across all metros on Equinix Metal.

You may find the actual capacity by running the following CLI command with the `metal-cli`:

```
metal capacity get | grep arm
```

**Comment by vielmetti** [comment]
We sorted out availability, and two systems are being turned up.

**Comment by vielmetti** [comment]
Two GH runner systems are online; from the Equinix side this looks OK to close as "completed".

**Comment by dims** [comment]
This is done and ready and it is working fine! thanks @vielmetti @idvoretskyi @caniszczyk
