### ISSUE TITLE
Requesting use of cncf/cluster resource for @packershift platform

### ISSUE THREAD

**Issue by jbanimineni** [cncf/cluster#230]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Jeh

### Email
jbanimineni@packershift.io

### Company/Organization
PackerShift
GitHub - https://github.com/packershift

### Job Title
Architect

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
PackerShift - Automate everything, release better software faster with DevOps

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
1. We are @packershift developing an orchestration engine for cloud-native application build/deployment/migration to multiple cloud environments.
2. You can view the application logs, git history, developer history, etc.. from the dashboard
3. Integrating GitOps tools for auto deployment
4. You can monitor your application health checks/ metrics on the same dashboard 
5. Providing support for multi-tenant users/organizations
6. Developing docker catalog for single click deployments on K8S clusters
7. Adding support for multiple open-source CI/CD tools which can be deployed from PackerShift dashboard
8. K8S cluster management with RBAC 
9. based on user selection docker and K8S orchestration can be done in the platform
10. providing and describing detailed information about the application in the dashboard
11. no need to switch multiple dashboards 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/packershift/packershift
License - https://github.com/packershift/packershift/blob/main/LICENSE

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?
server type - m3.small.x86
server count - 5

### What operating system and networking are you planning to use?
Ubuntu and deploying calico network to use in the  K8S cluster for development/testing purposes of the application

**Comment by jbanimineni** [comment]
Any update on the cluster request access?

**Comment by jbanimineni** [comment]
@caniszczyk and @idvoretskyi please review my request and help us to proceed further on the same.

**Comment by caniszczyk** [comment]
we are prioritizing CNCF projects currently for use of the cluster, we recommend you seek out promotional credits from cloud providers that are a bit more flexible, e.g., 

https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/
