### ISSUE TITLE
Request infrastructure for Merbridge project

### ISSUE THREAD

**Issue by kebe7jun** [cncf/cluster#236]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

Kebe Liu

### Email

Kebe Liu: mail@kebe7jun.com 
Xunzhuo Liu: mixdeers@gmail.com

### Company/Organization

DaoCloud / Merbridge

### Job Title

Merbridge Maintainer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Merbridge's performance tests.
Merbridge's e2e testing.

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Merbridge uses eBPF instead of iptables to accelerate the service grid, and currently supports istio, linkerd, kuma, and osm.
We currently do not have a more reliable infrastructure to run our ongoing performance tests to demonstrate Merbridge's strength.
So we'd like to have some virtual or physical machines to run our github runner on to test our performance and compatibility.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

100%.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

2 * s3.xlarge.x86 for performance tests.
1 * c3.medium.x86 for compatibility test.
1 * c3.large.arm64 for arm64 compatibility test [optional].

### What operating system and networking are you planning to use?

Ubuntu 20.04 or higher.

**Comment by kebe7jun** [comment]
@caniszczyk @idvoretskyi PTAL.

**Comment by caniszczyk** [comment]
+1

**Comment by idvoretskyi** [comment]
@kebe7jun invites sent!

**Comment by kebe7jun** [comment]
Got! thanks!
