### ISSUE TITLE
Visibility into cluster hardware utilization

### ISSUE THREAD

**Issue by jeremyeder** [cncf/cluster#24]
Hi, it would be useful if cluster users could have (read-only) visibility into:

* per-port utilization and statistics (such as error counters) from both ToR and core/interconnect switches
* syslog data from networking gear

Without this, debugging performance, link issues, driver/firmware issues at the host level becomes very difficult.  Cluster users could make more progress if they had such visibility and would reduce turn-around time for resolving issues.

**Comment by SuperQ** [comment]
This can be done with Prometheus and the snmp_exporter.

**Comment by caniszczyk** [comment]
closing this as we have a new setup: https://www.cncf.io/community/infrastructure-lab/
