### ISSUE TITLE
Infrastructure request for Falco kernel testing

### ISSUE THREAD

**Issue by LucaGuerra** [cncf/cluster#240]
### First and Last Name

Luca Guerra

### Email

luca@guerra.sh

### Company/Organization

CNCF Falco Org / Sysdig Inc.

### Job Title

Sr. Engineer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Falco Kernel Version Testing

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

The CNCF project [Falco](https://falco.org) has some core components, including two eBPF probes and a kernel module, that interact with the Linux kernel at a very low level and can be installed on a vast range of Linux kernel versions and distributions. We wish to enhance our automated testing by **setting up resources to test and validate our changes to Falco with many kernel versions**. This will allow us to build CI tests and regression testing to verify that feature changes are non-breaking, confirming backwards compatibility, and more easily test our code against newer kernel versions to identify potential issues sooner.

Running this kind of tests is technically more challenging and requires more resources than regular unit and integration testing for userspace components, which we already perform in our pipelines. For instance, kernel testing usually require quickly booting and tearing down sets of virtual machines loaded with specific versions of the Linux kernel without emulation, which is why the bare metal instances that Equinix provides look like a great tool for the job.

The Falco maintainer team has been looking for ways to perform this kind of testing, and this project has been recommended as well by the CNCF TOC during the Falco review for its path to graduation within the CNCF landscape.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes. All code, including kernelspace and userspace components, as well as the testing pipelines and any tool that was or will be developed for the project is made publicly available within the falcosecurity organization on GitHub https://github.com/falcosecurity . I am a core maintainer for the project.

### What kind of machines and how many do you expect to use (see: https://metal.equinix.com/product/servers/)?

Falco is compatible with x86_64 and Aarch64, therefore:
* 1 x m3.large.x86
* 1 x c3.large.arm64

### What operating system and networking are you planning to use?

As a base OS we plan to use Ubuntu 22.04 .

**Comment by jeefy** [comment]
@LucaGuerra Heya! I've created the Equinix project and added you to it. Feel free to ping me (jsica@linuxfoundation.org) with any other emails that need to be added to the project. :)

**Comment by LucaGuerra** [comment]
We set up the machines as explained above and tested the infrastructure. It works nicely for the kernel testing pipelines we're developing! I think I can close this issue, feel free to ping me for any issue/remark.
