### ISSUE TITLE
AWS account for Harbor add and restore

### ISSUE THREAD

**Issue by OrlinVasilev** [cncf/cluster#241]
### First and Last Name
Orlin Vasilev

### Email
orlin@orlix.org ; ovasilev@vmware.com

### Company/Organization
VMware/CNCF

### Job Title
Harbor Community Lead

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)
Harbor
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
Harbor testing

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
yes
### Any other relevant details we should know about?
We have account for Harbor but I need to added and daojunz@vmware.com to be restored
Thank you!
Orlix

**Comment by jeefy** [comment]
Passed along creds to @OrlinVasilev, should be g2g :)
