### ISSUE TITLE
Access to Equinix Metal for Istio

### ISSUE THREAD

**Issue by craigbox** [cncf/cluster#243]
Hi team,

Istio would like to do some performance testing of the [new Ambient Mesh feature](https://istio.io/latest/blog/2022/introducing-ambient-mesh/) on Equinix Metal.  Can this please be arranged?

❤️ 

Craig

_(Update: There's a form!  The link to get here didn't recognise that.  [PR](https://github.com/cncf/cluster/pull/244).)_

### First and Last Name

Craig Box; @craigbox on CNCF Slack

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Istio Ambient Mesh performance testing

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Look at performance numbers for [Ambient Mesh](https://istio.io/latest/blog/2022/introducing-ambient-mesh/), including latencies at various RPS and CPU/RAM usage.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Performance testing for https://github.com/istio/istio, potentially using https://github.com/kinvolk/service-mesh-benchmark.

[I sometimes do Istio things for fun](https://istio.io/latest/blog/2023/istio-graduates-within-cncf/) when I'm waiting for my colleagues to wake up.

### What kind of machines and how many do you expect to use (see: https://deploy.equinix.com/product/bare-metal/servers/)?

> "Our setup mimicked our earlier experiments: we ran all code in the Equinix Metal `dfw2` datacenter, which once again yielded the lowest-variance behavior that we found. Our cluster comprised 6 worker nodes of the s3.xlarge.x86 configuration (Intel Xeon 4214 with 24 physical cores @ 2.2GHz and 192GB of RAM) on which the benchmark application ran, plus one load generator node of the same config, plus one K8s master node of a c2.medium.x86 config."

### What operating system and networking are you planning to use?

Given Lokomotive has been discontinued, their recommendation is [Typhoon](https://github.com/poseidon/typhoon). But, we'll do whatever.

### Any other relevant details we should know about?

The work will probably be overseen, if not performed by, @howardjohn or @linsun.

**Comment by nate-double-u** [comment]
@craigbox, does https://github.com/cncf/cluster/issues/248 supersede this request? (Relating to the 2023 CNCF LFX Term 3 mentoring project: [CNCF - Istio: Implement performance testing](https://mentorship.lfx.linuxfoundation.org/project/bbebd511-1a3e-4c4f-b106-2f09690825c5)), or is this request separate?

/cc @linsun @andream12345
/cc @caniszczyk @jeefy

**Comment by linsun** [comment]
It is related to the mentoring project but we would love to also do performance testing beyond the short mentoring period, for each release if possible.

**Comment by craigbox** [comment]
We want the access to live on pass the mentorship in #248, so please make sure Lin, John and I are also invited & have ongoing access.

(What did he do that I didn't do to get such quick turnaround? 😄 )

**Comment by vielmetti** [comment]
I think I saw a request in the Equinix system for reserved nodes (our "self-service reservation" process) to support this task.

We don't do reservations for CNCF projects, preferring instead to use "on-demand' resources. 

Same equipment, simpler accounting. Can you check to see what is set up, @craigbox ?

**Comment by craigbox** [comment]
That's nothing to do with me.  @Shuayb1, do you know about this?

**Comment by Shuayb1** [comment]
The requests was mistakenly made and have been cancelled over the email with Emily.

I'm using the on demand now.

**Comment by idvoretskyi** [comment]
@craigbox a quick check if the access has been granted. If not, I'm happy to handle it for you.

**Comment by craigbox** [comment]
not for me specifically, no.  (And I'm always so glad to hear from you.)

**Comment by idvoretskyi** [comment]
> not for me specifically, no. (And I'm always so glad to hear from you.)

Thanks! I'll need the list of email addresses whom to add to the project.

**Comment by craigbox** [comment]
howardjohn @ google dot com
craig.box @ gmail dot com
lin.sun @ solo dot io

**Comment by linsun** [comment]
Following up on this - I assume the access has been granted as @Shuayb1 has been testing.  I might have missed the instructions to access the env (searched in my junk folder as well), would appreciate a resend.

**Comment by vielmetti** [comment]
I think we might be all set here - if so let's close this issue out?

**Comment by linsun** [comment]
I do have a question, now that the mentoring program completes - would we be able to have ongoing access for the equinix metal for Istio's performance test?

**Comment by craigbox** [comment]
That was always the intention - this ticket was opened before we had enrolled in the mentoring program.

**Comment by linsun** [comment]
Ok cool, would be great to get this (https://github.com/cncf/cluster/issues/243#issuecomment-1854707986) confirmed @vielmetti ?

**Comment by vielmetti** [comment]
@linsun @craigbox it's generally up to the project to decide who has access to this infra, and it's generally up to the CNCF (e.g. @idvoretskyi @jeefy and the like) to flip the bits so that the right people actually have access.

At Equinix I make sure that the machines are in good shape + used according to plan, but not the specifics of the people who have access.

**Comment by craigbox** [comment]
sorry, to be clear, the "set up people with access" task is complete and can be closed (assuming Greg Hanson got access per the other ticket).

We will continue to enjoy the service on an ongoing basis!
