### ISSUE TITLE
TAG Environmental Sustainability Carbon Intensity Measurement

### ISSUE THREAD

**Issue by mkorbi** [cncf/cluster#246]
### First and Last Name

Max Körbächer

### Email

m.koerbaecher@reply.de

### Company/Organization

Liquid Reply but this request in on behalf of the CNCF TAG Environmental Sustainability

### Job Title

Founder, Cloud Native Advisor

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

TAG Environmental Sustainability Carbon Intensity Measurement

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

We want to implement an Blueprint and define an approach how to measure for CNCF projects their carbon intensity and report them with a so called Software Carbon Intensity (SCI) KPI, on which that projects can see if their actions will change the efficiency of the project. 
For this we have two issues open in the TAG Env https://github.com/cncf/tag-env-sustainability/issues/64 and for the WG https://github.com/cncf/tag-env-sustainability/issues/116

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes, we will be required to run some Kubernetes, maybe https://github.com/sustainable-computing-io/kepler or https://github.com/hubblo-org/scaphandre . Maybe also some k6 https://k6.io/open-source/

### What kind of machines and how many do you expect to use (see: https://deploy.equinix.com/product/bare-metal/servers/)?

At the current state we will require something small, that demand might change after the initial phase. https://deploy.equinix.com/product/servers/m3-large/

### What operating system and networking are you planning to use?

Ubuntu, nothing special for the network, we need to be able to ssh to the machine.

**Comment by nikimanoledaki** [comment]
Thank you @mkorbi for opening this issue! cc @guidemetothemoon

@caniszczyk & @jeefy, is there any additional information that we could provide or anything we could help clarify?

We are kicking off the Green Reviews WG this Wednesday and are eager to help unblock this work. Thanks 😊

**Comment by nikimanoledaki** [comment]
Hi folks @mkorbi @caniszczyk @jeefy 👋  The Green Reviews WG held its first meeting last week and we started planning the technical details of the project, tracked here: https://github.com/cncf/tag-env-sustainability/issues/182

Access to the infrastructure is our priority so that we can plan accordingly. Please let us know if there is anything that we can do to help with this. Thank you so much for providing this community cluster!

**Comment by rossf7** [comment]
@caniszczyk @jeefy One thing to mention is that for both kepler and scaphandre we'll need CPUs with RAPL support. So servers with Intel CPUs might be best? AMD could also work if we're sure RAPL is supported.

@mkorbi @nikimanoledaki How many nodes do we need?

I think 2 nodes might be best. So the energy measurements on the worker node are not affected by the control plane.

**Comment by mkorbi** [comment]
> @mkorbi maybe we can open up a ticket in service desk for this

That happened already a month ago and got redirected to open an issue here.




> @mkorbi @nikimanoledaki How many nodes do we need?
> 
> I think 2 nodes might be best. So the energy measurements on the worker node are not affected by the control plane.

Yes, We also could start with one but two would be perfect.

**Comment by caniszczyk** [comment]
+1

**Comment by jeefy** [comment]
Created the Equinix project and added @mkorbi to it. If anyone else needs to be added, feel free to DM me in the CNCF or K8s slack (`@jeefy`) with your emails and I'll get y'all added as well. :)

**Comment by leonardpahlke** [comment]
Thank you!

**Comment by mkorbi** [comment]
Thank you @jeefy!
