### ISSUE TITLE
Ampere/CNCF Arm CI enablement with actuated

### ISSUE THREAD

**Issue by alexellis** [cncf/cluster#255]
### First and Last Name

Alex Ellis

### Email

(Equinix account):

alexellis2@gmail.com

### Company/Organization

OpenFaaS Ltd / Actuated

### Job Title

Founder / Director.

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Ampere/CNCF Arm CI enablement with actuated

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Ampere and the CNCF are funding access to the [actuated](https://actuated.dev) platform to provide secure CI for several CNCF projects. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Projects are CNCF-hosted.

### What kind of machines and how many do you expect to use (see: https://deploy.equinix.com/product/bare-metal/servers/)?

2x c3.large.arm64, potentially expanding to 3x total later on, depending on uptake.

### What operating system and networking are you planning to use?

Ubuntu 22.04

### Any other relevant details we should know about?

In addition to myself, han@openfaas.com will need access.

**Comment by jeefy** [comment]
This should be g2g!
