### ISSUE TITLE
Lab for Cilium

### ISSUE THREAD

**Issue by dharmarajumaganti** [cncf/cluster#256]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Killercoda]([https://www.katacoda.com/courses/kubernetes/playground]) or [Play With Kubernetes](https://labs.play-with-k8s.com/).

**Comment by vielmetti** [comment]
Is this request part of the main Cilium project, or an individual learning exercise?

**Comment by dharmarajumaganti** [comment]
Yes Individual Learning exercise

**Comment by vielmetti** [comment]
@dharmarajumaganti 

The CNCF CIL is aimed at project support, not individual learning. Please see https://labs.play-with-k8s.com for one example system that provides a testbed for individual learning exercises.

@jeefy @caniszczyk closing this.
