### ISSUE TITLE
Access to the equinox metal machine

### ISSUE THREAD

**Issue by dhawton** [cncf/cluster#260]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with.

If you're looking to learn Kubernetes and related technologies, please try out [Killercoda](https://killercoda.com/playgrounds/course/kubernetes-playgrounds) or [Play With Kubernetes](https://labs.play-with-k8s.com/) instead.

### First and Last Name

Daniel Hawton

### Email

daniel.hawton@solo.io

### Company/Organization

Solo.io

### Job Title

Senior Software Engineer

### Project Title (i.e., a summary of what do you want to do, not what is the name of the open source project you're working with)

Istio performance testing

### Briefly describe the project (i.e., what are the details of what you're planning to do with these servers?)

Perform performance testing for Istio for publishing on istio.io

### Is the code that you're going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes, https://github.com/istio/istio/wiki/Istio-Performance. I am a maintainer for the workgroups: Test and Release, and Docs.

### What kind of machines and how many do you expect to use (see: <https://deploy.equinix.com/product/bare-metal/servers/>)?

a3.large.opt-m3a2

### What operating system and networking are you planning to use?

Ubuntu
Public network with virtualization and an overlay network

### Any other relevant details we should know about?

Related: https://mentorship.lfx.linuxfoundation.org/project/bbebd511-1a3e-4c4f-b106-2f09690825c5

cc: @linsun

**Comment by linsun** [comment]
Thanks @dhawton and CNCF team. I can confirm that Daniel is an Istio maintainer and his work will feed into this page: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/

We already have the metal machine, just need him to grant him the access.

**Comment by linsun** [comment]
Thank you so much @jeefy!
