### ISSUE TITLE
Cisco Devnet Access

### ISSUE THREAD

**Issue by kenowens12** [cncf/cluster#27]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### Which members of the CNCF community and/or end-users would benefit from your work?
All projects, current and interested, all members - companies and end users.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
yes. Today at ciscoshipped.com. Please to update and modify to be vendor agnostic and fully open sourced.

### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to do this within 2 months of cluster use?
Yes

### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?
Yes

### Are there identified risks which would prevent you from achieving significant results in the project ?
No

### Please state your contributions to the open source community and any other relevant initiatives
Mantl, Shipped, Kubernetes, Consol, Terreform, Traefik, Cloud Foundry

### Number of nodes requested (minimum 20 nodes, maximum ~400 nodes).
400 Nodes

### Preferred node flavor, ratio if mixed (compute, storage, any).
80%compute

### Duration of request (minimum 24 hours, maximum 2 weeks).
2 weeks

### With or Without an Operating System (restricted to CNCF predefined OS and versions as in [README](https://github.com/cncf/cluster/blob/master/README.md))?
RHEL or Centos

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
provide a ecsosystem for developing, creating, and collaborating cloud natives architecutures

**Comment by bprestonlf** [comment]
+1

**Comment by cncfclusterteam** [comment]
Hi @kenowens12, we will work on this request right after the maintenance window https://github.com/cncf/cluster/issues/28. Please watch the associated issue for precise dates.

**Comment by cncfclusterteam** [comment]
Hi @kenowens12 , due to hardware delays we will probably be moving the maintenance window to last week of February. We would like to know if you are interested in having the nodes before the maintenance takes place - most probably starting at 03.02.2017 until around 20.02.2017 - or would you rather wait until the maintenance is done?

**Comment by cncfclusterteam** [comment]
Hi @kenowens12 , we would like to prepare the nodes for you in roughly 2 weeks after current, smaller requests are finished. Will that be fine for you?

**Comment by caniszczyk** [comment]
Going to close old cluster issues, we have a new cluster setup.
