### ISSUE TITLE
Scaling Kubernetes (Scalability SIG)

### ISSUE THREAD

**Issue by caniszczyk** [cncf/cluster#3]
### First Name
Timothy 
 
### Last Name
St. Clair
 
### Email
timothysc@gmail.com
 
### Company/Organization
Red Hat
 
### Job Title
Principal Software Engineer
 
### Project Title
Kubernetes Scalability SIG
 
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
Compare and diagnose scale test results across companies.
 
### Briefly describe the project
Scaling Kubernetes (Scalability SIG)
 
### Do you intend to measure specific metrics during the work? Please describe briefly
Yes
 
### Which members of community and/or end-users would benefit from your work?
The scale sig
 
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?
Yes
 
### Are there identified risks which would prevent you from achieving significant results in the project ?
Not yet. 
 
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip questions 2 through 4.
no
 
### Please list project titles associated with prior CNCF cluster usage.
kubernetes maintainer
 
### Please list contributions to open source initiatives for projects listed in question 2. If you did not upstream the results of the open source initiative in any of the projects, please explain why.
Active SIG lead and maintainer
 
### Have you ever been denied usage of the cluster in the past? If so, please explain why.
n/a
 
### Please state your contributions to the open source community and any other relevant initiatives
I'm an active kubernetes maintainer. 
 
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.
~300 
 
### Duration of request (minimum 24 hours)
4 weeks
 
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?
Without, or RHEL
 
### Any other relevant details we should know about while preparing the infrastructure?
Ideally I think openstack-ifying would be beneficial to the community.

**Comment by jeremyeder** [comment]
@caniszczyk what will be the start and end dates of this lease?

**Comment by jeremyeder** [comment]
Hi,  not sure when the clock starts/started, but we'd like to extend our lease to 4 or even 6 weeks if that's possible.  We are going to put this gear to very productive use.  I can share our test plan if it will help justify.  /cc @caniszczyk

**Comment by cncfclusterteam** [comment]
@jeremyeder Did you archive the data from cluster? Can we process with off-boarding?

**Comment by jeremyeder** [comment]
We were off-boarded on Aug 29 :-)
