### ISSUE TITLE
OpenSDS Kubernetes Integration Testing

### ISSUE THREAD

**Issue by hannibalhuang** [cncf/cluster#30]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Howard
### Last Name
Huang
### Email
huangzhipeng@huawei.com
### Company/Organization
Huawei
### Job Title
Senior Open Source/Standard Community Manager
### Project Title
OpenSDS Kubernetes Integration Testing
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
Storage is an important part of functionality for Kubernetes, and currently there are multiple in-tree and out-of-tree volume plugins developed for Kubernetes, but it is hard to know whether the integration of storage provider is functioning as it should be without testing it. Moreover for storage that is provided from cloud provider (e.g OpenStack), there should be functional testing to prove the integration's actually working.
### Briefly describe the project
[OpenSDS](opensds.io) is a fellow Linux Foundation collaborative project and aims to provide a unified storage service experience for Kubernetes. OpenSDS could provide various types of storage resource for Kubernetes (e.g OpenStack block and file service, baremetal storage device), and we want to use CNCF Cluster to : 
- Verify the integration of OpenSDS and Kubernetes
- Verify the performance of the inegration via metrics such as IOPS, latency
- Utilize the Intel S3610 400GB SSD and 2TB NLSAS HDD for storage provisioning 
### Do you intend to measure specific metrics during the work? Please describe briefly
Yes we need to measure the storage performance (e.g IOPS, latency) to see if the integration is functioning properly.
### Which members of the CNCF community and/or end-users would benefit from your work?
Kubernetes's storage-sig will get a better view on the future storage evolution. End-users could also have first-hand knowledge of the Kubernetes Storage prowess 
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, please refer to the source code at https://github.com/opensds/opensds
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to do this within 2 months of cluster use?
Yes, and we will also probably need to feedback the result to the OpenStack community as well.
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?
Yes we are testing with container clusters managed by Kubernetes.
### Are there identified risks which would prevent you from achieving significant results in the project ?
The storage interface is not well defined in Kubernetes at the moment, and any changes in the upstream will likely break the testing. We will try to work with storage sig as much as possible
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.
No
### Please state your contributions to the open source community and any other relevant initiatives
I've been working in the OpenStack and OPNFV community for about 3 years. My stats could be found at stackalytics website
### Number of nodes requested (minimum 20 nodes, maximum ~400 nodes).
20 or less (maybe 4 or 5 node is good enough)
### Preferred node flavor, ratio if mixed (compute, storage, any).
compute and storage node
### Duration of request (minimum 24 hours, maximum 2 weeks).
2 weeks
### With or Without an Operating System (restricted to CNCF predefined OS and versions as in [README](https://github.com/cncf/cluster/blob/master/README.md))?
Ubuntu 
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
This testing could help with orchestration especially in the storage area.
### Any other relevant details we should know about while preparing the infrastructure?
No

**Comment by bprestonlf** [comment]
+1

**Comment by caniszczyk** [comment]
+1 cc: @cncfclusterteam

**Comment by cncfclusterteam** [comment]
Hi @hannibalhuang , we will prepare the nodes this week. Would you rather have 5 nodes or 20? How many of them need to be storage nodes?

**Comment by hannibalhuang** [comment]
Hi @cncfclusterteam , after discussion with out engineering team, I think we need 10 computing nodes and 5 storage nodes, so in total 15 nodes :)

**Comment by cncfclusterteam** [comment]
Hi @hannibalhuang , the nodes are ready to use, two emails with details should wait in your inbox. Please do not hesitate to contact us in case of any issues or questions.

**Comment by cncfclusterteam** [comment]
Hi @hannibalhuang  ,

I am writing to inform you that Zhipeng Huang confirmed that we can clean up the nodes for next tenants.

We hope the time spent with the cluster has been productive.

Please also notify us here when there are any follow-up articles available.

Thank you,
CNCF Cluster Team

**Comment by hannibalhuang** [comment]
@cncfclusterteam yes we will provide the link to our summary testing report once its done :)

**Comment by hannibalhuang** [comment]
@cncfclusterteam @caniszczyk we have upload our demo video at https://www.youtube.com/watch?v=1irF0kXWNpE , more detailed article yet to come :) will post here when it is ready

**Comment by hannibalhuang** [comment]
@cncfclusterteam @caniszczyk detail summary of our testing could be found here: https://www.opensds.io/blog/2017/04/24/opensds-cncf-cluster-integration-testing
