### ISSUE TITLE
Usage Followup

### ISSUE THREAD

**Issue by ronaldpetty** [cncf/cluster#34]
Hello,

I am just curious.  What is the CNCF doing to make sure there is tangible benefit(s) from use of the cluster?  I see an approval process, but not really a follow up in what was improved about the software involved.  Not trying to call any project out, just trying to close the loop so others can reference this as good use and an overall benefit.

I think maybe just linking back to an issue in the various projects would be a good start.  (ex. software X has never ran on 500+ machines, it be good to see it work).  I also realize it might not lead to some change, but should at least show a decision was made based on its usage.  I can appreciate how much time(aka money) and effort goes into running clusters.

If I missed something, I apologize.

Ron

**Comment by dankohn** [comment]
We ask every cluster user to write a blog post about their experiences with the cluster, good or bad. Best one so far is https://www.cncf.io/blog/2016/08/23/deploying-1000-nodes-of-openshift-on-the-cncf-cluster-part-1

**Comment by ronaldpetty** [comment]
Thanks @dankohn, thats cool.  Maybe worth adding a mention of that to the expectations?  Happy to do trivial PR, if interested.

**Comment by dankohn** [comment]
It's mentioned here: https://github.com/cncf/cluster/blob/master/.github/ISSUE_TEMPLATE.md#do-you-commit-to-publishing-your-results-and-upstreaming-the-open-source-code-resulting-from-your-work-do-you-agree-to-do-this-within-2-months-of-cluster-use

**Comment by ronaldpetty** [comment]
Sorry, I see it now, thanks.
