### ISSUE TITLE
Resource Request: Prometheus Benchmarking

### ISSUE THREAD

**Issue by SuperQ** [cncf/cluster#35]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Ben
### Last Name
Kochie
### Email
superq@gmail.com
### Company/Organization
Prometheus Team
### Project Title
Benchmarking
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
* Update comparison benchmarks with competing systems.
* Provide a stable test ground for testing for scaling issues

### Briefly describe the project
We would like to build a Prometheus test setup for making performance optimizations that are not possible to test in standard CI pipelines.

### Do you intend to measure specific metrics during the work? Please describe briefly
* CPU use for Prometheus and exporter(s)
* IOPs used by Prometheus server when ingesting and doing maintenance operations.

### Which members of the CNCF community and/or end-users would benefit from your work?
Prometheus community in general.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://prometheus.io

### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to do this within 2 months of cluster use?
Yes
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?
Yes, we would use and monitor containers as part of the workload test.
### Are there identified risks which would prevent you from achieving significant results in the project ?
None expected.
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.
No
### Please state your contributions to the open source community and any other relevant initiatives
Prometheus Team member
### Number of nodes requested (minimum 20 nodes, maximum ~400 nodes).
50-100
### Preferred node flavor, ratio if mixed (compute, storage, any).
* 4-5 storage nodes.
* The rest can be compute.
### Duration of request (minimum 24 hours, maximum 2 weeks).
2 weeks.
### With or Without an Operating System (restricted to CNCF predefined OS and versions as in [README](https://github.com/cncf/cluster/blob/master/README.md))?
Ubuntu 16.04
### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
It will improve Prometheus performance and efficiency.

**Comment by bprestonlf** [comment]
+1

**Comment by cncfclusterteam** [comment]
Hi @SuperQ, we would like to prepare nodes for you next week. Will that be fine for you?
How many nodes will you need precisely?

**Comment by SuperQ** [comment]
Since this is our first test, let's go for 4 storage and 50 compute nodes.

**Comment by cncfclusterteam** [comment]
Hi @SuperQ, we'd like to ask you about your experience with the CNCF cluster. Does the environment function as expected? Do you have any further plans / need additional nodes / want to extend the lease?

Please let us know the details so we can plan accordingly, thanks!

**Comment by cncfclusterteam** [comment]
Hi @SuperQ, any updates?

**Comment by SuperQ** [comment]
Sorry, I haven't had the time to do a lot of work on this testing.

If we can keep the nodes for another couple weeks, that would be great.

**Comment by cncfclusterteam** [comment]
We can for sure extend your lease for the next two weeks, that is till June 26th. After that date it will depend on cluster usage by other tenants.

**Comment by cncfclusterteam** [comment]
Hi @SuperQ, we'd like to take the nodes back at the beginning of next week - Monday, August 7th. Is that OK with you? Will you be able to finish your work and release the nodes?

**Comment by SuperQ** [comment]
Yes, this is fine.

**Comment by cncfclusterteam** [comment]
@SuperQ, Great, thanks for the confirmation. We'll take back the nodes in about 4-6 hours.

I hope that your work on the CNCF cluster has been both positive and productive.
