### ISSUE TITLE
Container network performance testing

### ISSUE THREAD

**Issue by leecalcote** [cncf/cluster#36]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

### First Name
Lee
### Last Name
Calcote
### Email
lee.calcote@solarwinds.com
### Company/Organization
SolarWinds
### Job Title
Sr. Director, Technology Strategy
### Project Title
Container Network Performance
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
Selecting the proper container network provider for a project can be difficult.  We have noticed performance differences depending on the application workload.
### Briefly describe the project
The SolarWinds container network performance meter initiates a bandwidth test between containers and compares to the performance between the corresponding hosts.  We will configure a kubernetes cluster with various network plugins (WeaveNet, Calico, Flannel, etc.) to compare performance.
### Do you intend to measure specific metrics during the work? Please describe briefly
Yes - network bandwidth throughput between containers compared to performance between hosts. Container network driver performance - CNI and CNM plugins.
### Which members of the CNCF community and/or end-users would benefit from your work?
End-users will benefit from being enlighten about how their network driver choices affect connectivity and performance of their networks. Vendors will benefit from an apples-to-apples comparison from an agnostic third-party. Kubernetes itself may benefit from an understanding of the limits of its native networking scale.
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, it will be open-sourced and located here - https://github.com/solarwinds/containers
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to do this within 2 months of cluster use?
Yes, absolutely.
### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?
Yes, ideally testing containers from that of the [CNCF Demo](https://github.com/cncf/demo) project
### Are there identified risks which would prevent you from achieving significant results in the project ?
No
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.
No
### Have you ever been denied usage of the cluster in the past? If so, please explain why.
No
### Please state your contributions to the open source community and any other relevant initiatives
- We recently put together a few slides to facilitate the [ONIF panel on container networking](https://docs.google.com/presentation/d/1iVDcu6l1xl76SDQNkDeBkOp2VPmGLN0L-EBfrGSsz1w/edit?usp=sharing)
- We're contributing to the [CNCF WG-Networking](https://github.com/cncf/wg-networking) workgroup.
- We helped create and maintain a collection of [container network solutions](https://docs.google.com/spreadsheets/d/1polIS2pvjOxCZ7hpXbra68CluwOZybsP1IYfr-HrAXc/edit?usp=sharing)
### Number of nodes requested (minimum 20 nodes, maximum ~400 nodes).
20 nodes will work. 60 would be ideal in order elicit fully-distributed network behavior.
### Preferred node flavor, ratio if mixed (compute, storage, any).
Ideally, the same compute across the nodes, so as to facilitate a uniform test. If there is variance in compute, that's fine. We'll just note this. Variance in storage is not an issue.
### Duration of request (minimum 24 hours, maximum 2 weeks).
Ideally, 2 weeks, but 1 week will suffice.
### With or Without an Operating System (restricted to CNCF predefined OS and versions as in [README](https://github.com/cncf/cluster/blob/master/README.md))?
CentOS 7 (any others will work, however)
### Any other relevant details we should know about while preparing the infrastructure?
We intend to run high-volume bandwidth and latency tests between the networked hosts.

**Comment by bprestonlf** [comment]
+1

**Comment by cncfclusterteam** [comment]
Hi @leecalcote , when would you like to start working in the cluster? will next week be fine?

**Comment by leecalcote** [comment]
@cncfclusterteam thanks for considering this request. Much of the team involved with be out next week (at DockerCon). Starting on the week of April 24th or May 1st would well, though, assuming node availability.

**Comment by leecalcote** [comment]
@dankohn, I'd like to leverage the cncf/demo to deploy kubernetes with sample apps and promote the demo project as part of this analysis. Can we engage @zilman with a question or two?

**Comment by dankohn** [comment]
Sure. 

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io>
tel:+1-415-233-1000

**Comment by cncfclusterteam** [comment]
Hi @leecalcote, we'd like to schedule the provisioning of 60 compute nodes for you. Would it be OK if we provision the nodes at the beginning of next week (assuming that his request is still valid)?

**Comment by caniszczyk** [comment]
closing as we have a new cluster setup with CIL: https://www.cncf.io/community/infrastructure-lab/
