### ISSUE TITLE
Cluster for Hyperledger-Fabric-v1.0

### ISSUE THREAD

**Issue by lhaskins** [cncf/cluster#37]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

### First Name
Latitia
### Last Name
Haskins
### Email
lhaskins@us.ibm.com
### Company/Organization
IBM/ITPC/BlockChain
### Job Title
software engineer
### Project Title
Getting 100 fabric-peer nodes running running in an hyperledger fabric network
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )
We want to verify that we can run a high number of peers in many (greater than 10) organizations. Ideally, we would be able to test this with each peer being in its own organization. We also want to reconfigure this to have more than 1 peer in each organization with 1 peer having access to a channel and the other not having access as well as the number of peers allowed in a single organization and possibly more.
 
### Briefly describe the project
This test will allow us to find possible holes when there is a high number of organizations and peers with a certain number of channels, with only certain peers having access to a specific chaincode.

### Do you intend to measure specific metrics during the work? Please describe briefly
yes, We would like to be able to track 
* the number of transactions/second allowed
* at what point would degradation begin to show depending on the number of organizations and the number of peers.
* how long does it take to spin up the containers
* how long does it take for transactions to reach all peer nodes depending on the number in the organization
 
### Which members of the CNCF community and/or end-users would benefit from your work?
* Hyperledger fabric project team members and users

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/hyperledger/fabric

### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to do this within 2 months of cluster use?
Yes, for now, we can put the results in a README

### Will your testing involve containers? If not, could it? What would be entailed in changing your processes to containerize your workload?
Yes, we have docker images.

### Are there identified risks which would prevent you from achieving significant results in the project ?
Not that I'm aware of at this time.

### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip the next three questions.
No.

### Please state your contributions to the open source community and any other relevant initiatives
This is for the Hyperledger-Fabric open source project.

### Number of nodes requested (minimum 20 nodes, maximum ~400 nodes).
125 nodes.

### Preferred node flavor, ratio if mixed (compute, storage, any).
compute nodes, but we will want to look at both TLS and non-TLS setups, so we will need to be able to save certificates for potentially 100 different nodes on each node. The specified 400GB should be more than enough.

### Duration of request (minimum 24 hours, maximum 2 weeks).
2 weeks

### With or Without an Operating System (restricted to CNCF predefined OS and versions as in [README](https://github.com/cncf/cluster/blob/master/README.md))?
With - Ubuntu 16.04

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
This is testing scalability capabilities for the fabric network. It will give us more concrete indications of where the network bottlenecks are located and the extent of those bottlenecks. Using this setup will not limit us to the possibility of our local system limitations, but fabric network limitations.
 
### Any other relevant details we should know about while preparing the infrastructure?
As stated previously, we use docker images for the different containers. We would like to be able to view the containers' logs and log into certain nodes, if necessary.

**Comment by caniszczyk** [comment]
closing this as we have a new process with CIL: https://www.cncf.io/community/infrastructure-lab/

please re-apply if you're interested in access
