### ISSUE TITLE
Digital Rebar Open Source Template Validation

### ISSUE THREAD

**Issue by zehicle** [cncf/cluster#39]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Rob

### Last Name
Hirschfeld

### Email
rob@rackn.com

### Company/Organization
RackN

### Job Title
CEO

### Project Title
Digital Rebar 

### Briefly describe the project
Automates physical network provisioning

### Which members of the CNCF community and/or end-users would benefit from your work?
RackN is a CNCF member.  The service works on Packet.net
We're not sure who else is consuming software

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes.  http://Rebar.digital
Code is github.com/digitalrebar/provision

We're talking about PROVISION only, not the v2 container stuff.

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
Type 0s.  10 - 15 machines per build for about 15 minutes per commit.

### What OS and networking are you planning to use (see: https://www.packet.net/bare-metal/)?
CustomIPXE exclusively

### Please state your contributions to the open source community and any other relevant initiatives
For CNCF, we've been working on Kubespray and Kubernetes
We have significant activity with OpenStack in the past
We have been involved in a number of projects in monior ways including Consul, Terraform, BOSH, Golang and Chef.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
Digital Rebar is the cloud native physical provisioning alternative.  This testing ensures that the community profiles work consistently.  That helps users who want to use Kubernetes and other CNCF projects on bare metal deployments.

### Any other relevant details we should know about while preparing the infrastructure?
We're already using Packet for this open source testing, so we'd be able to give you a very quick and visible win on using the infrastructure to support an open project with CNCF ties.

**Comment by caniszczyk** [comment]
+1 @zehicle, we'll get you setup today/tomorrow

Sorry for the delay, check your email for the credentials by tomorrow.
