### ISSUE TITLE
Cluster for containerd for alternate platform CI infrastructure

### ISSUE THREAD

**Issue by stevvooe** [cncf/cluster#40]
### First Name

Stephen

### Last Name

Day

### Email

stephen at docker dot com

### Company/Organization

Docker, Inc/CNCF/containerd

### Job Title

Maintainer/Software Engineer

### Project Title

containerd

### Briefly describe the project

An open and reliable container runtime: https://containerd.io.

At this time, the cluster resources requested will be used to support alternative platform builds, including but not limited to ARM, s390x and power systems. While we would like to use hosted services, the support for less popular architectures.

### Which members of the CNCF community and/or end-users would benefit from your work?

These resources will be used to build `containerd` on every pull request, merge and build releases on alternative platforms. This will allow contributors to have confidence in their changes without having to try them across platforms. This will benefit maintainers by ensuring that testing is equal across platforms. Users will benefit from a better tested container runtime.

We hope to also benefit the kubernetes community by providing a stable container runtime that will work across any platform.

The ARM community is steadily growing and we see stability there as an important part of containerd's offering. s390x and power are heavily used in enterprise applications. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, https://github.com/containerd/containerd

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

- 1x Type 2 as an `amd64` head node for running builds.
  - This will run gitlab CI (or jenkins, if necessary)
  - Required large, redundant storage to provide head room for build database (postgres)
- 1x Type 2A will run gitlab-runner for ARM builds

We'll also need a place to back up build database in case of catastrophic failure. We will not require hot standby, as impact of failure will be low.

### What OS and networking are you planning to use (see: https://www.packet.net/bare-metal/)?

Ubuntu 17.04

### Please state your contributions to the open source community and any other relevant initiatives

I am a maintainer on Moby, OCI Image Spec, containerd, SwarmKit, Docker Registry and other smaller projects.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

With `containerd` at the base of containerization, it is a critical component of the cloud native "water cycle". Having solid cross-platform support is a must.

### Any other relevant details we should know about while preparing the infrastructure?

Thanks to all those that have helped with getting this proposal together!

cc @containerd-maintainers

**Comment by caniszczyk** [comment]
+1 approved

**Comment by matjohn2** [comment]
👍  +1

**Comment by eyz** [comment]
:+1:

**Comment by vielmetti** [comment]
Account is set up, billing set to CNCF, should be ready to take its first server.

**Comment by eyz** [comment]
Great news, @vielmetti!

**Comment by caniszczyk** [comment]
This is done.

**Comment by vielmetti** [comment]
This project has been idle with no servers associated with it since 2019; I've deleted the associated project setup at Equinix Metal.
