### ISSUE TITLE
Infra management for opensource

### ISSUE THREAD

**Issue by romxyz** [cncf/cluster#41]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Rom

### Last Name
Bob

### Email
rom@cicd.xyz

### Company/Organization
CICD XYZ

### Job Title
DevOps

### Project Title
Infrastructure management

### Briefly describe the project
Infrastructure management toolset for opensource projects CICD solutions not requiring hosted CI services for SDLM

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, TBD

**Comment by dankohn** [comment]
Hi, we'd be happy to support this work, but could you please open a new issue when you have a repo available of what code you'll be running. Closing for now, but you're welcome back.
