### ISSUE TITLE
Earth system modeling

### ISSUE THREAD

**Issue by juliepullen** [cncf/cluster#43]
[CIL_proposal_pullen.pdf](https://github.com/cncf/cluster/files/1380677/CIL_proposal_pullen.pdf)

**Comment by juliepullen** [comment]
Sorry, my previous entry didn't include all the relevant info.

### First Name

Julie

### Last Name

Pullen

### Email

julie@theworldisyourocean.net

### Company/Organization

Stevens Institute of Technology

### Job Title

Associate Professor

### Project Title

Earth Systems Modeling

### Briefly describe the project

Overview: In our research, we work with coupled models to represent the air, ocean and
river domains for coastal urban applications at high resolution. We propose to use open
source containerized code for earth system prediction and document the performance
and benefits of cloud/edge computing in the realm of geophysical fluid dynamics. For
the model coupling we will utilize gRPC, a CNCF project.

Background: Some progress has been made in containerizing earth system tools. The
open source community atmospheric weather model, Weather Research & Forecasting
(WRF), has recently been [containerized](https://ral.ucar.edu/projects/ncar-docker-wrf) by National Center for Atmospheric Research
(NCAR) (Hacker et al., 2017) . We have already satisfactorily tested that container on
Google cloud and we are looking to work at a larger scale.

Approach: We will begin with containerized WRF and expand to work with or implement
a sea (model) container for ROMS (Regional Ocean Modeling System) and a river
(model) container for WRF-Hydro. All of these codes are open source community
models with no proprietary or sensitive data. To couple the model systems we will aim
to employ gRPC, an open source project hosted by CNCF. As a research entity we are
comfortable with varying load availability.

Outcomes: We will write a blog post documenting our novel experiment with CIL
resources for high resolution coupled air/sea/hydrology modeling. We also envision
producing several peer-reviewed papers from this effort in which we will credit the CIL
resources.

### Which members of the CNCF community and/or end-users would benefit from your work?

Improving earth systems modeling has benefits for science, including more accurate weather forecasting. Demonstrating WRF and coupled models on Kubernetes is an important new domain to demonstrate that cloud computing can compete with MPI. Model coupling is a new and exciting application for gRPC.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes: https://github.com/NCAR/container-wrf

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

We plan to start with 3 or 4 Type 1 machines to demonstrate working code. When it is working, we would like to scale up for short periods to hundreds of nodes. We'd also like to experiment with different machine types.

### What OS and networking are you planning to use (see: https://www.packet.net/bare-metal/)?

A recent Ubuntu.

### Please state your contributions to the open source community and any other relevant initiatives

I've published extensively regarding open source weather models such as COAMPS.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Showing that it works with weather, ocean and river modeling.

### Any other relevant details we should know about while preparing the infrastructure?

**Comment by atarfish9** [comment]
Closes #43

**Comment by taylorwaggoner** [comment]
Closes #43

**Comment by whatnick** [comment]
Is there any reporting on the outcomes of this project and if so we would like to reproduce this work on AWS.
