### ISSUE TITLE
Access to CNCF CIL

### ISSUE THREAD

**Issue by marcf5** [cncf/cluster#44]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### Project Title
Kubernetes in hybrid environments, please see https://kccncna17.sched.com/event/CU7L/kuberneters-in-hybrid-environments-using-cloud-interconnect-a-marc-chisinevski-f5-networks
 
### Which members of the CNCF community and/or end-users would benefit from your work?
Istio/Envoy/Kubernetes

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/F5Networks/k8s-bigip-ctlr/

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
Type 1E

### What OS and networking are you planning to use (see: https://www.packet.net/bare-metal/)?
Public Internet
### Please state your contributions to the open source community and any other relevant initiatives
https://sourceforge.net/projects/assetmng/files/assetmng/
https://sourceforge.net/projects/assetmng/files/assetmng/v1.0/Asset_Management_and_Risk_Assessment___Functional_and_Technical_Specifications___plus_Linux_installation.pdf/download

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
Ease migration to managed Kubernetes environements (Google Container Engine, Azure Container Services etc) and enabling hybrid deployments.

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
Hi marcf5 - a project has been created for this in Packet.  Closing #44.  Thanks!

**Comment by vielmetti** [comment]
No infrastructure was ever provisioned for this project, so it's been marked as complete and removed.
