### ISSUE TITLE
access to the CNCF CIL for Wekan

### ISSUE THREAD

**Issue by xet7** [cncf/cluster#45]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

### First Name

Lauri

### Last Name

Ojansivu

### Email

x@xet7.org

### Company/Organization

http://www.xet7.org/about-me

### Job Title

CEO of my one person company

### Project Title

Wekan

### Briefly describe the project

Open Source Trello-like kanban

### Which members of the CNCF community and/or end-users would benefit from your work?

All that want to self-host kanban board and have control of the data.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Website:
https://wekan.github.io

Repo:
https://github.com/wekan/wekan

MIT License:
https://github.com/wekan/wekan/blob/devel/LICENSE

Current platforms where Wekan runs:
https://github.com/wekan/wekan/wiki/Platforms

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

Servers at Europe, Amsterdam.

Type 3, Type 1E and Type 2A

1) Type 3:
- Trying to simulate and find fixes for [large scale usage](https://discourse.wekan.io/t/cpu-utilization-problems-with-large-userbase/579/4) to make Wekan more scaleable, for example by having [DTrace running on Triton](https://www.joyent.com/dtrace) on your provided hardware. Running Docker containers.

2) Type 1E:
- Trying to build Proxmox LXC version of Wekan. Wekan is usually built on Debian 8.9 or Ubuntu 14.04.

3) Type 2A:
- Trying to build ARM version of Wekan. Debian 8 or 9, depending what is available.

Other uses:
- Building VirtualBox images etc for Wekan releases, like I currently do on my laptop and have release at https://wekan.github.io
- Building and testing with crosscloud to multiple clouds
- Add more tests and have building for different platforms work for every new pull request and commit, having results integrated to GitHub
- Add more platforms and tests for them like Ubuntu LXD, install scripts to various operating systems

### What OS and networking are you planning to use (see: https://www.packet.net/bare-metal/)?

Internet.

### Please state your contributions to the open source community and any other relevant initiatives

I have 920 contributions to various repos at GitHub in the last year:
https://github.com/xet7

I'm maintainer of Wekan, 444 commits:
https://github.com/wekan/wekan/graphs/contributors

I have helped to keep Wekan alive, by continuing Wekan in a fork, and got a chance to merge it back:
https://github.com/wekan/wekan/wiki/FAQ#what-was-wekan-fork--wefork

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Wekan has many integrations coming with  [IFTTT with Huginn or Flogo](https://github.com/wekan/wekan/issues/1160), [Gogs git repo hosting](https://github.com/wekan/wekan/issues/253), etc at [Integrations wiki page](https://github.com/wekan/wekan/wiki/Integrations).

For these, advancement is in having Docker Compose script and other ways to orchestrate on various public and private cloud platforms, easy ways make more integrations, and easy deployment and management of Wekan and other integrated Open Source software.

Wekan wiki [press page](https://github.com/wekan/wekan/wiki/Press) has link to Hacker News article where someone did say that they use Wekan to store confidential patient data in Wekan, so Wekan is mission critical for some.

### Any other relevant details we should know about while preparing the infrastructure?

I have worked as SysAdmin and AWS Cloud Architect, so most things I could probably be able to setup myself, though help is very welcome, like in setting up Triton, Proxmox etc environments. If you have some example Terraform or Ansible scripts to help with setting up various different environments, it would help.

For Google Cloud, I currently don't know how to enable websockets so Wekan works. I also have not tried Wekan yet at Azure. More about this at [Platforms wiki page](https://github.com/wekan/wekan/wiki/Platforms).

**Comment by dankohn** [comment]
+1

**Comment by xet7** [comment]
@dankohn 

It would be nice to have at least ARM server for trying to build Wekan.

Wekan has already gained some performance fixes.

**Comment by dankohn** [comment]
Yes, we'll be setting up an account for you now. My sincere apologies for the long delay.

**Comment by taylorwaggoner** [comment]
Hi xet7 - a project has been created for Wekan in Packet.  Closing #45.  Thanks!

**Comment by xet7** [comment]
My blog post about Wekan progress on x64 and ARM:
https://news.ycombinator.com/item?id=16209090

**Comment by xet7** [comment]
I started x64 server. It's so nice how fast it compiles Wekan and Sandstorm compared to my laptop :+1: This really speeds up development :)

**Comment by xet7** [comment]
@dankohn @taylorwaggoner 

Wekan now works on arm64 server and RasPi3, I got it working finally !!!!

Install info, screenshots etc:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

Blog post here:
https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/index.html

Next I plan to add arm64 and other platforms to Wekan Snap and Docker.

Thanks to CNCF for making all this possible !!!

I also tweeted this: https://twitter.com/WekanApp/status/1145168007901134848

**Comment by jacobsmith928** [comment]
@xet7 I hope you're doing well and enjoying this infrastructure.  Can I request that you consolidate a bit, if possible?  Ideally the work you have on the m2.xlarge in AMS could be handled by one of the other machines you have.

@vielmetti @taylorwaggoner please review.

**Comment by xet7** [comment]
@jacobsmith928 

Yes, Wekan developent is going on full speed. Yes I can look at consolidating.

**Comment by xet7** [comment]
@jacobsmith928 

I did backup and delete m2.xlarge :)

**Comment by jeefy** [comment]
Hiya @xet7 et all. Due to Equinix hardware deprecations, the current machine you have (boards.wekan.team) is slated for deletion. Please ACK on this by **EOD Dec 16th** otherwise the machine may get automatically deleted. Thanks! cc @vielmetti

**Comment by xet7** [comment]
@jeefy 

Thanks a lot for info !! Are these deprecations for all of that machine type in same datacenter?

Anyway, I will backup, move to some other server, and delete that instance.

**Comment by vielmetti** [comment]
@xet7 - there are two systems in your project - one (arm.wekan.team) is in our DA11 new data center that is unchanged, the other (boards.wekan.team) is in our AMS1 data center that's being decommissioned.

The likely substitute data center as an exact match is the AM metro. We also do have several other new metros in Europe. (AM is overall the most appropriate for general use due to connectivity and system availability).

**Comment by xet7** [comment]
@jeefy @vielmetti 

I have now moved from AMS1 to AM and deleted AMS1 server.

**Comment by vielmetti** [comment]
Thank you @xet7 ! Appreciate it.

**Comment by jeefy** [comment]
Heya @xet7  -- Unfortunately we're now restricting our Equinix account to be CNCF projects only. Because of that, we need Wekan to remove their footprint out of Equinix by May 31th, 2024. Come Mid-June we will be deleting the resources and the accounts, so we don't want you to lose any data.

Happy to discuss further. Thanks!

cc @vielmetti

**Comment by xet7** [comment]
@jeefy @vielmetti

Is it possible to apply for WeKan to become CNCF project?

**Comment by xet7** [comment]
@jeefy @vielmetti

I did backup and delete all running 2 servers from Equinix Metal Console.

Done. Thanks!
