### ISSUE TITLE
Request for CNCF CIL

### ISSUE THREAD

**Issue by SomboChea** [cncf/cluster#47]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

**Comment by dankohn** [comment]
Hi, we'd be happy to work with students in Cambodia, but we need you to please fill out the rest of the application. What do you want to do with the hardware?

**Comment by SomboChea** [comment]
## Hardware Specs
CPU: Xeon
RAM: 16GB
OS: VMware ESXi 6.5
HDD: 2TB
Network: Fiber Optics (25MB/s)

**Comment by dankohn** [comment]
Sambo, please edit your original response above and add an answer after each question.

**Comment by dankohn** [comment]
Also, VMWare ESXi is closed source but we ask that you run open source software on these servers.

**Comment by dankohn** [comment]
Closing for now, but please feel free to reopen with more info.
