### ISSUE TITLE
Streamplace's request for CNCF CIL

### ISSUE THREAD

**Issue by iameli** [cncf/cluster#48]
### First Name

Eli

### Last Name

Mallon

### Email

eli@stream.place

### Company/Organization

Streamplace Inc.

### Job Title

CEO

### Project Title

Streamplace

### Briefly describe the project

We're working on a cloud native compositor for live video. The core of it is a WebGL video compositor. Surrounding that core are adapters for RTMP, WebRTC, and HLS/DASH.

The incubator analogy-pitch is something like "Wordpress for livestreams" or "running your own Twitch". But that's later. For now I'm focusing on getting reliable and straightforward infrastructure for broadcasting and transcoding live video on Kubernetes.

### Which members of the CNCF community and/or end-users would benefit from your work?

Any of the companies that process live video in a Kubernetes cluster. Looking over the list of CNCF members, that's more than a few.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yep, everything is Apache licensed. [https://github.com/streamplace/streamplace](https://github.com/streamplace/streamplace).

### What kind of machines and how many do you expect to use?

A few Type 1Es would be amazing — our biggest resource hog is bandwidth. Eventually we'll want to see how high we can dial up ffmpeg's quality settings on something like a Type 2, but that can happen later.

To be clear, we don't intend to host enormous public live video broadcasts on the CNCF servers. Our clusters will be transcoding the video and broadcasting them out to YouTube/Facebook Live/Twitch/Twitter/whatever. If we are hosting our own video publicly, we'll do so through a CDN.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

Container Linux Stable should be fine. Or whatever. Our current servers are running both Ubuntu and CentOS, so we're easy.

### Please state your contributions to the open source community and any other relevant initiatives

Sure — 

* I've [contributed a variety of patches to the kube-aws project](https://github.com/kubernetes-incubator/kube-aws/issues?utf8=%E2%9C%93&q=iameli) while working on setting up a HIPAA-compliant k8s cluster when I was at [C-SATS](http://www.csats.com/). 
* I wrote [(possibly) the first open-source script to automate retrieval of Let's Encrypt certs for Kubernetes ingresses](https://github.com/iameli/kubernetes-letsencrypt), since supplanted by the vastly superior [kube-lego](https://github.com/jetstack/kube-lego).
* [I livestream development of Streamplace twice a week](https://twitter.com/elimallon/status/930183218464034816), with a focus on answering questions for bootcamp students and other folks that are getting into the industry.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Do a Google search for any combination of the words "live video kubernetes" and you'll get no results relevant to that at all, save for @jbeda's excellent [TGI Kubernetes](https://www.youtube.com/channel/UCjQU5ZI2mHswy7OOsii_URg/videos) livestream. It gets worse with more specific terms, the [fifth result for "RTMP server Kubernetes" is my _npm_ account](https://twitter.com/elimallon/status/930183218464034816), so there's not a lot of resources out there for this sort of thing.

Streamplace is already publishing Helm charts for this sort of thing, including [an RTMP server](https://github.com/streamplace/streamplace/tree/master/packages/sp-rtmp-server) and [a TURN server for WebRTC](https://github.com/streamplace/streamplace/tree/master/packages/sp-coturn). I'd love to get all of that stuff polished enough to get into the main Charts repo.

### Any other relevant details we should know about while preparing the infrastructure?

Each stream involves realtime video transcoding and bandwidth up to ~50Mbps. Should be fine given the specs but it's potentially more bandwidth-intensive than most tenants.

**Comment by dankohn** [comment]
I love this use case. We'll try to get you set up quickly.

**Comment by iameli** [comment]
Amazing, thank you. Let me know if you need any other information.

**Comment by atarfish9** [comment]
Greetings iameli!   Thanks so much for your submission. We've just approved you through the Packet system.  

Cheers,
Annie Fisher
CNCF Program Manager

**Comment by atarfish9** [comment]
Close #48

**Comment by iameli** [comment]
Right on. Closing.

**Comment by jacobsmith928** [comment]
Hey @iameli hope you're doing well!  I see that you still have two servers (in Seattle) but the project hasn't seen any commits in well over a year and the website is down (https://stream.place/).  Good to reclaim this infrastructure?

@taylorwaggoner @vielmetti maybe re-open to track and close out.

**Comment by iameli** [comment]
Ah yes, totally fine to shut them down. Thanks again for the support!
