### ISSUE TITLE
CNCF Demo on ARM

### ISSUE THREAD

**Issue by bigeasy** [cncf/cluster#49]
### Name, email, company, job title

Alan Gutierrez ~ @bigeasy ~ hacker<br>
Cory Kaufman-Schofield ~ @allspiritseve ~ also hacker

### Project Title and description

[CNCF Demo on ARM](https://github.com/cncf/demo) ~ Get the CNCF demo applications working on ARM. Initiate a project to get the [CNCF stable of hosted projects](https://www.cncf.io/projects/) working on ARM using the CNCF demo application as a test bench. Begin by first getting the demo to work with the Packet infrastructure. This will create a patch to the demo where the AWS installation step can be replaced by a deployment Packet x86. Once working on x86 we can then begin to port the demo components to ARM on Packet peicemeal with integration testing aginst that x86 hosted components. The end result is a CNCF demo that can be hosted mix or match on x86 or ARM at Packet, verified function of the CNCF components on ARM, along with any insights gathered in porting CNCF's Go based components form x86 to ARM.

### Which members of the community would benefit from your work?

Anyone working with cloud native applications. The heart of CNCF is Kubernetes, so this will be a demonstration of the ability to host a constainer orchestration environment on ARM hardware. Specifically this will be an exercise of Kubernetes container orchestration and Prometheus container monitoring. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, the code will be 100% open source and submitted back into the CNCF demo.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

The project will need access to 3 machines for the x86 portion of the port, each with a minimum of 32 GB RAM. The Packet Type 1 server should be adequate to the task. Type 1 servers are hosted in data centers with the Packet Block Storage service so it would allow us to evaulate the use Kubernetes block storage plugin for Packet Block Storage. Upon completion of the x86 evaulation, a similar number of Type 2A servers will be required for the Arm portion of the effort.

**Comment by dankohn** [comment]
Hi, I appreciate the enthusiasm and would love to get your participation. However, CNCF is sunsetting the [demo](https://github.com/cncf/demo). Instead, we have redirected most of that work towards cross-cloud: https://github.com/cncf/cross-cloud/

Conveniently, the cross-cloud team was just gearing up to tackle ARM, and would likely be very happy to collaborate with you.

If you can email Lucina Stricko <lucina@vulk.coop> she can set up a call with the rest of the team.

**Comment by dankohn** [comment]
Closing for now, but please feel free to reopen with more info.
