### ISSUE TITLE
Documentation on cluster usage...

### ISSUE THREAD

**Issue by timothysc** [cncf/cluster#5]
Documentation on cluster usage should probably live here, I've been looking for it but have been unable to find it. 

/cc @rrati @jeremyeder

**Comment by bgrant0607** [comment]
+1. It's entirely unclear how one would make use of the cluster. How much work would it be? What environment is provided?

**Comment by jeremyeder** [comment]
Hmm, yes, Intel should provide a physical diagram.  As far as getting it up and running, we can contribute what we've learned as well since we've been hammering on it.

**Comment by timothysc** [comment]
We also clearly need a trouble-shooting guide :-(

**Comment by liljenstolpe** [comment]
I would agree.  I hate to say it but the question of "would you use it?" generally begs the questions "what is 'it'?" and "what can 'it' do?"  I'm pretty sure we could use it.  I'm less certain as to how it all works, and what is possible.  The docs don't have to be great, but basic level of what is available and how its consumed would be useful.

**Comment by lwr20** [comment]
And procedures for how one should book the cluster, guidelines on how requests will be judged by the cluster management team, etc. might be useful to increase the quality of requests and save everybody time.  Again - it wouldn't have to be great, just a few bullets to start with - can be refined later.

**Comment by cncfclusterteam** [comment]
Are the points mentioned above still valid? Documentation for the cluster was extended since then and the README + [the dedicated cluster page](https://www.cncf.io/cluster) provide a bit of data now but maybe we are missing something really important here.

**Comment by liljenstolpe** [comment]
I believe you are.  Basically the README and the dedicated page are just replicas of one another.  I have the node specifications, but that's about it.  That's not really enough, guys.  Willing to help, but there is no info to start with.

**Comment by africanzoe** [comment]
As per the CNCF site: "... Intel is deploying 1000 nodes at Switch,.." does Intel have at least the connectivity diagram? Or they are deploying nodes without connectivity?

**Comment by cncfclusterteam** [comment]
Is the not-so-recently-added [diagram](https://github.com/cncf/cluster/raw/master/cncf-network.png) enough for the basic network architecture?

**Comment by caniszczyk** [comment]
we have a whole new process now for this with CIL: https://www.cncf.io/community/infrastructure-lab/

closing this
