### ISSUE TITLE
Request for CIL access: Plushu / Plusku Sandbox

### ISSUE THREAD

**Issue by stuartpb** [cncf/cluster#52]
### Full Name

Stuart P. Bentley

### Email

s@stuartpb.com

### Company/Organization, Job Title

I don't really have one - I pretty much spin up a new GitHub organization for each project, so I guess that's my organization (so my org for this request would be Plushu), and my title / role would be Lead Maintainer?

### Project Title

Plushu

### Briefly describe the project

Plushu is a modular framework for building command-line interfaces, with an eye toward being used as the shell for a dedicated user on a dedicated server (ie. establishing a CLI for operating the server itself).

The Plusku ecosystem of Plushu modules uses Docker (with an eye toward Kubernetes, going forward) to build and run [Twelve-Factor Apps](https://12factor.net/), a la Heroku.

I currently have an open server where users can try this out running at sandbox.plushu.org (with the entry-point to submit a public key for access running at http://enter.sandbox.plushu.org), which is re-imaged daily via a Cron job on a remote machine. The Sandbox server itself is currently running on a Digital Ocean droplet I'm paying for out-of-pocket, and the cronjob is running on a Dreamhost server.

### Which members of the CNCF community and/or end-users would benefit from your work?

Anybody looking to self-host a Heroku-style build and deployment infrastructure for their app.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

- Everything in the Plushu project is up under https://github.com/plushu
- The script used to set up the sandbox is [here](https://github.com/plushu/build-sandbox/blob/master/build.sh)
- The script currently used to reset the sandbox on a timer is [here](https://github.com/plushu/build-sandbox/blob/master/watchdog/reset-plushu-sandbox.sh)
- The app used to restore the sandbox manually (technically not part of the Plushu project) is at https://github.com/stuartpb/reshotput

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

I would only use the tiniest tier of machine; I would probably be using at least three of them (one for the Pluahu Sandbox, one for the watchdog service, and one for experimentation), but not many more than that (and I could potentially work toward consolidating the Sandbox and the watchdog to one machine with two IPs, where one would be in use for the host environment and the other would point to the Sandbox VM).

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

The Plushu Sandbox will probably run on Ubuntu 16.04 (the current sandbox is running on 14.04, only because I haven't bothered to rebuild it since 2015). I would probably experiment with RancherOS and CoreOS as well.

If I go the sandbox-as-a-nested-VM route, I may use CentOS 7 as the host environment, with something like mist.io or oVirt to manage the VM.

### Please state your contributions to the open source community and any other relevant initiatives

All the work I do is open-source: some of my other big open source projects include the [Open Profilogical Web Survey](https://github.com/opws), the [Tabalanche](https://github.com/tabalanche) browser extension, and [CouchDB in a Hurry](https://github.com/stuartpb/couchdb-in-a-hurry).

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination)?

The Plusku ecosystem orchestrates containerized microservices (apps and addons), and working on it uncovers new ways to approach these concepts within the space of existing developer paradigms (ie. following the use patterns established by the Heroku Toolbelt).

### Any other relevant details we should know about while preparing the infrastructure?

Is it possible to get an IPv6 address space? That could be useful for a possible extension to the Sandbox where, instead of having one global sandbox shared by any prospective developers, each user could be given a separate VM (within which they can provision containers), with its own IPv6 address.

**Comment by dankohn** [comment]
LGTM. https://help.packet.net/faq/onboarding/networking

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
Closes #52

**Comment by vielmetti** [comment]
The Plushu project currently has two systems in use, 2x t1.small in SJC1.

Our SJC1 data center is going away, and our t1.small instance type is going away, so some kind of migration would be necessary if CNCF CIL support for this project is to continue.

In addition, one of the t1.small systems is running a very very old "Flatcar Edge" operating system, support for which is ending (in favor of our mainstream supported Flatcar Linux).

However, it would appear from a quick look at the Plushu project that development has essentially stopped since 2018. Since Plushu is not a CNCF project, it would make sense to bring CNCF CIL support for this effort to an end, rather than plan a migration task.

cc @stuartpb @jeefy @caniszczyk

**Comment by stuartpb** [comment]
If this is blocking something on your end, you can go ahead and shut it down; the Plushu project hasn't *strictly* ended, but the focus has shifted dramatically enough that I most likely wouldn't be reusing any of the pieces from 2018 when the time comes to revisit it (or, at least, not to the extent that migration would be easier than starting over from scratch).

**Comment by vielmetti** [comment]
Thanks @stuartpb ! The machines have been taken down, we're set here.
