### ISSUE TITLE
Access to CNCF CI for Jaeger

### ISSUE THREAD

**Issue by kevinearls** [cncf/cluster#53]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Kevin

### Last Name
EARLS

### Email
kearls@redhat.com

### Company/Organization
Red Hat

### Job Title
Senior Software Engineer in Test

### Project Title
Jaeger

### Briefly describe the project
Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system released as open source by Uber Technologies. It can be used for monitoring microservice-based architectures

### Which members of the CNCF community and/or end-users would benefit from your work?
The Jaeger team and anyone interested in distributed tracing

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes.  There are several projects involved:

The Jaeger server: https://github.com/jaegertracing/jaeger

Jaeger clients including https://github.com/jaegertracing/jaeger-client-java https://github.com/jaegertracing/jaeger-client-go etc.

OpenShift and Kubernetes templates:https://github.com/jaegertracing/jaeger-openshift and https://github.com/jaegertracing/jaeger-kubernetes

Opentracing-contrib code: https://github.com/opentracing-contrib

Some tests from: https://github.com/hawkular-qe including  https://github.com/Hawkular-QE/jaeger-instrumentation-performance-tests and https://github.com/Hawkular-QE/jaeger-java-test

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
We would like machines for several purposes

	1. A live demo instance of Jaeger along with a live instance of the Jaeger Hot Rod application  For this I think a type 0 node would suffice
	2. A Cassandra instance.  This will be used by the demos and by Travis tests.  For this we'd like a type 1 node.
	3. An OpenShift instance for testing, including testing of the Jaeger OpenShift templates.  For this we'd like 2 Type 1E  or type 1 nodes.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Most likely CentOS.

### Please state your contributions to the open source community and any other relevant initiatives
I have been contributing to the Open Source community for a number of years, starting when I joined FuseSource in 2012.  I am a committer on the Apache Camel project, and prior to starting work on Jaeger and OpenTracing I  made numerous contributions a number of other open source projects including Apache Camel, Hawtio, fabric8, karaf, and JBoss Fuse.  

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
This testing will contribute to the stability of Jaeger and advance the state of distributed tracing in the cloud.

### Any other relevant details we should know about while preparing the infrastructure?
Jaeger is a CNCF project.

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
Closes #53

**Comment by vielmetti** [comment]
The last servers in this project  were deleted in 2019; I've removed the rest of the project information from Equinix Metal.
