### ISSUE TITLE
CIL request for Flathub

### ISSUE THREAD

**Issue by ramcq** [cncf/cluster#56]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

### First Name

Robert

### Last Name

McQueen

### Email

rob@endlessm.com

### Company/Organization

Endless Computers / Flathub

### Job Title

VP of Deployment

### Project Title

Flathub

### Briefly describe the project

Flathub is a build and distribution service for containerized Linux desktop applications in the Flatpak format. We're looking to use CNCF infrastructure as a case study for dynamically scaling the build workers available to build/publish FOSS Linux desktop applications, and sharing technology and learnings between cloud and desktop containerization.

See https://flathub.org/ and https://flatpak.org/

### Which members of the CNCF community and/or end-users would benefit from your work?

Any user of Linux on the desktop benefits from the ease of distribution, robustness and security that's brought by containerized desktop applications as offered by Flatpak. Although decentralization is key to the Flatpak tools, to allow any Linux ISV to publish apps how they wish and be successful on their own terms, the success of the Flatpak format relies on users having a central go-to place for users to find top OSS and existing Linux desktop apps. Flathub serves that need so that there will be a receptive audience for ISVs to publish their applications in the Flatpak format. As well as bringing diversity and robustness to the Linux desktop ecosystem, the adoption and development of container tech on the desktop space provides additional use cases, functionality and testing of the underlying/shared stack that also powers cloud containers.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. Workers for the BuildBot instances run the configuration pushed from the master here: https://github.com/flathub/buildbot-config/

Builds are run in a sandbox set up by flatpak-builder and flatpak, both at https://github.com/flatpak/

We will flesh out the Ansible playbooks at https://github.com/flathub/ansible-playbook to handle automatic set-up of workers on the CNCF bare metal hosts.

Depending which Flatpak is being built, the different manifests can be found here: https://github.com/flathub/

Any non-OSS components which are included in Flatpaks are not built/downloaded/distributed by the Flathub infrastructure, but are downloaded on the end-user system as needed.

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

Initially, Type 0 and Type 2A as needed during times of peak demand when existing workers are all busy. Intel architecture workers are more needed at the moment. We would likely move to larger Intel nodes as needed rather than spawn multiple nodes.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

CentOS 7 is used for Flathub hosts and worker set-up will be automated with Ansible. We will set up a WireGuard VPN so that the bare metal hosts can communicate securely with the Flathub core infrastructure.

### Please state your contributions to the open source community and any other relevant initiatives

I've been working and contributing to Open Source projects for nearly 20 years, including Debian, freedesktop.org, GNOME and most recently Flatpak and Flathub where I am in charge of the infrastructure. I'm one of the original founders of Collabora, a leading worldwide OSS consultancy and worked there for 10 years as the CTO. I am experienced in contributing to and guiding OSS projects in solid technical directions which also successfully deliver the benefits of FOSS to commercial adopters and end-users.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Containerizing desktop applications allows developer workstations to be hardened through minimal/read-only root host OSes by removing risk and complexity into containers - the same benefits in robustness and management as containerizing cloud workloads.

The convergence of projects like Fedora/CentOS Atomic Host has taken this one step further, by sharing the same base OS and infrastructure between cloud and workstation use cases, you can bring the developer even closer to the production environment and easily test/run/develop infrastructure like Kubernetes alongside your desktop and development containers.

Core infrastructure such as the bubblewrap sandboxing tool and OStree system image management library are used by Flatpak and shared with Project Atomic.

### Any other relevant details we should know about while preparing the infrastructure?

Flatpak uses bubblewrap to set up the containers for the builds, which (on most kernels) requires a privileged helper to set up a new user namespace. Typical container infrastructure doesn't allow priveleged operations like this, meaning Flatpak builds would fail at present. We'd be interested in learning if we can use cloud tech such as Kubernetes to run the Flatpak builds containerized and integrate it with our infrastructure that way - it should make the management/provision of instances more standardised and portable - if we can understand/solve the privilege issue. It would be for "Version 2" of our setup.

**Comment by idvoretskyi** [comment]
@dankohn please, take a look.

**Comment by dankohn** [comment]
+1. @taylorwaggoner will get you set up.

**Comment by ramcq** [comment]
Great news, thanks @dankohn @idvoretskyi. Do you have any pointers about the nested containers thing? Anyone who's used bwrap inside a kubernetes container?

**Comment by dankohn** [comment]
@idvoretskyi can point you to the Slack channel where you have the best shot of getting an answer.

**Comment by taylorwaggoner** [comment]
@ramcq - I've set this project up in Packet and have sent you an invitation to join.  Let me know if you have any questions.

**Comment by idvoretskyi** [comment]
@ramcq no problem, feel free to DM me at https://cloud-native.slack.com.

**Comment by jacobsmith928** [comment]
@ramcq I wanted to check in on this request and ongoing usage.  Looks like you have a decent amount of infra (3x large x86 and 3x large Arm) and I wonder if anything can be consolidated.

@taylorwaggoner can you and @vielmetti please review as well?

**Comment by ramcq** [comment]
@jacobsmith928 One of the large x86 is a test system we can decommission for the time being, the others are all in a pool for builds for https://flathub.org/builds/#/workers. I think we could take one of the ARM builders off and see whether we can keep up with 2x2 - would that be OK?

\cc @barthalion @alexlarsson

**Comment by barthalion** [comment]
I have deleted 1x t1.small.x86, 1x c1.large.arm.xda and 1x m1.xlarge.x86.

**Comment by jacobsmith928** [comment]
Great tahnks @barthalion - appreciate it!

**Comment by barthalion** [comment]
Hey @jacobsmith928, would it be a problem if we add one c1.large.arm in AMS? I suspect our main load balancers hosted elsewhere are overloaded which causes increased 503 error rate, I'd like to check if it gets any better if we add new server to the pool.

**Comment by jacobsmith928** [comment]
@vielmetti can you please coordinate as you see fit?

**Comment by vielmetti** [comment]
Hi @barthalion - have added a c1.large.arm reserved server in our AMS1 facility. You'll want to provision it per our reserved hardware setup info:

https://www.packet.com/developers/docs/getting-started/deployment-options/reserved-hardware/

**Comment by barthalion** [comment]
Thanks a lot!

**Comment by barthalion** [comment]
Hi @vielmetti, our load balancers have been upgraded to use proper SSDs and the performance issues are gone now, so the c1.large.arm machine can be reclaimed. Thanks again!

**Comment by vielmetti** [comment]
Thanks @barthalion - that system has now been reclaimed.

**Comment by barthalion** [comment]
Hey @vielmetti, any idea what has happened to sources.flathub.org? It hasn't been actively used lately, but it was definitely up, but I can't find it in Equinix Metal dashboard anymore.
