### ISSUE TITLE
CNCF Marketing Demo

### ISSUE THREAD

**Issue by caniszczyk** [cncf/cluster#6]
If you are interested in filing a request for access to the CNCF Community Cluster, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.
### First Name

Chris
### Last Name

Aniszczyk 
### Email

cra@linuxfoundation.org
### Company/Organization

Linux Foundation / CNCF
### Job Title

VP / COO
### Project Title

CNCF Marketing Demo (using Boinc)
### What existing problem or community challenge does this work address? ( Please include any past experience or lessons learned )

Builds a canonical marketing demo using CNCF technology
### Briefly describe the project

Builds a canonical marketing demo using CNCF technology
### Do you intend to measure specific metrics during the work? Please describe briefly

Application performance
### Which members of community and/or end-users would benefit from your work?

All of the CNCF community looking to learn how to build a non-trivial CNCF application
### Do you commit to publishing your results and upstreaming the open source code resulting from your work? Do you agree to this within 2 months of cluster use?

Everything will be open source from day 1 
### Are there identified risks which would prevent you from achieving significant results in the project ?

Nope 
### Have you requested CNCF cluster resources or access in the past? If ‘no’, please skip questions 2 through 4.

No
### Please list project titles associated with prior CNCF cluster usage.

N/A
### Please list contributions to open source initiatives for projects listed in question 2. If you did not upstream the results of the open source initiative in any of the projects, please explain why.

N/A
### Have you ever been denied usage of the cluster in the past? If so, please explain why.

N/A
### Please state your contributions to the open source community and any other relevant initiatives

N/A
### Number of nodes requested (minimum 20 nodes, maximum 500 nodes). In Q3, maximum increases to 1000 nodes.

20
### Duration of request (minimum 24 hours)

A couple of weeks to start, may request permanent access
### With or Without an operating system (Restricted to CNCF pre-defined OS and versions)?

With
### Any other relevant details we should know about while preparing the infrastructure?

We are CNCF staff :)

**Comment by cncfclusterteam** [comment]
This issue has been reopened to better show the current status of an associated request - "In progress" should show that the nodes are still used by the requester.

**Comment by caniszczyk** [comment]
closing as this happened + we have a new process
https://www.cncf.io/community/infrastructure-lab/
