### ISSUE TITLE
application for cluster access

### ISSUE THREAD

**Issue by fallenangel3k** [cncf/cluster#64]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Fidschi 

### Last Name
Meuer

### Email
fm2204@email.vccs.edu

### Company/Organization
Virginia's Community Colleges

### Job Title
Student

### Project Title
Multipurpose Unified Hashing   (development of)

### Briefly describe the project
today much computing power is wasted for different hashing algos only do one thing, this project is about to find a way to do useful work for multiple projects instead random numbers without a mean for any other project

### Which members of the CNCF community and/or end-users would benefit from your work?
everybody interessted

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
code will be released on GitHub

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
The project calls for two 4-node-clusters, one with mainly CPU power, one with mainly GPU power:
x1.small and c1.xlarge.x86

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
CentOS7

### Please state your contributions to the open source community and any other relevant initiatives
today much computing power is wasted for different hashing algos only do one thing, this project is about to find a way to do useful work for multiple projects instead random numbers without a mean for any other project

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
find right mix between memory, cpu and gpu; optimized codes

### Any other relevant details we should know about while preparing the infrastructure?
access to smaller or larger or different cluster is fine; the project is in the beginning still

best regards,

Fidschi Meuer

**Comment by dankohn** [comment]
Please developer your software locally and then open a new request when you're ready to test it at scale.
