### ISSUE TITLE
Requesting Cluster Computing Access for Academic Project

### ISSUE THREAD

**Issue by cksajil** [cncf/cluster#65]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Sajil

### Last Name
C. K.

### Email
sajilck@gmail.com
sajilckdcb@keralauniversity.ac.in

### Company/Organization
University of Kerala, India

### Job Title
Research Scholar

### Project Title
Phylogenetic Analysis 

### Briefly describe the project
This is an academic research project to study the evolutionary analysis of important genes in angiogenesis process. Angiogenesis is the process of formation of new blood vessels from pre-existing ones in the living organisms.

### Which members of the CNCF community and/or end-users would benefit from your work?
Anyone interested. The findings will push forward the existing scientific knowledge in the field of Angiogenesis. This could throw light into the process of when and where the genes emerged in the evolutionary history of life.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes. RAxML (https://sco.h-its.org/exelixis/web/software/raxml/). Source Code (https://github.com/stamatak/standard-RAxML)

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
We would like to get 100 cores with moderate RAM support and we expect the program to complete in a couple of days or almost one week.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
We would love to get Ubuntu 14.04 LTS but any Linux version is fine

### Please state your contributions to the open source community and any other relevant initiatives
I am a open source contributor in the beginning stage. I have made all of my research codes reproducible but sharing it via GitHub (please see https://github.com/cksajil/ancram for a recent contribution). I could make some tiny contributions to other GitHub projects also.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
This would bring clarity into the computing resource requirements of RAxML for various gene sizes. It could lead us to develop certain guidelines on efficient usage of RAxML for a given computing configuration.

### Any other relevant details we should know about while preparing the infrastructure?
RAxML requires MPI standard for parallelization. A detailed documentation of the setup can be found at https://sco.h-its.org/exelixis/web/software/raxml/cluster.html

**Comment by dankohn** [comment]
Approved, thanks.

We'd love to see you containize the RAxML code and show it running on Kubernetes, if feasible.

**Comment by cksajil** [comment]
Sure. Thank you so much.

**Comment by taylorwaggoner** [comment]
@cksajil I have sent an invitation to your Gmail account from Packet.  Please let me know if you have any questions!

**Comment by cksajil** [comment]
@taylorwaggoner  I followed the instructions as per the tutorial here (https://help.packet.net/technical/infrastructure/ssh-access). I could generate the key and add it to the packet site. I couldn't follow the last step here 

"Now that you that the key is added in portal, you need to force add it to your server(s). 
Use our SOS service to login with (root + pw) and manually add the new key on the authorized_keys file."

I could log in using the SOS service but don't know how to manually add the new key on the authorized_keys file. How can I do the same?. I tried log in using the ssh, but getting an error like:

Permission denied (publickey).

Please help me on this.

**Comment by cksajil** [comment]
@taylorwaggoner I solved it. I could add the key to authorized_keys file and log in. Thanks :-)))

**Comment by vielmetti** [comment]
Can we get a status update on this project, @cksajil ? I see a system still in use running a very old operating system (Ubuntu 14.04) which is no longer supported.

**Comment by cksajil** [comment]
You may shutdown the project. Thanks for reaching out. Thanks for
the support.

**Comment by vielmetti** [comment]
Thanks! One last machine was turned back to the pool, and the project is closed out.
