### ISSUE TITLE
CIL request for Linkerd

### ISSUE THREAD

**Issue by dadjeibaah** [cncf/cluster#66]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Dennis

### Last Name
Adjei-Baah

### Email
dennis@buoyant.io

### Company/Organization
Buoyant Inc

### Job Title
Software Engineer

### Project Title
Linkerd

### Briefly describe the project
Linkerd is a service mesh and a CNCF project. We are interested in using CNCF’s infrastructure Lab for our integration tests and bug reproduction environment. (Until now, these integration tests have been run in proprietary setups.)

### Which members of the CNCF community and/or end-users would benefit from your work?
All Linkerd users.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes. https://linkerd.io/
https://github.com/linkerd/linkerd

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
3 c1.small.x86

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Container Linux by CoreOS - Stable

### Please state your contributions to the open source community and any other relevant initiatives
I am a software engineer at Buoyant. Buoyant is the primary sponsor of Linkerd, an open source product.

### How will this testing advance cloud-native computing (specifically containerization, orchestration, microservices or some combination).

Linkerd is a CNCF project and a critical part of many production cloud-native architectures. Integration testing for Linkerd will benefit everyone who uses or plans to use, Linkerd.

### Any other relevant details we should know about while preparing the infrastructure?

Most of our integration tests assume a  working k8s cluster. We understand that Packet provides the bare-metal infrastructure. We would love you hear any suggestions on how we can quickly and easily set up and manage a k8s cluster.

**Comment by jacobsmith928** [comment]
@dadjeibaah Great request!  I'm with Packet - will let CNCF respond and get things setup, then happy to help with some k8s options in addition to whatever they can provide.

**Comment by dankohn** [comment]
@taylorwaggoner Will set you up.

**Comment by taylorwaggoner** [comment]
@dadjeibaah - I've set up the project in Packet and sent you an invitation to join.  Please let me know if you have any questions!

**Comment by taylorwaggoner** [comment]
@dadjeibaah - We noticed that you have 51 active devices, so wanted to check in to see what your plans are for this project. Thanks!

**Comment by dadjeibaah** [comment]
@taylorwaggoner, we have been running some benchmark tests for Linkerd for the past couple of weeks. We are at the tail end of the tests and we should have things wrapped up by next week and should be scaling down those devices then.

**Comment by taylorwaggoner** [comment]
@dadjeibaah great, thank you for the update!
