### ISSUE TITLE
Request for 1 Baremetal server for running k8s-code.appspot.com

### ISSUE THREAD

**Issue by dims** [cncf/cluster#67]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

**Comment by dankohn** [comment]
Approved, thanks. Taylor will get you the login info within a week. I would appreciate if you could create a branch or new repo where you include all of the code you're using for the server.

**Comment by taylorwaggoner** [comment]
@dims - I sent you an invitation from Packet.  Please let me know if you have any questions!

**Comment by vielmetti** [comment]
This code is now running at https://cs.k8s.io - thanks @dims !

A recent update put this on a new box.

https://twitter.com/dims/status/1326879034484150276

**Comment by vielmetti** [comment]
The code that's running is the code search engine Hound, https://github.com/hound-search/hound originally from Etsy.
