### ISSUE TITLE
Add new user to the Linkerd Packet project

### ISSUE THREAD

**Issue by siggy** [cncf/cluster#68]
**Note**: This is a request to add my user to the existing Linkerd project on Packet, which was already set up via #66. If this is something we can do ourselves, let me know.

---

If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name

Andrew

### Last Name

Seigner

### Email

siggy@buoyant.io

### Company/Organization

Buoyant Inc

### Job Title

Software Engineer

### Project Title

Linkerd

### Briefly describe the project

Linkerd is a service mesh and a CNCF project. We are interested in using CNCF’s infrastructure Lab for our integration tests and bug reproduction environment. (Until now, these integration tests have been run in proprietary setups.)

### Which members of the CNCF community and/or end-users would benefit from your work?

All Linkerd users.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. https://linkerd.io/
https://github.com/linkerd/linkerd

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

3 c1.small.x86

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

Container Linux by CoreOS - Stable

### Please state your contributions to the open source community and any other relevant initiatives

I am a software engineer at Buoyant. Buoyant is the primary sponsor of Linkerd, an open source product.

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).

Linkerd is a CNCF project and a critical part of many production cloud-native architectures. Integration testing for Linkerd will benefit everyone who uses or plans to use, Linkerd.

### Any other relevant details we should know about while preparing the infrastructure?

Most of our integration tests assume a working k8s cluster. We understand that Packet provides the bare-metal infrastructure. We would love you hear any suggestions on how we can quickly and easily set up and manage a k8s cluster.

**Comment by taylorwaggoner** [comment]
@siggy - I've sent you an invitation to join from Packet. Thanks!

**Comment by siggy** [comment]
Thanks @taylorwaggoner !
