### ISSUE TITLE
LLVM Compiler - Permission to access cluster for open source development

### ISSUE THREAD

**Issue by jbhateja** [cncf/cluster#70]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### Which members of the CNCF community and/or end-users would benefit from your work?
LLVM is widely used across industries and academia.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/llvm-mirror/llvm

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
X86_64 based machines haswell and higher microarchitectures.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Linux

### Please state your contributions to the open source community and any other relevant initiatives
https://reviews.llvm.org/p/jbhateja/

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
Main usage is for build and running performance regression (lnt), these activities are compute intensive.

### Any other relevant details we should know about while preparing the infrastructure?
Noting in particular.

**Comment by dankohn** [comment]
Sorry that I missed this. +1, but please let us know if you need more than a few servers.

**Comment by taylorwaggoner** [comment]
@jbhateja, I have sent you an invitation email from Packet.  Please let us know if you have any questions!

**Comment by vielmetti** [comment]
The "LLVM Compiler" project was never used; it has now been removed.
