### ISSUE TITLE
Request to access CNCF Packet Cluster

### ISSUE THREAD

**Issue by jeefy** [cncf/cluster#71]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

### First Name
Jeffrey
### Last Name
Sica
### Email
jsica@umich.edu
### Company/Organization
University of Michigan
### Job Title
Research Database Administrator Senior
### Project Title
Kubernetes Integrations / Bugfixes
### Briefly describe the project
Doing a bunch of Kubernetes development and E2E testing and would like to not use my laptop. Currently takes ~25min on my laptop, and ~10min on GCP.
### Which members of the CNCF community and/or end-users would benefit from your work?
Immediately, Kubernetes
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/kubernetes
### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
c2.medium.x86
c1.large.arm

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Ubuntu primarily

### Please state your contributions to the open source community and any other relevant initiatives
https://github.com/jeefy/

### How will this testing advance cloud native computing (specifically containerization, orchestration, microservices or some combination).
It will drastically speed up testing and development for me :)

### Any other relevant details we should know about while preparing the infrastructure?
None that I can think of. Thanks!

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
@jeefy - I sent you an invitation from Packet.  Thanks!

**Comment by vielmetti** [comment]
The bugs have been fixed and this project is complete; deleting it from Equinix Metal.
