### ISSUE TITLE
Request access for Network Service Mesh

### ISSUE THREAD

**Issue by fkautz** [cncf/cluster#73]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Frederick

### Last Name
Kautz

### Email
fkautz@redhat.com

### Company/Organization
Red Hat

### Job Title
Principal Software Engineer

### Project Title
Network Service Mesh

### Briefly describe the project
 Network Service Mesh is a novel approach to solving the more complicated L2/L3 use cases in Kubernetes that are tricky to address with the existing Kubernetes Network Model by taking inspiration from the work in Istio Service Mesh and mapping them to L2/L3 payloads.

### Which members of the CNCF community and/or end-users would benefit from your work?
* Telcos
* SDN providers who wish to support NFV and other robust and multifaceted k8s networking use cases
* Internet Service Providers
* Advanced enterprise customers
* Kubernetes NFV users
* Users with esoteric network protocols wishing to use kubernetes

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
The code is 100% open source.

https://github.com/ligato/networkservicemesh

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
Start with a cluster of size 3 for Continuous Integration and Integration Tests.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Testing on:
CentOS 7
Ubuntu 16.04
Ubuntu 18.04 LTS
OpenSUSE 14.03

### Please state your contributions to the open source community and any other relevant initiatives
* Co-founder, co-organizer and committer of Network Service Mesh.
* Co-founder and committer of the ODL Container Orchestration Engine (CNI driver)
* Former Docker contributor (had commit access before docker was publicly released)

Also, please take my colleague and project co-founder, Ed Warnicke's contributions and initiatives into consideration.

* Technical Steering Committee Chair of FD.io, parent project of VPP.
* Former TSC member of ODL
* Former TSC member of ONAP

### How will this testing advance cloud-native computing (specifically containerization, orchestration, microservices or some combination).
If Network Service Mesh is successful, we will have containerized, highly scalable cloud-native VNF and NFV applications being serviced by Kubernetes.

### Any other relevant details we should know about while preparing the infrastructure?
Access to DPDK enabled NICs is highly desirable. Existing Mellanox ConnectX-4 should be ok, but would strongly prefer Mellanox ConnectX-5 which are *highly* popular with Telco deployments.

Multi-NIC systems are also highly desirable.

**Comment by dankohn** [comment]
+1

**Comment by edwarnicke** [comment]
Question: Is it possible to get access to multi-NIC systems?

**Comment by fkautz** [comment]
I've updated the request to include multiple distros:

CentOS
Ubuntu 16.04
Ubuntu 18.04
OpenSUSE 14.03

My understanding is that packet makes it trivial to reimage a system, so this should be relatively easy to support without increasing the need for additional hardware substantially.

**Comment by fkautz** [comment]
I've added a line about multi-nic systems being desirable.

**Comment by vielmetti** [comment]
Looking forward to working with you on this!

**Comment by taylorwaggoner** [comment]
Hi @fkautz - I have created a project for you in Packet and have sent you an invitation.  If others should be added to the project, please send me their email addresses.  Thanks!
