### ISSUE TITLE
bhuvaneswar-CNCF

### ISSUE THREAD

**Issue by bhuvaneswar370** [cncf/cluster#74]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

### First Name
Bhuvaneswar
### Last Name
Reddy
### Email
bhuvaneswar0370@gmail.com
### Company/Organization
DevOps Enabler
### Job Title
DevOps Associate
### Project Title
Learning
### Briefly describe the project
Learning on how kubernetes works
### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
centos with 4 machine
### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
centos

**Comment by dankohn** [comment]
Sorry, we're looking to support the development of specific open source projects here. Please learn Kubernetes on your machine (perhaps using Minikibe or Docker), and consider making a request here when you have specific software on GitHub you're looking to improve.
