### ISSUE TITLE
kube-arbitrator - Request access for kubernetes

### ISSUE THREAD

**Issue by tossmilestone** [cncf/cluster#78]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Xiaoxi He
### Email
xxhe@alauda.io
### Company/Organization
Alauda
### Job Title
Software Engineer
### Project Title
kube-arbitrator
### Briefly describe the project
kube-arbitrator is batch system built on Kubernetes, providing mechanisms for the applications which would like to run batch jobs in Kubernetes.
### Which members of the CNCF community and/or end-users would benefit from your work?
kubernetes
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
Yes. https://github.com/kubernetes-incubator/kube-arbitrator
### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
c1.xlarge.x86 - 2
x1.small.x86 - 2
### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
CentOS
Flannel
### Please state your contributions to the open source community and any other relevant initiatives
- Kubernetes
   * Enable golinting for kubenetes scheduler packages
   * Avoid race condition when updating equivalence cache
   * Reuse the `min*Nodes` slices in order to save GC time
   * Add strategy description for 'kubectl describe sts' command 
### Any other relevant details we should know about?
The cluster will be used for testing with the kube-arbitrator on my contributions.

**Comment by dankohn** [comment]
+1

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by tossmilestone** [comment]
@taylorwaggoner hi, I just want to know when I can have the clusters? Thanks in advance!

**Comment by dankohn** [comment]
She should be able to get your account Monday. Thanks.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by taylorwaggoner** [comment]
@tossmilestone I have sent you an email invitation from Packet.  Thanks!

**Comment by jacobsmith928** [comment]
@tossmilestone I wanted to followup on this project as the original request was for a small number of machines (3) and I see you're using 14 large machines include 4x GPU's.  Can you please reduce your usage to the original scope and please provide an update on the project?

@taylorwaggoner @vielmetti please review.

**Comment by tossmilestone** [comment]
@jacobsmith928 OK，I will reduce the usage to free the machines

**Comment by vielmetti** [comment]
@tossmilestone

**Comment by tossmilestone** [comment]
@vielmetti 
I have reduced the usage, please check it again. Thanks!

**Comment by vielmetti** [comment]
Thanks! Closing this ticket again.

**Comment by vielmetti** [comment]
Hello @tossmilestone  -

Your current configuration has 2 x1.small systems in our "hkg1" data center, which we are planning to close. We're evaluating alternative data centers to provide you with similar systems. 

My assumption is that a location in Asia-Pacific would be best and that a second choice is western US (you have systems in Tokyo and in Silicon Valley right now) - any guidance as to your preferences would be welcome as we make plans.

thanks

Ed

**Comment by tossmilestone** [comment]
@vielmetti I am ok with the Tokyo region. I will start the migration soon. Thanks!

**Comment by tossmilestone** [comment]
@vielmetti the migration has been done.

**Comment by vielmetti** [comment]
Thanks @tossmilestone !

**Comment by vielmetti** [comment]
@tossmilestone @jeefy 

Another data center migration request for you.

We are closing our NRT1 and SJC1 data centers. Your current configuration has two systems in NRT1 and one in SJC1, so the request is to rebuild the entire infrastructure. 

Our capacity dashboard should help you figure out a good location https://deploy.equinix.com/developers/capacity-dashboard/ for your needs - compared to the last time we did this, there are quite a few more available data centers to pick from. You'll want to select an instance with a capacity marked "high" for best results. Let me know if you need help with system picking. Our current APAC data centers are Hong Kong, Sydney, Seoul, Tokyo, and Singapore.

**Comment by vielmetti** [comment]
@tossmilestone Thanks for taking care of this! Marking this as complete.
