### ISSUE TITLE
helm chart for kubernets

### ISSUE THREAD

**Issue by huanghuangzym** [cncf/cluster#79]
If you are interested in filing a request for access to the CNCF CIL, please fill out the details below.

If you are just filing an issue, ignore/delete those fields and file your issue.

First Name

li

Last Name

huang

Email

lihuang@alauda.io

Company/Organization

Alauda

Job Title

Software Engineer

Project Title

helm/charts

Briefly describe the project

Use this repository to submit official Charts for Kubernetes Helm. Charts are curated application definitions for Kubernetes Helm. For more information about installing and using Helm, see its README.md. To get a quick introduction to Charts see this chart document.

Which members of the CNCF community and/or end-users would benefit from your work?

Helm charts and Kubernetes users

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

yes 100% open source.
https://github.com/helm/charts

What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

t1.small.x86 -3

What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

Debian 8
CentOS/RHEL 7
OpenSuse 14.03
Ubuntu 16.04 LTS
Container Linux by CoreOS
Fedora/CentOS Atomic

Please state your contributions to the open source community and any other relevant initiatives

make more apps in chart ,tu run in kubernets

Any other relevant details we should know about while preparing the infrastructure?

**Comment by dankohn** [comment]
Sorry, this isn't detailed enough. Could you please start again with a new issue and explain what you want to do.
