### ISSUE TITLE
Request access for kubeflow

### ISSUE THREAD

**Issue by zlcnju** [cncf/cluster#80]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Licheng.Zhu

### Email
zlcnju@gmail.com

### Company/Organization
Alauda

### Job Title
Software Engineer

### Project Title
kubeflow

### Briefly describe the project
The Kubeflow project is dedicated to making deployments of machine learning (ML) workflows on Kubernetes simple, portable and scalable. Our goal is not to recreate other services, but to provide a straightforward way to deploy best-of-breed open-source systems for ML to diverse infrastructures. Anywhere you are running Kubernetes, you should be able to run Kubeflow

### Which members of the CNCF community and/or end-users would benefit from your work?
kubeflow/tensorflow users

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
yes, 100% open source
https://github.com/kubeflow/kubeflow

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
x1.small.x86 -2

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
CentOS/RHEL 7
Ubuntu 16.04 LTS

### Please state your contributions to the open source community and any other relevant initiatives
- Make kubeflow a simple tool to deploy tensorflow
- provide a more convenient way to run tensorflow job on the distributed system

**Comment by dankohn** [comment]
Can you please provide some detail as what you want to do with Tensorflow.
Are you an existing contributor to the project?

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by zlcnju** [comment]
I want to deploy tensorflow on the k8s clusters, what i focus is how to make the tensorflow deployment easier,  and try to give a efficient and convenient way for the publish of tensorflow model. I have make effort about the whole process， but i don't have enough resource to test the distributed job on the k8s, so  i want to request some machine to keep my test moving.
And I have to say I am new to the kubeflow project.

**Comment by zlcnju** [comment]
I want to deploy tensorflow on the k8s clusters, what i focus is how to make the tensorflow deployment easier,  and try to give a efficient and convenient way for the publish of tensorflow model. I have make effort about the whole process， but i don't have enough resource to test the distributed job on the k8s, so  i want to request some machine to keep my test moving.
And I have to say I am new to the kubeflow project.

**Comment by dankohn** [comment]
Unfortunately, I need to turn down your request for now, until you have a more concrete development plan. The cluster is for developers working to improve open source software, not just for those getting it running (although the latter is almost always the first step of the former).

Cc @aronchick who may have access to other resources for those in China wanting to use Kubeflow.

**Comment by aronchick** [comment]
@zlcnju can you help me understand what you're looking to do? If you just need a free cluster, you could create a 1 node f1-micro on Google Cloud (where I work). Happy to help! (you can email me to follow up at aronchick (at) google (dot) com.
