### ISSUE TITLE
Request access: puppet-kubernetes module playground

### ISSUE THREAD

**Issue by Andor** [cncf/cluster#81]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Andrew N Golovkov

### Email
andrew.golovkov@gmail.com

### Company/Organization
Ozon.ru

### Job Title
Senior System Engineer

### Project Title
Puppet Kubernetes Module.

### Briefly describe the project
Make reliable kubernetes bare metal deployment with Puppet.

### Which members of the CNCF community and/or end-users would benefit from your work?
Any bare metal user can achieve benefit if he is using Puppet.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
The project is not in opensource yet, but we have a plan to publish it.

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
At least 5 instances, any type, prefer x86 for start.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Ubuntu 18.04, and will test other Linux distributions as well.

### Please state your contributions to the open source community and any other relevant initiatives
I made some Puppet modules and contribute to many of them.

### Any other relevant details we should know about?
I don't need 100% uptime for hosts, only when I or my colleagues really will work on it.

**Comment by dankohn** [comment]
Thanks for the application. Please open source the modules first and then reapply. Also, please think about integrating with this work: https://github.com/puppetlabs/puppetlabs-kubernetes

**Comment by Andor** [comment]
@dankohn Yeah, our work is based on the upstream module and we will contribute to it.
Currently, our work is in private forks of the puppetlabs's official module.

**Comment by dankohn** [comment]
Could you please open source your fork and then we're happy to approve.

**Comment by Andor** [comment]
@dankohn yeah, sure. Will do it today.
