### ISSUE TITLE
OpenShift 3.10 +OpenStack 13 with Ceph and Gluster

### ISSUE THREAD

**Issue by santiagoangel** [cncf/cluster#82]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Santiago Angel
### Email
santiagoangel@redhat.com
### Company/Organization
Red Hat
### Job Title
Middleware Solutions Architect
### Project Title
OpenShift 3.10 +OpenStack 13 with Ceph and Gluster
### Briefly describe the project
run OpenShift 3.10 on top of OpenStack 13 with Ceph and Gluster storage over it.
### Which members of the CNCF community and/or end-users would benefit from your work?
Gluster community
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/gluster/gluster-kubernetes

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
50 machines to test Gluster integration on specific version (13) of OpenStack

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Centos 7/RHEL 7.5

### Please state your contributions to the open source community and any other relevant initiatives
I contribute to open source promotion and education in Mexico

**Comment by dankohn** [comment]
We'd like to support you on this, but 50 machines is a huge request, and you didn't lay out a project plan or describe your association with gluster-kubernetes. Can you please add additional detail.

**Comment by santiagoangel** [comment]
Hello Dan, I want to test the case when Gluster is installed in converged mode in OpenShift Nodes and those nodes are virtual ones provided by OpenStack. I'm think 50 is a huge number but I want to check Gluster performance in this scenarios: HA metrics, HA logging, CI / CD nodes, with internal registry, with Quay registry and with 2000 apps load in application nodes. As a minimal setup i count 3 virtual node for OpenShift Masters, 3 for infra, 3 for metrics, 3 for logging, 3 for CI/CD, 3 for Quay and 8 for Apps, 3 for load balancer and 1 for bastion host with a total of 30 virtual nodes.

**Comment by dankohn** [comment]
@vielmetti and @jacobsmith928 This sounds like an intriguing use of Packet but is probably too much for CNCF's allocation. Would Packet be open to supporting @santiagoangel (or upping CNCF's allotment for the course of his experiment)?

**Comment by jacobsmith928** [comment]
@dankohn and @santiagoangel we'll need to coordinate to ensure available resources, but otherwise we'd be more than happy to increase the CNCF's allotment for the experiment. Feel free to move the request forward.  Thanks!

**Comment by dankohn** [comment]
+1

**Comment by taylorwaggoner** [comment]
@santiagoangel, I have sent you an invitation from Packet for the OpenShift 3.10 +OpenStack 13 with Ceph and Gluster project.  Thanks!

**Comment by vielmetti** [comment]
Has this project completed? It looks like 2 of the servers allocated to it were never turned down.

**Comment by vielmetti** [comment]
This project has been completed, and all of the associated infrastructure has been turned down. If there's a need for additional infrastructure to accommodate a new project, please open up a new issue. thanks!
