### ISSUE TITLE
Kubernetes & Redhat OKD Cluster Hosting Services - Stackhatch, Inc (Container Stack Packaging)

### ISSUE THREAD

**Issue by jbanimineni** [cncf/cluster#84]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name

JayaBabu Animineni

### Email

jbanimineni@stackhatch.org

### Company/Organization

Stackhatch, Inc (https://stackhatch.org)

### Job Title

Founder & Architect

### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)

Container Stack Packaging

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Stackhatch, Inc has automated the ability to build, package, deploy, monitor and maintain applications, lowering the barrier to adoption for anyone to deploy and maintain a full spectrum of server applications in any cloud environment. For this we require multiple architecture servers to test docker images and to host Kubernetes & Redhat OKD Cluster container platforms.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?

Yes. 100% open source, Apache2.0
Project URL:  https://gitlab.com/stackhatch/container-stack-packaging
Gitlab Org URL: https://gitlab.com/stackhatch (We got the Gitlab Gold plan for our organisation)

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

t1.small.x86 - 2
x1.small.x86 - 5

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?

CentOS7

### Any other relevant details we should know about?

We would like to host, manage & orchestrate kubernetes cluster and Redhat OKD Platform in bare metal servers and providing the infrastructure for open source developers & entrepreneurs to develop, build and deploy their applications on containers platform using *Container Stack Packaging*. We will maintain all docker stack images up to date and will monitor & support kubernetes & Redhat OKD cluster platform with latest updates.

**Comment by dankohn** [comment]
+1

**Comment by jbanimineni** [comment]
How many days it would take to approve our request?

@dankohn,  may I know the meaning of +1

**Comment by taylorwaggoner** [comment]
@jbanimineni - I have sent you an invitation from Packet for your project.  Please let us know if you have any questions!

**Comment by jbanimineni** [comment]
Thank you, received the invitation and accepted.

Now can I provision and deploy  cluster?

**Comment by jbanimineni** [comment]
my mail I'd: jbanimineni@stackhatch.org

Packet Registered account mail I'd : accounts@stackhatch.org

**Comment by dankohn** [comment]
Yes.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by jbanimineni** [comment]
Can I use packet and cncf badges in our website as sponsered companies?

**Comment by jacobsmith928** [comment]
Always happy to have that @jbanimineni but not required.  Most important -> share your story with the CNCF if you find interesting results and use of the resources.  ![packet_logo_color](https://user-images.githubusercontent.com/7989673/45238131-cd1bb980-b2ae-11e8-9043-1eda1c10086a.png)

**Comment by taylorwaggoner** [comment]
Glad the invitation went through!  Yes, you should be all set then. Thanks!

**Comment by jbanimineni** [comment]
Sure, once cluster deployed will definitely share the results and our success story with CNCF.

Can I provision higher configuration of servers if required. Or else do I need to provision same configuration of servers which I requested?

**Comment by dankohn** [comment]
You can go higher, but please try to be reasonable.

Please don't use the CNCF logo, but we'd be happy to have a link saying,
"Server resources provided by Packet through the CNCF [Community
Infrastructure Lab](https://www.cncf.io/community/infrastructure-lab/)".
And, of course, you are welcome to use the Packet logo.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Hi, a recent email we received said that "once our publication goes live all the data is storing inside packet only if instances are terminated by someone from packet or CNCF I would loss the entire data". This sounds like a production environment you're trying to setup which is definitely not what the Packet-provided community cluster is intended to provide.

In addition, the source links that you provided above are now 404s. Unless we hear an update that convinces us otherwise, we'll be shutting down this service in a week. So, I urge you to back up all of the software and data and find a new hosting environment.
