### ISSUE TITLE
Access for Arch Linux

### ISSUE THREAD

**Issue by barthalion** [cncf/cluster#85]
### First and Last Name
Bartłomiej Piotrowski

### Email
bpiotrowski@archlinux.org

### Company/Organization
Arch Linux

### Title
Developer

### Project Title
Arch Linux

### Briefly describe the project
Arch Linux is an independently developed x86_64 general-purpose GNU/Linux distribution that strives to provide the latest stable versions of most software by following a rolling-release model. Technical decisions are driven by pragmatism, simplicity and do-acracy.

### Is the code that you’re going to run 100% open source?
Yes. The core of what will run is [devtools](https://git.archlinux.org/devtools.git/), our bash helper that automate creation of chroots used for build. There will be another service, likely written in Python, to provide further automations for larger rebuilds, but I can't say yet if we will write our own or simply use buildbot. PKGBUILD files that are build instructions for packaging tools are also open source and can be found [here](https://git.archlinux.org/svntogit/packages.git/) for core and extra repositories or [here](https://git.archlinux.org/svntogit/community.git/) for community and multilib.

Currently we are using Ansible to manage our infrastructure and our roles nad playbooks are publicly available [here](https://git.archlinux.org/infrastructure.git/).

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?

The goal is to offload our own infrastructure by spawning new builders (up to 3) only for heavy packages like GCC or rebuilds that entail over 20-30 packages. We have two dedicated machines (one at Hetzner and one somewhere in Singapore) that we usually use but sometimes it's not enough when multiple packagers need to build something. Most likely c2.medium.x86.

### What OS and networking are you planning to use

We would like to use the access to CNCF cluster to develop PXE scripts and/or ready image to be used for Packet.

### Any other relevant details we should know about?

In the future, when we migrate from one-svn-for-everything to single git repo per package, we would like to evaluate Gitlab and its container-based CI to provide automated build checks for packages.

**Comment by dankohn** [comment]
+1

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by taylorwaggoner** [comment]
@barthalion, I have sent you an invitation for Arch Linux in Packet.  Please let us know if you have any questions!

**Comment by barthalion** [comment]
Thank you!
