### ISSUE TITLE
Access to Flathub org for Dan Nicholson

### ISSUE THREAD

**Issue by ramcq** [cncf/cluster#91]
Can we add @dbnicholson (nicholson@endlessm.com) with access to the Flathub project on CNCF CIL?

**Comment by taylorwaggoner** [comment]
@ramcq I have sent nicholson@endlessm.com an invitation to join the Flathub project in Packet. Thanks!

**Comment by dbnicholson** [comment]
I got the invite and accepted it. Thanks!
