### ISSUE TITLE
Test of vpp support of MLX4 with Some distros.

### ISSUE THREAD

**Issue by tfherbert** [cncf/cluster#94]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

Thomas F Herbert

therbert@redhat.com

Red Hat

Principal Software Engineer

fd.io/NSM

### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)

Yes, fd.io/vpp 

1 bare metal machine with MLX4 IF

CentOS 7.6

Will need root or privileged account to load distro and install kmods and packages.

**Comment by dankohn** [comment]
+1

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by taylorwaggoner** [comment]
@tfherbert I've sent you an invitation for the fd.io/NSM project in Packet.  Thanks!
