### ISSUE TITLE
Envoy with Accelerated TLS offload

### ISSUE THREAD

**Issue by josepalafox** [cncf/cluster#95]
Please fill out the details below to file a request for access to the CNCF Community Infrastructure Lab. Please note that access is targeted to people working on specific open source projects; this is not designed just to get your feet wet. The most important answer is the URL of the project you'll be working with. If you're looking to learn Kubernetes and related technologies, please try out [Katacoda](https://www.katacoda.com/courses/kubernetes/playground).

### First and Last Name
Jose Palafox
### Email
Jose.palafox@intel.com
### Company/Organization
Intel
### Job Title
Program Manager
### Project Title (i.e., summary of what do you want to do, not what is the name of the open source project you're working with)
I work on exposing intel features to Kubernetes and other CNCF projects
### Briefly describe the project (i.e., what is the detail of what you're planning to do with these servers?)
We would like to test Envoy with accelerated TLS via Intel QAT 
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located? What is your association with that project?
https://github.com/intel/QAT_Engine
https://github.com/ipuustin/envoy
https://github.com/intel/intel-device-plugins-for-kubernetes

### What kind of machines and how many do you expect to use (see: https://www.packet.net/bare-metal/)?
We need at least 1 QAT enabled sku.

### What OS and networking are you planning to use (see: https://help.packet.net/technical/infrastructure/supported-operating-systems)?
Centos

**Comment by dankohn** [comment]
+1
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by taylorwaggoner** [comment]
@josepalafox I've sent you an invitation to the Intel project I created for you in Packet.  Let us know if you have any questions!

**Comment by josepalafox** [comment]
Hi @taylorwaggoner can you please add:
ismo.puustinen@intel.com
mikko.ylinen@intel.com
to the organization as well?

**Comment by taylorwaggoner** [comment]
@josepalafox I've added them, thanks!

**Comment by vielmetti** [comment]
Working on the "QAT enabled sku" part of this right now.

**Comment by vielmetti** [comment]
This project was completed in
