### ISSUE TITLE
Web page link to this repo is broken

### ISSUE THREAD

**Issue by vielmetti** [cncf/cluster#99]
At https://www.cncf.io/community/infrastructure-lab/ at the bottom:

Request access and then get up and running in minutes!

links to https://goo.gl/x6t8fB which is now a broken link:

404: Page not found – the page https://goo.gl/x6t8fB does not exist.

Not sure where the source code for this page is.

**Comment by taylorwaggoner** [comment]
@vielmetti thanks for letting us know.  I've updated the link.
